const lessons_json = {
    "lesson1": [
        { "latin": "yo", "japanese": "わたし" },
        { "latin": "tú, usted", "japanese": "あなた" },
        { "latin": "aquella persona", "japanese": ["あのひと", "あのかた"] },
        { "latin": ["señor", "señora", "señorita"], "japanese": "~さん" },
        { "latin": "chan", "japanese": "~ちゃん" },
        { "latin": "jin", "japanese": "~じん" },
        { "latin": ["maestro", "profesor", "instructor"], "japanese": "せんせい" },
        { "latin": ["maestro", "profesor", "instructor"], "japanese": "きょうし" },
        { "latin": "estudiante", "japanese": "がくせい" },
        { "latin": "empleado de la empresa", "japanese": "かいしゃいん" },
        { "latin": "empleado de la empresa", "japanese": "しゃいん" },
        { "latin": "empleado de un banco", "japanese": "ぎんこういん" },
        { "latin": "médico", "japanese": "いしゃ" },
        { "latin": "investigador", "japanese": "けんきゅうしゃ" },
        { "latin": "universidad", "japanese": "さいがく" },
        { "latin": "hospital", "japanese": "びょういん" },
        { "latin": "quién", "japanese": "だれ(どなた)" },
        { "latin": "años de edad", "japanese": "~さい" },
        { "latin": "cuántos años", "japanese": ["なんさい", "おいくつ"] },
        { "latin": "sí", "japanese": "はい" },
        { "latin": "no", "japanese": "いいえ" },

        { "latin": "1 años", "japanese": "いっさい" },
        { "latin": "2 años", "japanese": "にさい" },
        { "latin": "3 años", "japanese": "さんさい" },
        { "latin": "4 años", "japanese": "よんさい" },
        { "latin": "5 años", "japanese": "ごさい" },
        { "latin": "6 años", "japanese": "ろくさい" },
        { "latin": "7 años", "japanese": "ななさい" },
        { "latin": "8 años", "japanese": "はっさい" },
        { "latin": "9 años", "japanese": "きゅうさい" },
        { "latin": "10 años", "japanese": "じゅさい" }
    ],


    "lesson2": [
        { "latin": ["este", "esta", "esto"], "japanese": "これ" },
        { "latin": ["ese", "esa", "eso"], "japanese": "それ" },
        { "latin": ["aquel", "aquella", "aquello"], "japanese": "あれ" },
        { "latin": ["este~", "esta~"], "japanese": "この~" },
        { "latin": ["ese~", "esa~"], "japanese": "その~" },
        { "latin": ["aquel~", "aquella~"], "japanese": "あの~" },
        { "latin": ["libro"], "japanese": "ほん" },
        { "latin": "diccionario", "japanese": "じしょ" },
        { "latin": "revista", "japanese": "ざっし" },
        { "latin": "periódico", "japanese": "しんぶん" },
        { "latin": "cuaderno", "japanese": "ノート" },
        { "latin": "agenda", "japanese": "てちょお" },
        { "latin": "tarjeta de visita", "japanese": "めいし" },
        { "latin": "tarjeta", "japanese": "カード" },
        { "latin": "lápiz", "japanese": "えんぴつ" },
        { "latin": "bolígrafo", "japanese": "ボールペン" },
        { "latin": "portaminas", "japanese": "シャープペンシル" },
        { "latin": "llave", "japanese": "かぎ" },
        { "latin": "reloj", "japanese": "とけい" },
        { "latin": "paraguas", "japanese": "かさ" },
        { "latin": "bolso, maleta", "japanese": "かばん" },
        { "latin": "CD", "japanese": "CD" },
        { "latin": ["televisión", "televisor"], "japanese": "テレビ" },
        { "latin": "radio", "japanese": "ラジオ" },
        { "latin": "máquina fotográfica", "japanese": "カメラ" },
        { "latin": "ordenador", "japanese": "コンピューター" },
        { "latin": ["coche", "automóvil"], "japanese": "くるま" },
        { "latin": "escritorio", "japanese": "つくえ" },
        { "latin": "silla", "japanese": "いす" },
        { "latin": "chocolate", "japanese": "チョコレート" },
        { "latin": "café", "japanese": "コーヒー" },
        { "latin": ["souvenir", "recuerdo de un viaje", "regalo que se lleva al visitar a alguien"], "japanese": "[お]みやげ" },
        { "latin": "el idioma inglés", "japanese": "えいご" },
        { "latin": "el idioma japonés", "japanese": "にほんご" },
        { "latin": "idioma~", "japanese": "~ご" },
        { "latin": "qué", "japanese": "なん" },
        { "latin": "sí, eso", "japanese": "そう" }
    ],


    "lesson3": [
        { "latin": ["aquí", "este lugar"], "japanese": "ここ" },
        { "latin": ["ahí", "ese lugar"], "japanese": "そこ" },
        { "latin": ["allí", "aquel lugar"], "japanese": "あそこ" },
        { "latin": ["dónde", "en qué lugar"], "japanese": "そこ" },
        { "latin": ["por aquí", "aquí"], "japanese": "こちら" },
        { "latin": ["por ahí", "ahí"], "japanese": "そちら" },
        { "latin": ["por allí", "allí"], "japanese": "あちら" },
        { "latin": ["por dónde", "dónde"], "japanese": "どちら" },
        { "latin": "aula", "japanese": "きょうしつ" },
        { "latin": "comedor", "japanese": "しょくどう" },
        { "latin": "oficina", "japanese": "きむしょ" },
        { "latin": "sala de reuniones", "japanese": "かいぎしつ" },
        { "latin": "recepción", "japanese": "うけつけ" },
        { "latin": ["recepción", "vestíbulo"], "japanese": "ロビー" },
        { "latin": ["habitación", "cuarto"], "japanese": "へや" },
        { "latin": ["baño", "servicio"], "japanese": "トイレ（おてあらい）" },
        { "latin": "escalera", "japanese": "かいだん" },
        { "latin": "ascensor", "japanese": "エレベーター" },
        { "latin": "escalera mecánica", "japanese": "エスカレーター" },
        { "latin": "máquina expendedora", "japanese": "じどうはんばいき" },
        { "latin": ["teléfono", "llamada telefónica"], "japanese": "でんわ" },
        { "latin": ["país", "patria"], "japanese": "［お］くに" },
        { "latin": ["empresa", "compañía", "firma"], "japanese": "かいしゃ" },
        { "latin": "casa", "japanese": "うち、いえ" },
        { "latin": "zapatos", "japanese": "くつ" },
        { "latin": "corbata", "japanese": "ネクタイ" },
        { "latin": "vino", "japanese": "ワイン" },
        { "latin": "sección", "japanese": "うりば" },
        { "latin": "sótano", "japanese": "ちか" },
        { "latin": ["piso", "planta"], "japanese": "ーかい（ーがい）" },
        { "latin": "qué piso", "japanese": "なんがい" },
        { "latin": "yen", "japanese": "ーえん" },
        { "latin": "cuánto", "japanese": "いくら" },
        { "latin": "cien", "japanese": "ひゃく" },
        { "latin": "mil", "japanese": "せん" },
        { "latin": "diez mil", "japanese": "まん" }
    ],


    "lesson4": [
        { "latin": "levantarse", "japanese": "おきます" },
        { "latin": ["acostarse", "ir a la cama"], "japanese": "ねます" },
        { "latin": "trabajar", "japanese": "はたらきませ" },
        { "latin": ["descansar", "estar de vacaciones"], "japanese": "やすみます" },
        { "latin": "estudiar", "japanese": "べんきょします" },
        { "latin": "terminar", "japanese": "おわります" },
        { "latin": "grandes almacenes", "japanese": "デパート" },
        { "latin": "banco", "japanese": "ぎんこう" },
        { "latin": "oficina de correos", "japanese": "ゆうびんきょく" },
        { "latin": "biblioteca", "japanese": "としょかん" },
        { "latin": "museo de arte", "japanese": "びじゅつかん" },
        { "latin": "ahora", "japanese": "いま" },
        { "latin": "hora", "japanese": "ーじ" },
        { "latin": "minutos", "japanese": "ーふん、ーぷん" },
        { "latin": "y media", "japanese": "はん" },
        { "latin": "¿qué hora?", "japanese": "なんじ" },
        { "latin": "¿qué minuto?", "japanese": "なんぷん" },
        { "latin": ["la mañana", "AM"], "japanese": "ごぜん" },
        { "latin": ["la tarde", "PM", "por la tarde"], "japanese": "ごご" },
        { "latin": "por la mañana", "japanese": "あさ" },
        { "latin": ["día", "mediodía"], "japanese": "ひる" },
        { "latin": "noche", "japanese": "ばん、よる" },
        { "latin": "anteayer", "japanese": "おととい" },
        { "latin": "ayer", "japanese": "きのう" },
        { "latin": "hoy", "japanese": "きょう" },
        { "latin": "mañana", "japanese": "あした" },
        { "latin": "pasado mañana", "japanese": "あさって" },
        { "latin": "esta mañana", "japanese": "けさ" },
        { "latin": "esta noche", "japanese": "こんばん" },
        { "latin": ["descanso", "día libre"], "japanese": "やすみ" },
        { "latin": "descanso de mediodía", "japanese": "ひるやすみ" },
        { "latin": "número", "japanese": "ばんごう" },
        { "latin": "qué número", "japanese": "なんばん" },
        { "latin": "examen", "japanese": "しけん" },
        { "latin": "reunión", "japanese": "かいぎ" },
        { "latin": "película", "japanese": "えいが" },
        { "latin": "todas las mañanas", "japanese": "まいあさ" },
        { "latin": "todas las noches", "japanese": "まいばん" },
        { "latin": "todos los días", "japanese": "まいにち" },
        { "latin": "lunes", "japanese": "げつようび" },
        { "latin": "martes", "japanese": "かようび" },
        { "latin": "miércoles", "japanese": "すいようび" },
        { "latin": "jueves", "japanese": "もくようび" },
        { "latin": "viernes", "japanese": "きんようび" },
        { "latin": "sábado", "japanese": "どようび" },
        { "latin": "domingo", "japanese": "にちようび" },
        { "latin": "desde ~", "japanese": "～から" },
        { "latin": "hasta ~", "japanese": "～まで" },
        { "latin": "y", "japanese": "～と～" }
    ],


    "lesson5": [
        { "latin": "ir", "japanese": "いきます" },
        { "latin": "venir", "japanese": "きます" },
        { "latin": "volver, regresar, irse a casa", "japanese": "かえります" },
        { "latin": "escuela", "japanese": "がっこう" },
        { "latin": "supermercado", "japanese": "スーパー" },
        { "latin": "estación", "japanese": "えき" },
        { "latin": "avión", "japanese": "ひこうき" },
        { "latin": "barco", "japanese": "ふね" },
        { "latin": "tren eléctrico", "japanese": "でんしゃ" },
        { "latin": "metro", "japanese": "ちかてつ" },
        { "latin": "shinkansen, tren bala", "japanese": "しんかんせん" },
        { "latin": "autobús", "japanese": "バス" },
        { "latin": "taxi", "japanese": "タクシー" },
        { "latin": "bicicleta", "japanese": "じてんしゃ" },
        { "latin": "a pie, andando", "japanese": "あるいて" },
        { "latin": "persona, gente", "japanese": "ひと" },
        { "latin": "amigo(s)", "japanese": "ともだち" },
        { "latin": "él, novio", "japanese": "かれ" },
        { "latin": "ella, novia", "japanese": "かのじょ" },
        { "latin": "familia", "japanese": "かぞく" },
        { "latin": "solo", "japanese": "ひとりで" },
        { "latin": "la semana pasada", "japanese": "せんしゅう" },
        { "latin": "esta semana", "japanese": "こんしゅう" },
        { "latin": "la semana que viene", "japanese": "らいしゅう" },
        { "latin": "el mes pasado", "japanese": "せんげつ" },
        { "latin": "este mes", "japanese": "こんげつ" },
        { "latin": "el mes que viene", "japanese": "らいげつ" },
        { "latin": "el año pasado", "japanese": "きょねん" },
        { "latin": "este año", "japanese": "ことし" },
        { "latin": "el año que viene", "japanese": "らいねん" },
        { "latin": "año ー", "japanese": "ーねん" },
        { "latin": "qué año", "japanese": "なんねん" },
        { "latin": "mes de", "japanese": "ーげつ" },
        { "latin": "qué mes", "japanese": "なんがつ" },
        { "latin": "el día uno", "japanese": "ついたち" },
        { "latin": "el día dos, 2 días", "japanese": "ふつか" },
        { "latin": "el día cuatro, 4 días", "japanese": "みっか" },
        { "latin": "el día tres, 3 días", "japanese": "よっか" },
        { "latin": "el día seis, 6 días", "japanese": "いつか" },
        { "latin": "el día cinco, 5 días", "japanese": "むいか" },
        { "latin": "el día ocho, 8 días", "japanese": "なのか" },
        { "latin": "el día siete, 7 días", "japanese": "ようか" },
        { "latin": "el día diez, 10 días", "japanese": "ここのか" },
        { "latin": "el día nueve, 9 días", "japanese": "とおか" },
        { "latin": "el día veinte, 20 días", "japanese": "じゅうよっか" },
        { "latin": "el día catorce, 14 días", "japanese": "はつか" },
        { "latin": "díaー, ーdía(s)", "japanese": "にじゅうよっか" },
        { "latin": "el día veinticuatro, 24 días", "japanese": "ーにち" },
        { "latin": "cuándo", "japanese": "なんいち" },
        { "latin": "qué día del mes, cuántos días", "japanese": "いつ" },
        { "latin": "a ningún sitio", "japanese": "たんじょうび" },
        { "latin": "cumpleaños", "japanese": "どこ「へ」も（いきませんでした" },
        { "latin": "hacer solo", "japanese": "一で verb + します" }
    ],


    "lesson6": [
        { "latin": "comer", "japanese": "たべます" },
        { "latin": ["beber", "tomar"], "japanese": "のみます" },
        { "latin": "fumar", "japanese": "すいます" },
        { "latin": ["ver", "mirar"], "japanese": "みます" },
        { "latin": ["oír", "escuchar"], "japanese": "ききます" },
        { "latin": "leer", "japanese": "よみます" },
        { "latin": ["escribir", "dibujar"], "japanese": "かきます" },
        { "latin": "comprar", "japanese": "かいます" },
        { "latin": "sacar fotos", "japanese": "しゃしんをとります" },
        { "latin": "hacer", "japanese": "します" },
        { "latin": ["ver a", "encontrarse con"], "japanese": "あります" },
        { "latin": ["comida", "arroz cocido"], "japanese": "ごはん" },
        { "latin": "desayuno", "japanese": "あさごはん" },
        { "latin": ["almuerzo", "comida"], "japanese": "ひるごはん" },
        { "latin": "cena", "japanese": "ばんごはん" },
        { "latin": "pan", "japanese": "パン" },
        { "latin": "huevo", "japanese": "たまご" },
        { "latin": "carne", "japanese": "にく" },
        { "latin": ["pescado", "pez"], "japanese": "さかな" },
        { "latin": "verduras", "japanese": "やさい" },
        { "latin": "frutas", "japanese": "くだもの" },
        { "latin": "agua", "japanese": "みず" },
        { "latin": ["té", "té verde"], "japanese": "おちゃ" },
        { "latin": ["té negro", "té inglés"], "japanese": "こちゃ" },
        { "latin": "leche", "japanese": ["ぎゅうにゅう", "ミルク"] },
        { "latin": ["zumo", "refresco"], "japanese": "ジューズ" },
        { "latin": "cerveza", "japanese": "ビール" },
        { "latin": ["bebida alcohólica", "sake"], "japanese": "さけ" },
        { "latin": ["cigarrillo", "tabaco"], "japanese": "たばこ" },
        { "latin": ["carta", "correspondencia"], "japanese": "てがみ" },
        { "latin": ["informe", "reporte"], "japanese": "レポート" },
        { "latin": "fotografía", "japanese": "しゃしん" },
        { "latin": "video", "japanese": "ビデオ" },
        { "latin": ["tienda", "negocio"], "japanese": "みせ" },
        { "latin": "jardín", "japanese": "にわ" },
        { "latin": ["deberes", "tarea"], "japanese": "しゅくだい" },
        { "latin": "tenis", "japanese": "テニス" },
        { "latin": "fútbol", "japanese": "サッカー" },
        { "latin": "ver cerezos en flor", "japanese": "はなみ" },
        { "latin": "qué", "japanese": "なに" },
        { "latin": ["junto", "juntos"], "japanese": "いっしょに" },
        { "latin": "un poco", "japanese": "ちょっと" },
        { "latin": ["siempre", "normalmente"], "japanese": "いつも" },
        { "latin": ["de vez en cuando", "a veces"], "japanese": "ときどき" },
        { "latin": ["y luego", "y después"], "japanese": "それから" },
        { "latin": "sí", "japanese": "ええ" },
        { "latin": "es buena idea", "japanese": "いいですね" },
        { "latin": ["entendido", "muy bien"], "japanese": "わかりました" }
    ],


    "lesson7": [
        { "latin": "cortar", "japanese": "きります" },
        { "latin": "enviar", "japanese": "おくります" },
        { "latin": "dar", "japanese": "あげます" },
        { "latin": "recibir", "japanese": "もらいます" },
        { "latin": "prestar", "japanese": "かします" },
        { "latin": "tomar prestado", "japanese": "かります" },
        { "latin": "enseñar", "japanese": "おしえます" },
        { "latin": "aprender", "japanese": "ならいます" },
        { "latin": "hacer una llamada", "japanese": "でんわをかけます" },
        { "latin": "mano", "japanese": "て" },
        { "latin": "palillos", "japanese": "はし" },
        { "latin": "cuchara", "japanese": "スプーン" },
        { "latin": "cuchillo", "japanese": "ナイフ" },
        { "latin": "tenedor", "japanese": "フォーク" },
        { "latin": "tijeras", "japanese": "はさみ" },
        { "latin": "ordenador", "japanese": "パソコン" },
        { "latin": "teléfono móvil", "japanese": "ケータイ" },
        { "latin": ["email", "correo electrónico"], "japanese": "メール" },
        { "latin": "tarjeta de año nuevo", "japanese": "ねんがじょう" },
        { "latin": "perforadora", "japanese": "パンチ" },
        { "latin": "grapadora", "japanese": "ホッチキス" },
        { "latin": "cinta adhesiva", "japanese": "セロテープ" },
        { "latin": "goma de borrar", "japanese": "けしゴム" },
        { "latin": "papel", "japanese": "かみ" },
        { "latin": "flor", "japanese": "はな" },
        { "latin": "camisa", "japanese": "シャツ" },
        { "latin": "regalo", "japanese": "プレセント" },
        { "latin": ["equipaje", "paquete"], "japanese": "にもつ" },
        { "latin": "dinero", "japanese": "おかね" },
        { "latin": "billete", "japanese": "きっぷ" },
        { "latin": "Navidad", "japanese": "クリスマス" },
        { "latin": "mi padre", "japanese": "ちち" },
        { "latin": "mi madre", "japanese": "はは" },
        { "latin": "padre", "japanese": "おとうさん" },
        { "latin": "madre", "japanese": "おかあさん" },
        { "latin": "ya", "japanese": "もう" },
        { "latin": "todavía", "japanese": "まだ" },
        { "latin": ["desde ahora", "dentro de poco"], "japanese": "これから" }
    ],


    "lesson8": [
        { "latin": "guapo", "japanese": "ハンサム「な」" },
        { "latin": ["hermoso", "limpio"], "japanese": "きれい「な」" },
        { "latin": "silencioso", "japanese": "しずか「な」" },
        { "latin": ["concurrido", "animado"], "japanese": "にぎやか「な」" },
        { "latin": ["famoso", "célebre"], "japanese": "ゆうめい「な」" },
        { "latin": ["amable", "generoso"], "japanese": "しんせつ「な」" },
        { "latin": ["sano", "con ánimo"], "japanese": "げんき「な」" },
        { "latin": "estar libre", "japanese": "ひま「な」" },
        { "latin": ["útil", "práctico", "conveniente"], "japanese": "べんり「な」" },
        { "latin": ["bonito", "precioso"], "japanese": "すてき「な」" },
        { "latin": "grande", "japanese": "おおきい" },
        { "latin": "pequeño", "japanese": "ちいさい" },
        { "latin": "nuevo", "japanese": "あたらしい" },
        { "latin": ["antiguo", "viejo"], "japanese": "ふるい" },
        { "latin": "bueno", "japanese": ["いい", "よい"] },
        { "latin": "malo", "japanese": "わるい" },
        { "latin": ["caluroso", "caliente"], "japanese": "あつい" },
        { "latin": "frío", "japanese": "さむい" },
        { "latin": "frío", "japanese": "つめたい" },
        { "latin": "difícil", "japanese": "むずかしい" },
        { "latin": ["fácil", "amable"], "japanese": "やさしい" },
        { "latin": "fácil", "japanese": "かんたん「な」" },
        { "latin": ["caro", "alto"], "japanese": "たかい" },
        { "latin": "barato", "japanese": "やすい" },
        { "latin": "bajo", "japanese": "ひくい" },
        { "latin": ["interesante", "gracioso"], "japanese": "おもしろい" },
        { "latin": ["delicioso", "sabroso", "rico"], "japanese": "おいしい" },
        { "latin": ["atareado", "ocupado"], "japanese": "おそがしい" },
        { "latin": ["divertido", "placentero"], "japanese": "たのしい" },
        { "latin": "blanco", "japanese": "しろい" },
        { "latin": "negro", "japanese": "くろい" },
        { "latin": "rojo", "japanese": "あかい" },
        { "latin": "azul", "japanese": "あおい" },
        { "latin": ["árbol de cerezo", "flor de cerezo"], "japanese": "さくら" },
        { "latin": "montaña", "japanese": "やま" },
        { "latin": ["población", "ciudad"], "japanese": "まち" },
        { "latin": ["comida", "alimentos"], "japanese": "たべもの" },
        { "latin": "lugar", "japanese": "ところ" },
        { "latin": ["residencia", "dormitorios"], "japanese": "りょう" },
        { "latin": "restaurante", "japanese": "レストラン" },
        { "latin": "vida diaria", "japanese": "せいかつ" },
        { "latin": ["trabajo", "profesión"], "japanese": "「お」しごと" },
        { "latin": "cómo", "japanese": "どう" },
        { "latin": "qué clase de", "japanese": "どんな" },
        { "latin": ["muy", "mucho"], "japanese": "とても" },
        { "latin": ["no muy", "no mucho"], "japanese": "あまり" },
        { "latin": "y", "japanese": "そして" },
        { "latin": "pero", "japanese": "～が、～" }
    ],


    "lesson9": [
        { "latin": ["entender", "comprender"], "japanese": "わかります" },
        { "latin": ["haber", "estar", "existir"], "japanese": "あります" },
        { "latin": "gustar", "japanese": "すき" },
        { "latin": ["odiar", "detestar"], "japanese": "きらい" },
        { "latin": ["ser bueno", "ser hábil"], "japanese": "じょうず" },
        { "latin": ["ser malo", "ser inhábil"], "japanese": "へた" },
        { "latin": "bebida", "japanese": "のみもの" },
        { "latin": ["cocina", "plato"], "japanese": "りょうり" },
        { "latin": "deporte", "japanese": "スポーツ" },
        { "latin": "béisbol", "japanese": "やきゅう" },
        { "latin": "baile", "japanese": "ダンス" },
        { "latin": "viaje", "japanese": "りょこう" },
        { "latin": "música", "japanese": "おんがく" },
        { "latin": "canción", "japanese": "うた" },
        { "latin": "música clásica", "japanese": "クラシック" },
        { "latin": "jazz", "japanese": "ジャズ" },
        { "latin": "concierto", "japanese": "コンサート" },
        { "latin": "día laboral", "japanese": "へいじつ" },
        { "latin": "día festivo", "japanese": "きゅくじつ" },
        { "latin": "día", "japanese": "じつ" },
        { "latin": "karaoke", "japanese": "カラオケ" },
        { "latin": "kabuki", "japanese": "かぶき" },
        { "latin": ["pintura", "dibujo", "cuadro"], "japanese": "え" },
        { "latin": "letra", "japanese": "じ" },
        { "latin": "caracteres chinos", "japanese": "かんじ" },
        { "latin": "hiragana", "japanese": "ひらがな" },
        { "latin": "katakana", "japanese": "カタカナ" },
        { "latin": "alfabeto latino", "japanese": "ローマじ" },
        { "latin": ["dinero suelto", "en monedas"], "japanese": "こまかいおかね" },
        { "latin": "detallista", "japanese": "こまかい" },
        { "latin": "entrada", "japanese": "チケット" },
        { "latin": "tiempo", "japanese": "じかん" },
        { "latin": "algo que hacer", "japanese": "ようじ" },
        { "latin": ["cita", "compromiso", "promesa"], "japanese": "やくそく" },
        { "latin": ["trabajo temporal", "trabajo eventual"], "japanese": "アルバイト" },
        { "latin": "todo", "japanese": "ぜんぶ" },
        { "latin": "crear", "japanese": "つくります" },
        { "latin": ["su marido", "tu marido"], "japanese": "ごしゅじん" },
        { "latin": ["mi marido", "mi esposo"], "japanese": ["おっと", "しゅじん"] },
        { "latin": ["su esposa", "tu esposa"], "japanese": "おくさん" },
        { "latin": "mi esposa", "japanese": ["つま", "かない"] },
        { "latin": ["niño", "mi hijo"], "japanese": "こども" },
        { "latin": ["bien", "mucho"], "japanese": "よく" },
        { "latin": ["más o menos", "aproximadamente"], "japanese": "だいたい" },
        { "latin": "mucho", "japanese": "たくさん" },
        { "latin": ["poco", "un poco"], "japanese": "すこし" },
        { "latin": "nada", "japanese": "ぜんぜん" },
        { "latin": ["temprano", "rápido"], "japanese": "はやく" },
        { "latin": "porque", "japanese": "～から" },
        { "latin": "por qué", "japanese": "どうして" },
        { "latin": "sano", "japanese": "けんこう" },
        { "latin": "flexible", "japanese": "フレキシブル" },
        { "latin": "dolor", "japanese": "いたい" },
        { "latin": "cabeza", "japanese": "あたま" },
        { "latin": "querer", "japanese": "したい" },
        { "latin": ["guapo", "guay"], "japanese": "かっこいい" }
    ],


    "lesson10": [
        { "latin": ["estar", "haber", "existir"], "japanese": "あります" },
        { "latin": ["estar", "haber", "existir"], "japanese": "います" },
        { "latin": "diversos", "japanese": "いろいろ「な」" },
        { "latin": "hombre", "japanese": "おとこのひと" },
        { "latin": "mujer", "japanese": "おんなのひと" },
        { "latin": "niño", "japanese": "おとこのこ" },
        { "latin": "niña", "japanese": "おんなのこ" },
        { "latin": "perro", "japanese": "いぬ" },
        { "latin": "perrito", "japanese": "こいぬ" },
        { "latin": "gato", "japanese": "ねこ" },
        { "latin": "gatito", "japanese": "こねこ" },
        { "latin": "panda", "japanese": "パンダ" },
        { "latin": "elefante", "japanese": "ぞう" },
        { "latin": "caballo", "japanese": "うま" },
        { "latin": ["árbol", "madera"], "japanese": "き" },
        { "latin": ["cosa", "objeto"], "japanese": "もの" },
        { "latin": ["pila", "batería"], "japanese": "でんち" },
        { "latin": "caja", "japanese": "はこ" },
        { "latin": "cajón", "japanese": "ひきだし" },
        { "latin": "interruptor", "japanese": "スイッチ" },
        { "latin": ["refrigerador", "nevera"], "japanese": "れいぞうこ" },
        { "latin": "congelador", "japanese": "れいとうこ" },
        { "latin": "taza", "japanese": "マグカップ" },
        { "latin": "vaso", "japanese": "コップ" },
        { "latin": "mesa", "japanese": "テーブル" },
        { "latin": "cama", "japanese": "ベッド" },
        { "latin": "estante", "japanese": "たな" },
        { "latin": "puerta", "japanese": "ドア" },
        { "latin": "ventana", "japanese": "まど" },
        { "latin": "buzón", "japanese": "ポスト" },
        { "latin": "construir", "japanese": "たてもす" },
        { "latin": "edificio de oficinas", "japanese": "ビル" },
        { "latin": "edificio", "japanese": "たてもの" },
        { "latin": ["ATM", "cajero automático"], "japanese": "ATM" },
        { "latin": ["tienda de conveniencia", "tienda de 24 horas"], "japanese": "コンビニ" },
        { "latin": "parque", "japanese": "こうえん" },
        { "latin": "cafetería", "japanese": "きっさてん" },
        { "latin": "tienda de", "japanese": "～や" },
        { "latin": "parada", "japanese": "のりば" },
        { "latin": "provincia", "japanese": "けん" },
        { "latin": ["encima", "arriba"], "japanese": "うえ" },
        { "latin": ["debajo", "abajo"], "japanese": "した" },
        { "latin": ["delante", "adelante", "en frente"], "japanese": "まえ" },
        { "latin": ["montar", "subir"], "japanese": "のります" },
        { "latin": "aire acondicionado", "japanese": "エアコン" },
        { "latin": ["detrás", "atrás"], "japanese": "うしろ" },
        { "latin": "derecha", "japanese": "みぎ" },
        { "latin": "izquierda", "japanese": "ひだり" },
        { "latin": "dentro", "japanese": "なか" },
        { "latin": "fuera", "japanese": "そと" },
        { "latin": "al lado", "japanese": ["となり", "よこ"] },
        { "latin": "cerca", "japanese": "ちかく" },
        { "latin": "lejos", "japanese": "とおく" },
        { "latin": "entre", "japanese": "あいだ" },
        { "latin": "y entre otros", "japanese": "～や ～「など」" },
        { "latin": "banco", "japanese": "ベンチ" },
        { "latin": "camión", "japanese": "トラック" },
        { "latin": "animal", "japanese": "どうぶつ" },
        { "latin": "zoo", "japanese": "どうぶつえん" },
        { "latin": "zona al aire libre", "japanese": "えん" },
        { "latin": "chanclas", "japanese": "ビーチサンダル" },
        { "latin": "sandalias", "japanese": "サンダル" },
        { "latin": ["barrio", "distrito"], "japanese": "ちいき" },
        { "latin": "pasear", "japanese": "さんぽ「を」します" },
        { "latin": "línea de transporte público", "japanese": "せん" },
        { "latin": "plaza", "japanese": "ひろば" },
        { "latin": ["sección", "esquina"], "japanese": "コーナー" },
        { "latin": "centro", "japanese": "まんなか" },
        { "latin": "al fondo", "japanese": "おく" },
        { "latin": "despertar", "japanese": "めぎまし" },
        { "latin": "reloj despertador", "japanese": "めぎましどけい" },
        { "latin": "brazo", "japanese": "うで" },
        { "latin": "reloj de muñeca", "japanese": "うでどけい" },
        { "latin": "estadio", "japanese": "スタジアム" },
        { "latin": "estadio", "japanese": "ドーム" },
        { "latin": "padres", "japanese": "りょうしん" },
        { "latin": "juego de mesa", "japanese": "ポードゲーム" }
    ],


    "lesson11": [
        { "latin": "tener hijos", "japanese": "「こどもが」います" },
        { "latin": ["estar", "permanecer"], "japanese": "います" },
        { "latin": ["tardar", "costar"], "japanese": "かかります" },
        { "latin": ["ausentarse", "faltar"], "japanese": "やすみます" },
        { "latin": ["cuántos", "cuántas"], "japanese": "いくら" },
        { "latin": "una persona", "japanese": "ひとり" },
        { "latin": "dos personas", "japanese": "ふたり" },

        { "latin": "objetos", "japanese": "ーつ" },
        { "latin": "personas", "japanese": "ーにん" },
        { "latin": "orden", "japanese": "ーばん" },
        { "latin": ["objetos finos y planos", "objetos planos y finos"], "japanese": "ーまい" },
        { "latin": ["máquinas", "vehículos"], "japanese": "ーだい" },
        { "latin": "edad", "japanese": "ーさい" },
        { "latin": ["libros", "cuadernos"], "japanese": "ーさつ" },
        { "latin": "ropas", "japanese": "ーちゃく" },
        { "latin": "frecuencia", "japanese": "ーかい" },
        { "latin": "objetos pequeños", "japanese": "ーこ" },
        { "latin": ["calzados", "calcetines"], "japanese": ["ーそく","ーぞく"] },
        { "latin": "viviendas", "japanese": ["ーけん","ーげん"] },
        { "latin": ["pisos", "plantas"], "japanese": ["ーかい","ーがい"] },
        { "latin": ["objetos delgados y largos", "objetos largos y delgados"], "japanese": ["ーほん","ーぼん", "ーぽん"] },
        { "latin": ["bebidas", "vasos", "copas", "tazas"], "japanese": ["ーはい","ーばい", "ーぱい"] },
        { "latin": ["animales pequeños", "peces", "insectos"], "japanese": ["ーひき","ーびき", "ーぴき"] },
        
        { "latin": "manzana", "japanese": "りんご" },
        { "latin": "mandarina", "japanese": "みかん" },
        { "latin": "sándwich", "japanese": "サンドイッチ" },
        { "latin": "curry con arroz", "japanese": "カレーライス" },
        { "latin": "helado", "japanese": "アイスクリーム" },
        { "latin": "sello postal", "japanese": "きって" },
        { "latin": "tarjeta postal", "japanese": "はがき" },
        { "latin": "sobre", "japanese": "ふうとう" },
        { "latin": "padres", "japanese": "りょうしん" },
        { "latin": "hermanas", "japanese": "しまい" },
        { "latin": "hermanos", "japanese": "きょうだい" },
        { "latin": "mi hermano mayor", "japanese": "あに" },
        { "latin": "hermano mayor", "japanese": "おにいさん" },
        { "latin": "mi hermana mayor", "japanese": "あね" },
        { "latin": "hermana mayor", "japanese": "おねえさん" },
        { "latin": "hermano pequeño", "japanese": "あとうと" },
        { "latin": "hermana pequeña", "japanese": "いもうと" },
        { "latin": "país extranjero", "japanese": "がいこく" },
        { "latin": "extranjero", "japanese": "がいこくじん" },
        { "latin": "estudiante extranjero", "japanese": "りゅうがくせい" },
        { "latin": "clase", "japanese": "クラス" },
        { "latin": "horas", "japanese": "ーじかん" },
        { "latin": "semanas", "japanese": "ーしゅうかん" },
        { "latin": "meses", "japanese": "ーかげつ" },
        { "latin": "años", "japanese": "ーねん" },
        { "latin": "alrededor de", "japanese": "～ぐらい" },
        { "latin": ["cuánto tiempo", "cuánta cantidad"], "japanese": "どのくらい" },
        { "latin": "en total", "japanese": "ぜんぶで" },
        { "latin": "todos", "japanese": "みんな" },
        { "latin": "solo", "japanese": "～だけ" },
        { "latin": "descansar", "japanese": "きゅうけいします" },
        { "latin": "descanso", "japanese": "きゅうけい" },
        { "latin": "patinar", "japanese": "スケートボード" }
    ]
}