const lessons_json = {
    "lesson1": [
        { "latin": "yo", "japanese": "わたし" },
        { "latin": "tú, usted", "japanese": "あなた" },
        { "latin": "aquella persona", "japanese": ["あのひと", "あのかた"] },
        { "latin": ["señor", "señora", "señorita"], "japanese": "~さん" },
        { "latin": "chan", "japanese": "~ちゃん" },
        { "latin": "jin", "japanese": "~じん" },
        { "latin": ["maestro", "profesor", "instructor"], "japanese": "せんせい" },
        { "latin": ["maestro", "profesor", "instructor"], "japanese": "きょうし" },
        { "latin": "estudiante", "japanese": "がくせい" },
        { "latin": "empleado de la empresa", "japanese": "かいしゃいん" },
        { "latin": "empleado de la empresa", "japanese": "しゃいん" },
        { "latin": "empleado de un banco", "japanese": "ぎんこういん" },
        { "latin": "médico", "japanese": "いしゃ" },
        { "latin": "investigador", "japanese": "けんきゅうしゃ" },
        { "latin": "universidad", "japanese": "さいがく" },
        { "latin": "hospital", "japanese": "びょういん" },
        { "latin": "quién", "japanese": "だれ(どなた)" },
        { "latin": "años de edad", "japanese": "~さい" },
        { "latin": "cuántos años", "japanese": ["なんさい", "おいくつ"] },
        { "latin": "sí", "japanese": "はい" },
        { "latin": "no", "japanese": "いいえ" },

        { "latin": "1 años", "japanese": "いっさい" },
        { "latin": "2 años", "japanese": "にさい" },
        { "latin": "3 años", "japanese": "さんさい" },
        { "latin": "4 años", "japanese": "よんさい" },
        { "latin": "5 años", "japanese": "ごさい" },
        { "latin": "6 años", "japanese": "ろくさい" },
        { "latin": "7 años", "japanese": "ななさい" },
        { "latin": "8 años", "japanese": "はっさい" },
        { "latin": "9 años", "japanese": "きゅうさい" },
        { "latin": "10 años", "japanese": "じゅさい" }
    ],


    "lesson2": [
        { "latin": ["este", "esta", "esto"], "japanese": "これ" },
        { "latin": ["ese", "esa", "eso"], "japanese": "それ" },
        { "latin": ["aquel", "aquella", "aquello"], "japanese": "あれ" },
        { "latin": ["este~", "esta~"], "japanese": "この~" },
        { "latin": ["ese~", "esa~"], "japanese": "その~" },
        { "latin": ["aquel~", "aquella~"], "japanese": "あの~" },
        { "latin": ["libro"], "japanese": "ほん" },
        { "latin": "diccionario", "japanese": "じしょ" },
        { "latin": "revista", "japanese": "ざっし" },
        { "latin": "periódico", "japanese": "しんぶん" },
        { "latin": "cuaderno", "japanese": "ノート" },
        { "latin": "agenda", "japanese": "てちょお" },
        { "latin": "tarjeta de visita", "japanese": "めいし" },
        { "latin": "tarjeta", "japanese": "カード" },
        { "latin": "lápiz", "japanese": "えんぴつ" },
        { "latin": "bolígrafo", "japanese": "ボールペン" },
        { "latin": "portaminas", "japanese": "シャープペンシル" },
        { "latin": "llave", "japanese": "かぎ" },
        { "latin": "reloj", "japanese": "とけい" },
        { "latin": "paraguas", "japanese": "かさ" },
        { "latin": "bolso, maleta", "japanese": "かばん" },
        { "latin": "CD", "japanese": "CD" },
        { "latin": ["televisión", "televisor"], "japanese": "テレビ" },
        { "latin": "radio", "japanese": "ラジオ" },
        { "latin": "máquina fotográfica", "japanese": "カメラ" },
        { "latin": "ordenador", "japanese": "コンピューター" },
        { "latin": ["coche", "automóvil"], "japanese": "くるま" },
        { "latin": "escritorio", "japanese": "つくえ" },
        { "latin": "silla", "japanese": "いす" },
        { "latin": "chocolate", "japanese": "チョコレート" },
        { "latin": "café", "japanese": "コーヒー" },
        { "latin": ["souvenir", "recuerdo de un viaje", "regalo que se lleva al visitar a alguien"], "japanese": "[お]みやげ" },
        { "latin": "el idioma inglés", "japanese": "えいご" },
        { "latin": "el idioma japonés", "japanese": "にほんご" },
        { "latin": "idioma~", "japanese": "~ご" },
        { "latin": "qué", "japanese": "なん" },
        { "latin": "sí, eso", "japanese": "そう" }
    ],


    "lesson3": [
        { "latin": ["aquí", "este lugar"], "japanese": "ここ" },
        { "latin": ["ahí", "ese lugar"], "japanese": "そこ" },
        { "latin": ["allí", "aquel lugar"], "japanese": "あそこ" },
        { "latin": ["dónde", "en qué lugar"], "japanese": "そこ" },
        { "latin": ["por aquí", "aquí"], "japanese": "こちら" },
        { "latin": ["por ahí", "ahí"], "japanese": "そちら" },
        { "latin": ["por allí", "allí"], "japanese": "あちら" },
        { "latin": ["por dónde", "dónde"], "japanese": "どちら" },
        { "latin": "aula", "japanese": "きょうしつ" },
        { "latin": "comedor", "japanese": "しょくどう" },
        { "latin": "oficina", "japanese": "きむしょ" },
        { "latin": "sala de reuniones", "japanese": "かいぎしつ" },
        { "latin": "recepción", "japanese": "うけつけ" },
        { "latin": ["recepción", "vestíbulo"], "japanese": "ロビー" },
        { "latin": ["habitación", "cuarto"], "japanese": "へや" },
        { "latin": ["baño", "servicio"], "japanese": "トイレ（おてあらい）" },
        { "latin": "escalera", "japanese": "かいだん" },
        { "latin": "ascensor", "japanese": "エレベーター" },
        { "latin": "escalera mecánica", "japanese": "エスカレーター" },
        { "latin": "máquina expendedora", "japanese": "じどうはんばいき" },
        { "latin": ["teléfono", "llamada telefónica"], "japanese": "でんわ" },
        { "latin": ["país", "patria"], "japanese": "［お］くに" },
        { "latin": ["empresa", "compañía", "firma"], "japanese": "かいしゃ" },
        { "latin": "casa", "japanese": "うち、いえ" },
        { "latin": "zapatos", "japanese": "くつ" },
        { "latin": "corbata", "japanese": "ネクタイ" },
        { "latin": "vino", "japanese": "ワイン" },
        { "latin": "sección", "japanese": "うりば" },
        { "latin": "sótano", "japanese": "ちか" },
        { "latin": ["piso", "planta"], "japanese": "ーかい（ーがい）" },
        { "latin": "qué piso", "japanese": "なんがい" },
        { "latin": "yen", "japanese": "ーえん" },
        { "latin": "cuánto", "japanese": "いくら" },
        { "latin": "cien", "japanese": "ひゃく" },
        { "latin": "mil", "japanese": "せん" },
        { "latin": "diez mil", "japanese": "まん" }
    ],


    "lesson4": [
        { "latin": "levantarse", "japanese": "おきます" },
        { "latin": ["acostarse", "ir a la cama"], "japanese": "ねます" },
        { "latin": "trabajar", "japanese": "はたらきませ" },
        { "latin": ["descansar", "estar de vacaciones"], "japanese": "やすみます" },
        { "latin": "estudiar", "japanese": "べんきょします" },
        { "latin": "terminar", "japanese": "おわります" },
        { "latin": "grandes almacenes", "japanese": "デパート" },
        { "latin": "banco", "japanese": "ぎんこう" },
        { "latin": "oficina de correos", "japanese": "ゆうびんきょく" },
        { "latin": "biblioteca", "japanese": "としょかん" },
        { "latin": "museo de arte", "japanese": "びじゅつかん" },
        { "latin": "ahora", "japanese": "いま" },
        { "latin": "hora", "japanese": "ーじ" },
        { "latin": "minutos", "japanese": "ーふん、ーぷん" },
        { "latin": "y media", "japanese": "はん" },
        { "latin": "¿qué hora?", "japanese": "なんじ" },
        { "latin": "¿qué minuto?", "japanese": "なんぷん" },
        { "latin": ["la mañana", "AM"], "japanese": "ごぜん" },
        { "latin": ["la tarde", "PM", "por la tarde"], "japanese": "ごご" },
        { "latin": "por la mañana", "japanese": "あさ" },
        { "latin": ["día", "mediodía"], "japanese": "ひる" },
        { "latin": "noche", "japanese": "ばん、よる" },
        { "latin": "anteayer", "japanese": "おととい" },
        { "latin": "ayer", "japanese": "きのう" },
        { "latin": "hoy", "japanese": "きょう" },
        { "latin": "mañana", "japanese": "あした" },
        { "latin": "pasado mañana", "japanese": "あさって" },
        { "latin": "esta mañana", "japanese": "けさ" },
        { "latin": "esta noche", "japanese": "こんばん" },
        { "latin": ["descanso", "día libre"], "japanese": "やすみ" },
        { "latin": "descanso de mediodía", "japanese": "ひるやすみ" },
        { "latin": "número", "japanese": "ばんごう" },
        { "latin": "qué número", "japanese": "なんばん" },
        { "latin": "examen", "japanese": "しけん" },
        { "latin": "reunión", "japanese": "かいぎ" },
        { "latin": "película", "japanese": "えいが" },
        { "latin": "todas las mañanas", "japanese": "まいあさ" },
        { "latin": "todas las noches", "japanese": "まいばん" },
        { "latin": "todos los días", "japanese": "まいにち" },
        { "latin": "lunes", "japanese": "げつようび" },
        { "latin": "martes", "japanese": "かようび" },
        { "latin": "miércoles", "japanese": "すいようび" },
        { "latin": "jueves", "japanese": "もくようび" },
        { "latin": "viernes", "japanese": "きんようび" },
        { "latin": "sábado", "japanese": "どようび" },
        { "latin": "domingo", "japanese": "にちようび" },
        { "latin": "desde ~", "japanese": "～から" },
        { "latin": "hasta ~", "japanese": "～まで" },
        { "latin": "y", "japanese": "～と～" }
    ],


    "lesson5": [
        { "latin": "ir", "japanese": "いきます" },
        { "latin": "venir", "japanese": "きます" },
        { "latin": "volver, regresar, irse a casa", "japanese": "かえります" },
        { "latin": "escuela", "japanese": "がっこう" },
        { "latin": "supermercado", "japanese": "スーパー" },
        { "latin": "estación", "japanese": "えき" },
        { "latin": "avión", "japanese": "ひこうき" },
        { "latin": "barco", "japanese": "ふね" },
        { "latin": "tren eléctrico", "japanese": "でんしゃ" },
        { "latin": "metro", "japanese": "ちかてつ" },
        { "latin": "shinkansen, tren bala", "japanese": "しんかんせん" },
        { "latin": "autobús", "japanese": "バス" },
        { "latin": "taxi", "japanese": "タクシー" },
        { "latin": "bicicleta", "japanese": "じてんしゃ" },
        { "latin": "a pie, andando", "japanese": "あるいて" },
        { "latin": "persona, gente", "japanese": "ひと" },
        { "latin": "amigo(s)", "japanese": "ともだち" },
        { "latin": "él, novio", "japanese": "かれ" },
        { "latin": "ella, novia", "japanese": "かのじょ" },
        { "latin": "familia", "japanese": "かぞく" },
        { "latin": "solo", "japanese": "ひとりで" },
        { "latin": "la semana pasada", "japanese": "せんしゅう" },
        { "latin": "esta semana", "japanese": "こんしゅう" },
        { "latin": "la semana que viene", "japanese": "らいしゅう" },
        { "latin": "el mes pasado", "japanese": "せんげつ" },
        { "latin": "este mes", "japanese": "こんげつ" },
        { "latin": "el mes que viene", "japanese": "らいげつ" },
        { "latin": "el año pasado", "japanese": "きょねん" },
        { "latin": "este año", "japanese": "ことし" },
        { "latin": "el año que viene", "japanese": "らいねん" },
        { "latin": "año ー", "japanese": "ーねん" },
        { "latin": "qué año", "japanese": "なんねん" },
        { "latin": "mes de", "japanese": "ーげつ" },
        { "latin": "qué mes", "japanese": "なんがつ" },
        { "latin": "el día uno", "japanese": "ついたち" },
        { "latin": "el día dos, 2 días", "japanese": "ふつか" },
        { "latin": "el día cuatro, 4 días", "japanese": "みっか" },
        { "latin": "el día tres, 3 días", "japanese": "よっか" },
        { "latin": "el día seis, 6 días", "japanese": "いつか" },
        { "latin": "el día cinco, 5 días", "japanese": "むいか" },
        { "latin": "el día ocho, 8 días", "japanese": "なのか" },
        { "latin": "el día siete, 7 días", "japanese": "ようか" },
        { "latin": "el día diez, 10 días", "japanese": "ここのか" },
        { "latin": "el día nueve, 9 días", "japanese": "とおか" },
        { "latin": "el día veinte, 20 días", "japanese": "じゅうよっか" },
        { "latin": "el día catorce, 14 días", "japanese": "はつか" },
        { "latin": "díaー, ーdía(s)", "japanese": "にじゅうよっか" },
        { "latin": "el día veinticuatro, 24 días", "japanese": "ーにち" },
        { "latin": "cuándo", "japanese": "なんいち" },
        { "latin": "qué día del mes, cuántos días", "japanese": "いつ" },
        { "latin": "a ningún sitio", "japanese": "たんじょうび" },
        { "latin": "cumpleaños", "japanese": "どこ「へ」も（いきませんでした" },
        { "latin": "hacer solo", "japanese": "一で verb + します" }
    ],


    "lesson6": [
        { "latin": "comer", "japanese": "たべます" },
        { "latin": ["beber", "tomar"], "japanese": "のみます" },
        { "latin": "fumar", "japanese": "すいます" },
        { "latin": ["ver", "mirar"], "japanese": "みます" },
        { "latin": ["oír", "escuchar"], "japanese": "ききます" },
        { "latin": "leer", "japanese": "よみます" },
        { "latin": ["escribir", "dibujar"], "japanese": "かきます" },
        { "latin": "comprar", "japanese": "かいます" },
        { "latin": "sacar fotos", "japanese": "しゃしんをとります" },
        { "latin": "hacer", "japanese": "します" },
        { "latin": ["ver a", "encontrarse con"], "japanese": "あります" },
        { "latin": ["comida", "arroz cocido"], "japanese": "ごはん" },
        { "latin": "desayuno", "japanese": "あさごはん" },
        { "latin": ["almuerzo", "comida"], "japanese": "ひるごはん" },
        { "latin": "cena", "japanese": "ばんごはん" },
        { "latin": "pan", "japanese": "パン" },
        { "latin": "huevo", "japanese": "たまご" },
        { "latin": "carne", "japanese": "にく" },
        { "latin": ["pescado", "pez"], "japanese": "さかな" },
        { "latin": "verduras", "japanese": "やさい" },
        { "latin": "frutas", "japanese": "くだもの" },
        { "latin": "agua", "japanese": "みず" },
        { "latin": ["té", "té verde"], "japanese": "おちゃ" },
        { "latin": ["té negro", "té inglés"], "japanese": "こちゃ" },
        { "latin": "leche", "japanese": ["ぎゅうにゅう", "ミルク"] },
        { "latin": ["zumo", "refresco"], "japanese": "ジューズ" },
        { "latin": "cerveza", "japanese": "ビール" },
        { "latin": ["bebida alcohólica", "sake"], "japanese": "さけ" },
        { "latin": ["cigarrillo", "tabaco"], "japanese": "たばこ" },
        { "latin": ["carta", "correspondencia"], "japanese": "てがみ" },
        { "latin": ["informe", "reporte"], "japanese": "レポート" },
        { "latin": "fotografía", "japanese": "しゃしん" },
        { "latin": "video", "japanese": "ビデオ" },
        { "latin": ["tienda", "negocio"], "japanese": "みせ" },
        { "latin": "jardín", "japanese": "にわ" },
        { "latin": ["deberes", "tarea"], "japanese": "しゅくだい" },
        { "latin": "tenis", "japanese": "テニス" },
        { "latin": "fútbol", "japanese": "サッカー" },
        { "latin": "ver cerezos en flor", "japanese": "はなみ" },
        { "latin": "qué", "japanese": "なに" },
        { "latin": ["junto", "juntos"], "japanese": "いっしょに" },
        { "latin": "un poco", "japanese": "ちょっと" },
        { "latin": ["siempre", "normalmente"], "japanese": "いつも" },
        { "latin": ["de vez en cuando", "a veces"], "japanese": "ときどき" },
        { "latin": ["y luego", "y después"], "japanese": "それから" },
        { "latin": "sí", "japanese": "ええ" },
        { "latin": "es buena idea", "japanese": "いいですね" },
        { "latin": ["entendido", "muy bien"], "japanese": "わかりました" }
    ],


    "lesson7": [
        { "latin": "cortar", "japanese": "きります" },
        { "latin": "enviar", "japanese": "おくります" },
        { "latin": "dar", "japanese": "あげます" },
        { "latin": "recibir", "japanese": "もらいます" },
        { "latin": "prestar", "japanese": "かします" },
        { "latin": "tomar prestado", "japanese": "かります" },
        { "latin": "enseñar", "japanese": "おしえます" },
        { "latin": "aprender", "japanese": "ならいます" },
        { "latin": "hacer una llamada", "japanese": "でんわをかけます" },
        { "latin": "mano", "japanese": "て" },
        { "latin": "palillos", "japanese": "はし" },
        { "latin": "cuchara", "japanese": "スプーン" },
        { "latin": "cuchillo", "japanese": "ナイフ" },
        { "latin": "tenedor", "japanese": "フォーク" },
        { "latin": "tijeras", "japanese": "はさみ" },
        { "latin": "ordenador", "japanese": "パソコン" },
        { "latin": "teléfono móvil", "japanese": "ケータイ" },
        { "latin": ["email", "correo electrónico"], "japanese": "メール" },
        { "latin": "tarjeta de año nuevo", "japanese": "ねんがじょう" },
        { "latin": "perforadora", "japanese": "パンチ" },
        { "latin": "grapadora", "japanese": "ホッチキス" },
        { "latin": "cinta adhesiva", "japanese": "セロテープ" },
        { "latin": "goma de borrar", "japanese": "けしゴム" },
        { "latin": "papel", "japanese": "かみ" },
        { "latin": "flor", "japanese": "はな" },
        { "latin": "camisa", "japanese": "シャツ" },
        { "latin": "regalo", "japanese": "プレセント" },
        { "latin": ["equipaje", "paquete"], "japanese": "にもつ" },
        { "latin": "dinero", "japanese": "おかね" },
        { "latin": "billete", "japanese": "きっぷ" },
        { "latin": "Navidad", "japanese": "クリスマス" },
        { "latin": "mi padre", "japanese": "ちち" },
        { "latin": "mi madre", "japanese": "はは" },
        { "latin": "padre", "japanese": "おとうさん" },
        { "latin": "madre", "japanese": "おかあさん" },
        { "latin": "ya", "japanese": "もう" },
        { "latin": "todavía", "japanese": "まだ" },
        { "latin": ["desde ahora", "dentro de poco"], "japanese": "これから" }
    ],


    "lesson8": [
        { "latin": "guapo", "japanese": "ハンサム「な」" },
        { "latin": ["hermoso", "limpio"], "japanese": "きれい「な」" },
        { "latin": "silencioso", "japanese": "しずか「な」" },
        { "latin": ["concurrido", "animado"], "japanese": "にぎやか「な」" },
        { "latin": ["famoso", "célebre"], "japanese": "ゆうめい「な」" },
        { "latin": ["amable", "generoso"], "japanese": "しんせつ「な」" },
        { "latin": ["sano", "con ánimo"], "japanese": "げんき「な」" },
        { "latin": "estar libre", "japanese": "ひま「な」" },
        { "latin": ["útil", "práctico", "conveniente"], "japanese": "べんり「な」" },
        { "latin": ["bonito", "precioso"], "japanese": "すてき「な」" },
        { "latin": "grande", "japanese": "おおきい" },
        { "latin": "pequeño", "japanese": "ちいさい" },
        { "latin": "nuevo", "japanese": "あたらしい" },
        { "latin": ["antiguo", "viejo"], "japanese": "ふるい" },
        { "latin": "bueno", "japanese": ["いい", "よい"] },
        { "latin": "malo", "japanese": "わるい" },
        { "latin": ["caluroso", "caliente"], "japanese": "あつい" },
        { "latin": "frío", "japanese": "さむい" },
        { "latin": "frío", "japanese": "つめたい" },
        { "latin": "difícil", "japanese": "むずかしい" },
        { "latin": ["fácil", "amable"], "japanese": "やさしい" },
        { "latin": "fácil", "japanese": "かんたん「な」" },
        { "latin": ["caro", "alto"], "japanese": "たかい" },
        { "latin": "barato", "japanese": "やすい" },
        { "latin": "bajo", "japanese": "ひくい" },
        { "latin": ["interesante", "gracioso"], "japanese": "おもしろい" },
        { "latin": ["delicioso", "sabroso", "rico"], "japanese": "おいしい" },
        { "latin": ["atareado", "ocupado"], "japanese": "おそがしい" },
        { "latin": ["divertido", "placentero"], "japanese": "たのしい" },
        { "latin": "blanco", "japanese": "しろい" },
        { "latin": "negro", "japanese": "くろい" },
        { "latin": "rojo", "japanese": "あかい" },
        { "latin": "azul", "japanese": "あおい" },
        { "latin": ["árbol de cerezo", "flor de cerezo"], "japanese": "さくら" },
        { "latin": "montaña", "japanese": "やま" },
        { "latin": ["población", "ciudad"], "japanese": "まち" },
        { "latin": ["comida", "alimentos"], "japanese": "たべもの" },
        { "latin": "lugar", "japanese": "ところ" },
        { "latin": ["residencia", "dormitorios"], "japanese": "りょう" },
        { "latin": "restaurante", "japanese": "レストラン" },
        { "latin": "vida diaria", "japanese": "せいかつ" },
        { "latin": ["trabajo", "profesión"], "japanese": "「お」しごと" },
        { "latin": "cómo", "japanese": "どう" },
        { "latin": "qué clase de", "japanese": "どんな" },
        { "latin": ["muy", "mucho"], "japanese": "とても" },
        { "latin": ["no muy", "no mucho"], "japanese": "あまり" },
        { "latin": "y", "japanese": "そして" },
        { "latin": "pero", "japanese": "～が、～" }
    ],


    "lesson9": [
        { "latin": ["entender", "comprender"], "japanese": "わかります" },
        { "latin": ["haber", "estar", "existir"], "japanese": "あります" },
        { "latin": "gustar", "japanese": "すき" },
        { "latin": ["odiar", "detestar"], "japanese": "きらい" },
        { "latin": ["ser bueno", "ser hábil"], "japanese": "じょうず" },
        { "latin": ["ser malo", "ser inhábil"], "japanese": "へた" },
        { "latin": "bebida", "japanese": "のみもの" },
        { "latin": ["cocina", "plato"], "japanese": "りょうり" },
        { "latin": "deporte", "japanese": "スポーツ" },
        { "latin": "béisbol", "japanese": "やきゅう" },
        { "latin": "baile", "japanese": "ダンス" },
        { "latin": "viaje", "japanese": "りょこう" },
        { "latin": "música", "japanese": "おんがく" },
        { "latin": "canción", "japanese": "うた" },
        { "latin": "música clásica", "japanese": "クラシック" },
        { "latin": "jazz", "japanese": "ジャズ" },
        { "latin": "concierto", "japanese": "コンサート" },
        { "latin": "día laboral", "japanese": "へいじつ" },
        { "latin": "día festivo", "japanese": "きゅくじつ" },
        { "latin": "día", "japanese": "じつ" },
        { "latin": "karaoke", "japanese": "カラオケ" },
        { "latin": "kabuki", "japanese": "かぶき" },
        { "latin": ["pintura", "dibujo", "cuadro"], "japanese": "え" },
        { "latin": "letra", "japanese": "じ" },
        { "latin": "caracteres chinos", "japanese": "かんじ" },
        { "latin": "hiragana", "japanese": "ひらがな" },
        { "latin": "katakana", "japanese": "カタカナ" },
        { "latin": "alfabeto latino", "japanese": "ローマじ" },
        { "latin": ["dinero suelto", "en monedas"], "japanese": "こまかいおかね" },
        { "latin": "detallista", "japanese": "こまかい" },
        { "latin": "entrada", "japanese": "チケット" },
        { "latin": "tiempo", "japanese": "じかん" },
        { "latin": "algo que hacer", "japanese": "ようじ" },
        { "latin": ["cita", "compromiso", "promesa"], "japanese": "やくそく" },
        { "latin": ["trabajo temporal", "trabajo eventual"], "japanese": "アルバイト" },
        { "latin": "todo", "japanese": "ぜんぶ" },
        { "latin": "crear", "japanese": "つくります" },
        { "latin": ["su marido", "tu marido"], "japanese": "ごしゅじん" },
        { "latin": ["mi marido", "mi esposo"], "japanese": ["おっと", "しゅじん"] },
        { "latin": ["su esposa", "tu esposa"], "japanese": "おくさん" },
        { "latin": "mi esposa", "japanese": ["つま", "かない"] },
        { "latin": ["niño", "mi hijo"], "japanese": "こども" },
        { "latin": ["bien", "mucho"], "japanese": "よく" },
        { "latin": ["más o menos", "aproximadamente"], "japanese": "だいたい" },
        { "latin": "mucho", "japanese": "たくさん" },
        { "latin": ["poco", "un poco"], "japanese": "すこし" },
        { "latin": "nada", "japanese": "ぜんぜん" },
        { "latin": ["temprano", "rápido"], "japanese": "はやく" },
        { "latin": "porque", "japanese": "～から" },
        { "latin": "por qué", "japanese": "どうして" },
        { "latin": "sano", "japanese": "けんこう" },
        { "latin": "flexible", "japanese": "フレキシブル" },
        { "latin": "dolor", "japanese": "いたい" },
        { "latin": "cabeza", "japanese": "あたま" },
        { "latin": "querer", "japanese": "したい" },
        { "latin": ["guapo", "guay"], "japanese": "かっこいい" }
    ],


    "lesson10": [
        { "latin": ["estar", "haber", "existir"], "japanese": "あります" },
        { "latin": ["estar", "haber", "existir"], "japanese": "います" },
        { "latin": "diversos", "japanese": "いろいろ「な」" },
        { "latin": "hombre", "japanese": "おとこのひと" },
        { "latin": "mujer", "japanese": "おんなのひと" },
        { "latin": "niño", "japanese": "おとこのこ" },
        { "latin": "niña", "japanese": "おんなのこ" },
        { "latin": "perro", "japanese": "いぬ" },
        { "latin": "perrito", "japanese": "こいぬ" },
        { "latin": "gato", "japanese": "ねこ" },
        { "latin": "gatito", "japanese": "こねこ" },
        { "latin": "panda", "japanese": "パンダ" },
        { "latin": "elefante", "japanese": "ぞう" },
        { "latin": "caballo", "japanese": "うま" },
        { "latin": ["árbol", "madera"], "japanese": "き" },
        { "latin": ["cosa", "objeto"], "japanese": "もの" },
        { "latin": ["pila", "batería"], "japanese": "でんち" },
        { "latin": "caja", "japanese": "はこ" },
        { "latin": "cajón", "japanese": "ひきだし" },
        { "latin": "interruptor", "japanese": "スイッチ" },
        { "latin": ["refrigerador", "nevera"], "japanese": "れいぞうこ" },
        { "latin": "congelador", "japanese": "れいとうこ" },
        { "latin": "taza", "japanese": "マグカップ" },
        { "latin": "vaso", "japanese": "コップ" },
        { "latin": "mesa", "japanese": "テーブル" },
        { "latin": "cama", "japanese": "ベッド" },
        { "latin": "estante", "japanese": "たな" },
        { "latin": "puerta", "japanese": "ドア" },
        { "latin": "ventana", "japanese": "まど" },
        { "latin": "buzón", "japanese": "ポスト" },
        { "latin": "construir", "japanese": "たてます" },
        { "latin": "edificio de oficinas", "japanese": "ビル" },
        { "latin": "edificio", "japanese": "たてもの" },
        { "latin": ["ATM", "cajero automático"], "japanese": "ATM" },
        { "latin": ["tienda de conveniencia", "tienda de 24 horas"], "japanese": "コンビニ" },
        { "latin": "parque", "japanese": "こうえん" },
        { "latin": "cafetería", "japanese": "きっさてん" },
        { "latin": "tienda de", "japanese": "～や" },
        { "latin": "parada", "japanese": "のりば" },
        { "latin": "provincia", "japanese": "けん" },
        { "latin": ["encima", "arriba"], "japanese": "うえ" },
        { "latin": ["debajo", "abajo"], "japanese": "した" },
        { "latin": ["delante", "adelante", "en frente"], "japanese": "まえ" },
        { "latin": ["montar", "subir"], "japanese": "のります" },
        { "latin": "aire acondicionado", "japanese": "エアコン" },
        { "latin": ["detrás", "atrás"], "japanese": "うしろ" },
        { "latin": "derecha", "japanese": "みぎ" },
        { "latin": "izquierda", "japanese": "ひだり" },
        { "latin": "dentro", "japanese": "なか" },
        { "latin": "fuera", "japanese": "そと" },
        { "latin": "al lado", "japanese": ["となり", "よこ"] },
        { "latin": "cerca", "japanese": "ちかく" },
        { "latin": "lejos", "japanese": "とおく" },
        { "latin": "entre", "japanese": "あいだ" },
        { "latin": "y entre otros", "japanese": "～や ～「など」" },
        { "latin": "banco", "japanese": "ベンチ" },
        { "latin": "camión", "japanese": "トラック" },
        { "latin": "animal", "japanese": "どうぶつ" },
        { "latin": "zoo", "japanese": "どうぶつえん" },
        { "latin": "zona al aire libre", "japanese": "えん" },
        { "latin": "chanclas", "japanese": "ビーチサンダル" },
        { "latin": "sandalias", "japanese": "サンダル" },
        { "latin": ["barrio", "distrito"], "japanese": "ちいき" },
        { "latin": "pasear", "japanese": "さんぽ「を」します" },
        { "latin": "línea de transporte público", "japanese": "せん" },
        { "latin": "plaza", "japanese": "ひろば" },
        { "latin": ["sección", "esquina"], "japanese": "コーナー" },
        { "latin": "centro", "japanese": "まんなか" },
        { "latin": "al fondo", "japanese": "おく" },
        { "latin": "despertar", "japanese": "めぎまし" },
        { "latin": "reloj despertador", "japanese": "めぎましどけい" },
        { "latin": "brazo", "japanese": "うで" },
        { "latin": "reloj de muñeca", "japanese": "うでどけい" },
        { "latin": "estadio", "japanese": "スタジアム" },
        { "latin": "estadio", "japanese": "ドーム" },
        { "latin": "padres", "japanese": "りょうしん" },
        { "latin": "juego de mesa", "japanese": "ポードゲーム" }
    ],


    "lesson11": [
        { "latin": "tener hijos", "japanese": "「こどもが」います" },
        { "latin": ["estar", "permanecer"], "japanese": "います" },
        { "latin": ["tardar", "costar"], "japanese": "かかります" },
        { "latin": ["ausentarse", "faltar"], "japanese": "やすみます" },
        { "latin": ["cuántos", "cuántas"], "japanese": "いくら" },
        { "latin": "una persona", "japanese": "ひとり" },
        { "latin": "dos personas", "japanese": "ふたり" },

        { "latin": "objetos", "japanese": "ーつ" },
        { "latin": "personas", "japanese": "ーにん" },
        { "latin": "orden", "japanese": "ーばん" },
        { "latin": ["objetos finos y planos", "objetos planos y finos"], "japanese": "ーまい" },
        { "latin": ["máquinas", "vehículos"], "japanese": "ーだい" },
        { "latin": "edad", "japanese": "ーさい" },
        { "latin": ["libros", "cuadernos"], "japanese": "ーさつ" },
        { "latin": "ropas", "japanese": "ーちゃく" },
        { "latin": "frecuencia", "japanese": "ーかい" },
        { "latin": "objetos pequeños", "japanese": "ーこ" },
        { "latin": ["calzados", "calcetines"], "japanese": ["ーそく","ーぞく"] },
        { "latin": "viviendas", "japanese": ["ーけん","ーげん"] },
        { "latin": ["pisos", "plantas"], "japanese": ["ーかい","ーがい"] },
        { "latin": ["objetos delgados y largos", "objetos largos y delgados"], "japanese": ["ーほん","ーぼん", "ーぽん"] },
        { "latin": ["bebidas", "vasos", "copas", "tazas"], "japanese": ["ーはい","ーばい", "ーぱい"] },
        { "latin": ["animales pequeños", "peces", "insectos"], "japanese": ["ーひき","ーびき", "ーぴき"] },
        
        { "latin": "manzana", "japanese": "りんご" },
        { "latin": "mandarina", "japanese": "みかん" },
        { "latin": "sándwich", "japanese": "サンドイッチ" },
        { "latin": "curry con arroz", "japanese": "カレーライス" },
        { "latin": "helado", "japanese": "アイスクリーム" },
        { "latin": "sello postal", "japanese": "きって" },
        { "latin": "tarjeta postal", "japanese": "はがき" },
        { "latin": "sobre", "japanese": "ふうとう" },
        { "latin": "padres", "japanese": "りょうしん" },
        { "latin": "hermanas", "japanese": "しまい" },
        { "latin": "hermanos", "japanese": "きょうだい" },
        { "latin": "mi hermano mayor", "japanese": "あに" },
        { "latin": "hermano mayor", "japanese": "おにいさん" },
        { "latin": "mi hermana mayor", "japanese": "あね" },
        { "latin": "hermana mayor", "japanese": "おねえさん" },
        { "latin": "hermano pequeño", "japanese": "あとうと" },
        { "latin": "hermana pequeña", "japanese": "いもうと" },
        { "latin": "país extranjero", "japanese": "がいこく" },
        { "latin": "extranjero", "japanese": "がいこくじん" },
        { "latin": "estudiante extranjero", "japanese": "りゅうがくせい" },
        { "latin": "clase", "japanese": "クラス" },
        { "latin": "horas", "japanese": "ーじかん" },
        { "latin": "semanas", "japanese": "ーしゅうかん" },
        { "latin": "meses", "japanese": "ーかげつ" },
        { "latin": "años", "japanese": "ーねん" },
        { "latin": "alrededor de", "japanese": "～ぐらい" },
        { "latin": ["cuánto tiempo", "cuánta cantidad"], "japanese": "どのくらい" },
        { "latin": "en total", "japanese": "ぜんぶで" },
        { "latin": "todos", "japanese": "みんな" },
        { "latin": "solo", "japanese": "～だけ" },
        { "latin": "descansar", "japanese": "きゅうけいします" },
        { "latin": "descanso", "japanese": "きゅうけい" },
        { "latin": "patinar", "japanese": "スケートボード" }
    ],


    "lesson12": [
        { "latin": ["fácil", "sencillo"], "japanese": "かんたん「な」" },
        { "latin": "cercano", "japanese": "ちかい" },
        { "latin": ["distante", "lejano"], "japanese": "とおい" },
        { "latin": ["rápido", "temprano"], "japanese": "はやい" },
        { "latin": ["tarde", "lento", "despacio"], "japanese": "おそい" },
        { "latin": ["mucha", "muchos", "mucho"], "japanese": "「ひとが」おおい" },
        { "latin": ["poca", "un poco", "escaso"], "japanese": "「ひとが」すくない" },
        { "latin": ["cálido", "templado"], "japanese": "あたたかい" },
        { "latin": "fresco", "japanese": "すずしい" },
        { "latin": "dulce", "japanese": "あまい" },
        { "latin": "picante", "japanese": "からい" },
        { "latin": "pesado", "japanese": "おもい" },
        { "latin": "ligero", "japanese": "かるい" },
        { "latin": "preferir", "japanese": "「コーヒーが」いい" },
        { "latin": ["estación", "temporada"], "japanese": "きせつ" },
        { "latin": "primavera", "japanese": "はる" },
        { "latin": "verano", "japanese": "なつ" },
        { "latin": "otoño", "japanese": "あき" },
        { "latin": "invierno", "japanese": "ふゆ" },
        { "latin": ["tiempo", "clima"], "japanese": "てんき" },
        { "latin": "lluvia", "japanese": "あめ" },
        { "latin": "nieve", "japanese": "ゆき" },
        { "latin": "nublado", "japanese": "くもり" },
        { "latin": "soleado", "japanese": "はれ" },
        { "latin": "hotel", "japanese": "ホテル" },
        { "latin": "aeropuerto", "japanese": "くうごう" },
        { "latin": ["mar", "océano"], "japanese": "うみ" },
        { "latin": "mundo", "japanese": "せかい" },
        { "latin": "fiesta", "japanese": "パーティー" },
        { "latin": ["festival", "feria"], "japanese": "「お」まつり" },
        { "latin": "estofado de ternera y verduras", "japanese": "すきやき" },
        { "latin": "sashimi", "japanese": "さしみ" },
        { "latin": "sushi", "japanese": "「お」すし" },
        { "latin": "tempura", "japanese": "てんぷら" },
        { "latin": "carne de cerdo", "japanese": "ぶたにく" },
        { "latin": "carne de pollo", "japanese": "とりにく" },
        { "latin": "carne de vaca", "japanese": "ぎゅうにく" },
        { "latin": "limón", "japanese": "レモン" },
        { "latin": "arreglo floral", "japanese": "いけばな" },
        { "latin": ["arce", "hojas coloradas de otoño"], "japanese": "もみじ" },
        { "latin": "cúal", "japanese": "どちら" },
        { "latin": "ambos", "japanese": "どちらも" },
        { "latin": ["el más", "el primero"], "japanese": "いちばん" },
        { "latin": ["mucho más", "continuamente", "sin parar"], "japanese": "ずっと" },
        { "latin": "por primera vez", "japanese": "はじめて" },

        { "latin": "aburrido", "japanese": "つまらない" },
        { "latin": "normal", "japanese": "ふつう「な」" },
        { "latin": "espinacas", "japanese": "ほうれんそう" },
        { "latin": "huevo frito", "japanese": "めだまやき" },
        { "latin": "cuando tenía", "japanese": "～のとき" },
        { "latin": ["buen tiempo", "buen clima"], "japanese": "いいてんき" },
        { "latin": "más", "japanese": "より" },
        { "latin": "más", "japanese": "ほう" },
        { "latin": "igual", "japanese": "おなじ" },
        { "latin": "meterse", "japanese": "いれます" },
        { "latin": "vivir solo", "japanese": "ひとりぐらし" },
        { "latin": "patinete eléctrico", "japanese": "スクーター" },
        { "latin": "salmón crudo", "japanese": "サーモン" },
        { "latin": "salmón cocinado", "japanese": "さけ" },
        { "latin": "atún", "japanese": "まぐる" },
        { "latin": "atún enlatado", "japanese": "ツナ" },
        { "latin": "cansado", "japanese": "つかれ" },
        { "latin": "encuesta", "japanese": "アンケート" },
        { "latin": "hacer encuesta", "japanese": "アンケートします" },
        { "latin": "primos", "japanese": "いとこ" },
        { "latin": "votar", "japanese": "とうびょうします" },
        { "latin": "elecciones", "japanese": "せんきょ" },
        { "latin": "recomendar", "japanese": "おすすめ「な」" },
        { "latin": ["mejórate", "espero que te mejores"], "japanese": "おだいじに" },
        { "latin": "vacaciones", "japanese": "きゅうじつ" }
    ],


    "lesson13": [
        { "latin": ["jugar", "divertirse"], "japanese": "あそびます" },
        { "latin": "nadar", "japanese": "およぎます" },
        { "latin": ["recoger", "recibir"], "japanese": "むかえます" },
        { "latin": "cansarse", "japanese": "つかれます" },
        { "latin": "estar cansado", "japanese": "つかれました" },
        { "latin": "casarse", "japanese": "けっこんします" },
        { "latin": "hacer compras", "japanese": "かいものします" },
        { "latin": "comer", "japanese": "しょくじします" },
        { "latin": "pasear", "japanese": "「こうえんを」さんぽします" },
        { "latin": ["duro", "terrible"], "japanese": "たいへん「な」" },
        { "latin": "querer", "japanese": "ほしい" },
        { "latin": ["amplio", "espacioso"], "japanese": "ひるい" },
        { "latin": ["pequeño", "angosto", "estrecho"], "japanese": "せまい" },
        { "latin": "piscina", "japanese": "プール" },
        { "latin": "río", "japanese": "かわ" },
        { "latin": "bellas artes", "japanese": "びじゅつ" },
        { "latin": "pesca", "japanese": "つり" },
        { "latin": "pescar", "japanese": "つりをします" },
        { "latin": "esquí", "japanese": "スキー" },
        { "latin": "esquiar", "japanese": "スキーをします" },
        { "latin": "fin de semana", "japanese": "しゅうまつ" },
        { "latin": "año nuevo", "japanese": "「お」しょうがつ" },
        { "latin": "hacia", "japanese": "～ごろ" },
        { "latin": "algo", "japanese": "なにか" },
        { "latin": "algún lugar", "japanese": "どこか" },
        { "latin": "tener sed", "japanese": "のどがかわきました" },
        { "latin": "tener hambre", "japanese": "おなかがすきました" },
        { "latin": "garganta", "japanese": "のど" },
        { "latin": "secar", "japanese": "かわきます" },
        { "latin": "estómago", "japanese": "おなか" },
        { "latin": "estar vacío", "japanese": "すきます" },
        { "latin": "alguien", "japanese": "だれか" },
        { "latin": "algún momento", "japanese": "いつか" },
        { "latin": "matrimonio", "japanese": "けっこん" },
        { "latin": "boda", "japanese": "けっこんしき" },
        { "latin": "siguiente", "japanese": "つぎ" },
        { "latin": "estar lleno", "japanese": "いっぱいです" },
        { "latin": "mucho", "japanese": "いっぱい「たくさん」" },
        { "latin": "recoger", "japanese": "うけとります" },
        { "latin": "pagar", "japanese": "はらいます" },
        { "latin": "esperar", "japanese": "まちます" },
        { "latin": "economía", "japanese": "けいざい" },
        { "latin": "entrar", "japanese": "はいります「に」" },
        { "latin": "salir", "japanese": "でます「を」" },
    ],


    "lesson14": [
        { "latin": "encender", "japanese": "つけます" },
        { "latin": "apagar", "japanese": "けします" },
        { "latin": "abrir", "japanese": "あけます" },
        { "latin": "cerrar", "japanese": "しめます" },
        { "latin": ["apresurarse", "darse prisa"], "japanese": "いそぎます" },
        { "latin": "esperar", "japanese": "まちます" },
        { "latin": ["tener algo en la mano", "tomar"], "japanese": "もちます" },
        { "latin": ["pasar", "dar"], "japanese": "とります" },
        { "latin": "ayudar", "japanese": "てつだいます" },
        { "latin": "llamar", "japanese": "よびます" },
        { "latin": "hablar", "japanese": "はなします" },
        { "latin": "usar", "japanese": "つかいます" },
        { "latin": ["parar", "estacionar"], "japanese": "とめます" },
        { "latin": ["mostrar", "enseñar"], "japanese": "みせます" },
        { "latin": ["enseñar, dar"], "japanese": "［じゅうしょを］おしえます" },
        { "latin": "sentarse", "japanese": "すわります" },
        { "latin": "ponerse de pie", "japanese": "たちます" },
        { "latin": "entrar", "japanese": "［きっさてんに］はいります" },
        { "latin": "salir", "japanese": "［きっさてんを］でます" },
        { "latin": "llover", "japanese": "［あめが］ふります" },
        { "latin": "sacar fotocopias", "japanese": "コピーします" },
        { "latin": ["electricidad", "luz"], "japanese": "でんき" },
        { "latin": "aire acondicionado", "japanese": "エアコン" },
        { "latin": "pasaporte", "japanese": "パスポート" },
        { "latin": "nombre", "japanese": "なまえ" },
        { "latin": ["dirección, domicilio"], "japanese": "じゅうしょ" },
        { "latin": ["mapa", "plano"], "japanese": "ちず" },
        { "latin": "sal", "japanese": "しお" },
        { "latin": "azúcar", "japanese": "さとう" },
        { "latin": ["pregunta", "problema"], "japanese": "もんだい" },
        { "latin": "respuesta", "japanese": "こたえ" },
        { "latin": ["cómo leer", "modo de lectura"], "japanese": "よみかた" },
        { "latin": ["cómo", "modo de", "manera de"], "japanese": "～かた" },
        { "latin": ["derecho", "recto"], "japanese": "まっすぐ" },
        { "latin": "despacio", "japanese": "ゆっくり" },
        { "latin": "inmediatamente", "japanese": "すぐ" },
        { "latin": "de nuevo", "japanese": "また" },
        { "latin": ["después", "más tarde"], "japanese": "あとで" },
        { "latin": "un poco más", "japanese": "もうすこし" },
        { "latin": ["más", "otro"], "japanese": "もう" },
        { "latin": "vamos", "japanese": "さあ" },
        { "latin": ["¿Cómo?", "¿Eh?"], "japanese": "あれ？" },
        { "latin": "mudanza", "japanese": "ひっこし" },
        { "latin": "explicar", "japanese": "せつめいします" },
        { "latin": "sacar", "japanese": "だします" },
        { "latin": "solo", "japanese": "だけ" },
        { "latin": "girar", "japanese": "まわります" },
        { "latin": "recoger a alguien", "japanese": "むかえます" },
        { "latin": "montar", "japanese": "のります" },
        { "latin": "reservar", "japanese": "よやくします" },
        { "latin": "jefe de departamento", "japanese": "ぶちょう" },
        { "latin": "jefe", "japanese": "かちょう" },
        { "latin": "materiales", "japanese": "しりょう" },
        { "latin": "conductor", "japanese": "うんてんしゅ" },
        { "latin": "semáforo", "japanese": "しんごう" },
        { "latin": "lavar", "japanese": "あらいます" },
        { "latin": "tejado", "japanese": "やね" },
        { "latin": "calle", "japanese": "みち" },
        { "latin": "correa", "japanese": "リード" },
        { "latin": "sin", "japanese": "なし" },
        { "latin": "sopa de cerdo", "japanese": ["ぶたじる", "とんじる"] },
        { "latin": "estofado", "japanese": "ツチュー" }
    ],


    "lesson15": [
        { "latin": ["poner", "colocar"], "japanese": "おきます" },
        { "latin": ["hacer", "producir"], "japanese": "つくります" },
        { "latin": "vender", "japanese": "うります" },
        { "latin": ["enterarse", "saber", "conocer"], "japanese": "しります" },
        { "latin": ["vivir", "residir"], "japanese": "すみます" },
        { "latin": "investigar", "japanese": "けんきゅうします" },
        { "latin": ["recordar", "acordarse"], "japanese": "おもいだします" },
        { "latin": ["materiales", "datos"], "japanese": "しりょう" },
        { "latin": "catálogo", "japanese": "カタログ" },
        { "latin": "horario", "japanese": "じこくひょう" },
        { "latin": "ropa", "japanese": "ふく" },
        { "latin": "productos", "japanese": "せいひん" },
        { "latin": "software", "japanese": "ソフト" },
        { "latin": "diccionario electrónico", "japanese": "でんしじしょ" },
        { "latin": "economía", "japanese": "けいざい" },
        { "latin": "ayuntamiento", "japanese": "しやくしょ" },
        { "latin": ["bachillerato", "escuela secundaria superior"], "japanese": "こうこう" },
        { "latin": ["dentista", "clínical dental"], "japanese": "はいしゃ" },
        { "latin": "soltero", "japanese": "どくしん" },
        { "latin": ["perdón", "lo siento"], "japanese": "すみません" },
        { "latin": ["señoras y señores", "ustedes"], "japanese": "みなさん" },
        { "latin": "casarse", "japanese": "けっこんします" },
        { "latin": "cosas", "japanese": "せいひん" },
        { "latin": "usar", "japanese": "つかいます" },
        { "latin": "biología", "japanese": "せいぶつがく" },
        { "latin": ["pueblo", "campo"], "japanese": "いなか" },
        { "latin": "capital", "japanese": "しゅと" },
        { "latin": "cambio de divisa", "japanese": ["りょうがえ", "かわせ"] },
        { "latin": ["jubilado", "renunciar"], "japanese": "たいしょくします" },
        { "latin": "vehículo", "japanese": "じどうしゃ" }
    ],


    "lesson16": [
        { "latin": "subir", "japanese": "「でんしゃに」のります" },
        { "latin": "bajar", "japanese": "「でんしゃお」おります" },
        { "latin": ["trasbordo", "transbordo"], "japanese": "のりかえます" },
        { "latin": "ducharse", "japanese": "「シャワーお」あびます" },
        { "latin": ["meter", "introducir", "insertar"], "japanese": "いれます" },
        { "latin": ["sacar", "entregar", "presentar", "enviar"], "japanese": "だします" },
        { "latin": ["retirar", "sacar"], "japanese": "「おかねお」おろします" },
        { "latin": ["entrar", "ingresar"], "japanese": "「だいがくに」はいります" },
        { "latin": "graduarse", "japanese": "「だいがくお」でます" },
        { "latin": ["presionar", "empujar", "pulsar"], "japanese": "おします" },
        { "latin": "beber alcohol", "japanese": "のみます" },
        { "latin": ["empezar", "comenzar", "iniciar"], "japanese": "はじめます" },
        { "latin": "visitar", "japanese": "けんがくします" },
        { "latin": ["llamar por teléfono", "telefonear"], "japanese": "でんわします" },
        { "latin": "joven", "japanese": "わかい" },
        { "latin": "largo", "japanese": "ながい" },
        { "latin": "corto", "japanese": "みじかい" },
        { "latin": ["claro", "luminoso"], "japanese": "あかるい" },
        { "latin": "oscuro", "japanese": "くらい" },
        { "latin": "cuerpo", "japanese": "からだ" },
        { "latin": ["cabeza", "cerebro"], "japanese": "あたま" },
        { "latin": "cabello", "japanese": "かみ" },
        { "latin": "cara", "japanese": "かお" },
        { "latin": ["ojo", "ojos"], "japanese": "め" },
        { "latin": ["oreja", "orejas"], "japanese": "みみ" },
        { "latin": "nariz", "japanese": "はな" },
        { "latin": "boca", "japanese": "くち" },
        { "latin": ["diente", "dientes"], "japanese": "は" },
        { "latin": ["pierna", "piernas", "pie", "pies"], "japanese": "あし" },
        { "latin": "estómago", "japanese": "おなか" },
        { "latin": ["altura", "estatura"], "japanese": "せ" },
        { "latin": "servicio", "japanese": "サービス" },
        { "latin": "jogging", "japanese": "ジョギング" },
        { "latin": "ducha", "japanese": "シャワー" },
        { "latin": ["verde", "zona verde"], "japanese": "みどり" },
        { "latin": "templo budista", "japanese": "「お」てら" },
        { "latin": "santuario sintoísta", "japanese": "じんじゃ" },
        { "latin": "número", "japanese": "ーばん" },
        { "latin": ["cómo", "de qué manera"], "japanese": ["どうやって", "なんで"] },
        { "latin": "cuál", "japanese": "どの～" },
        { "latin": "cuál", "japanese": "どれ" },
        { "latin": "increíble", "japanese": "すごいですね" },
        { "latin": "todavía", "japanese": "まだまだです" },
        { "latin": ["bajo", "pequeño"], "japanese": "ちさい" },
        { "latin": "botón", "japanese": "ボタン" }
    ],
    

    "lesson17": [
        { "latin": "memorizar", "japanese": "おぼえます" },
        { "latin": "olvidar", "japanese": "わすれます" },
        { "latin": "perder", "japanese": "なくします" },
        { "latin": "pagar", "japanese": "はらいます" },
        { "latin": "devolver", "japanese": "かえします" },
        { "latin": ["salir", "ir", "venir", "volver"], "japanese": "「へ」でかけます" },
        { "latin": "quitarse", "japanese": "ぬぎます" },
        { "latin": "llevar", "japanese": "もっていきます" },
        { "latin": "traer", "japanese": "もってきます" },
        { "latin": "preocuparse", "japanese": "しんぱいします" },
        { "latin": "trabajar horas extra", "japanese": "ざんぎょうします" },
        { "latin": "ir de viaje de trabajo", "japanese": "しゅっちょうします" },
        { "latin": ["tomar medicinas", "medicarse"], "japanese": "「くすりを」のみます" },
        { "latin": ["tomar un baño", "bañarse"], "japanese": "「おふろに」はいります" },
        { "latin": "importante", "japanese": "たいせつ「な」" },
        { "latin": "estar bien", "japanese": "だいじょうぶ「な」" },
        { "latin": "peligroso", "japanese": "あぶない" },
        { "latin": "prohibido fumar", "japanese": "きんえん" },
        { "latin": "tarjeta del seguro de salud", "japanese": "けんこうほけんしょう" },
        { "latin": "fiebre", "japanese": "ねつ" },
        { "latin": "enfermedad grave", "japanese": "びょうき" },
        { "latin": ["medicina", "medicamento", "pastillas"], "japanese": "くすり" },
        { "latin": ["chaqueta", "abrigo"], "japanese": "うわぎ" },
        { "latin": "ropa interior", "japanese": "したぎ" },
        { "latin": "unos días", "japanese": "２，３にち" },
        { "latin": "unos", "japanese": "２，３～" },
        { "latin": "antes de", "japanese": "～までに" },
        { "latin": ["por eso", "entonces"], "japanese": "ですから" },
        { "latin": "preocupación", "japanese": "しんぱい" },
        { "latin": "horas extra", "japanese": "ざんぎょう" },
        { "latin": "seguro", "japanese": "ほけん" },
        { "latin": "tarjeta", "japanese": "しょう" },


        
        { "latin": "bañera", "japanese": "おふろ" },
        { "latin": "platos", "japanese": "おさら" },
        { "latin": "país extranjero", "japanese": "かいがい" },
        { "latin": "escuela", "japanese": "しゅうちょう" },
        { "latin": "documento", "japanese": "しりょう" },
        { "latin": "tortilla", "japanese": "オムレツ" },
        { "latin": "arroz blanco aguado", "japanese": "おかゆ" },
        { "latin": ["comprobar", "confirmar"], "japanese": "かくにんします" },
        { "latin": "que te mejores", "japanese": "おだいじに" }
    ],
    


    "lesson18": [
        { "latin": ["poder", "ser capaz de"], "japanese": "できます" },
        { "latin": "lavar", "japanese": "あらいます" },
        { "latin": "tocar", "japanese": "ひきます" },
        { "latin": "cantar", "japanese": "うたいます" },
        { "latin": ["coleccionar", "reunir"], "japanese": "あつめます" },
        { "latin": ["tirar", "desechar"], "japanese": "すてます" },
        { "latin": ["cambiar", "reemplazar"], "japanese": "かえます" },
        { "latin": "conducir", "japanese": "うんてんします" },
        { "latin": "reservar", "japanese": "よやくします" },
        { "latin": "piano", "japanese": "ピアノ" },
        { "latin": "metro", "japanese": "メートル" },
        { "latin": "dinero en efectivo", "japanese": "げんきん" },
        { "latin": ["afición", "pasatiempo"], "japanese": "しゅみ" },
        { "latin": "diario", "japanese": "にっき" },
        { "latin": "oración", "japanese": "おいのり" },
        { "latin": "jefe de sección", "japanese": "かちょう" },
        { "latin": ["gerente de división", "gerente de departamento"], "japanese": "ぶちょう" },
        { "latin": ["director ejecutivo", "presidente", "director general de una empresa"], "japanese": "しゃちょう" },
        { "latin": "animal", "japanese": "どうぶつ" },
        { "latin": "caballo", "japanese": "うま" },
        { "latin": "internet", "japanese": "インターネット" },
        


        { "latin": ["por supuesto", "claro"], "japanese": "ぜひ" },
        { "latin": "estar feliz", "japanese": "うれしい" },
        { "latin": "comida china", "japanese": "ちゅうか「りょうり」" },
        { "latin": "otro día", "japanese": "べつのひ" },
        { "latin": "uniforme", "japanese": "ユニフォーム" },
        { "latin": "Navidad", "japanese": "クリスマスイブ" },
        { "latin": "salón", "japanese": ["リビング", "いま"] },
        { "latin": "abuelos", "japanese": "そふぼ" },
        { "latin": "niebla", "japanese": "きり" },
        { "latin": "Nochevieja", "japanese": "おおみそか" },
        { "latin": "casa antigua de alquiler", "japanese": "こみんか" },
        { "latin": "celebrar los 20 años", "japanese": "せいじんのひ" },
        { "latin": ["rezar", "orar"], "japanese": "おいのりします" },
        { "latin": "zoo", "japanese": "どうぶつえん" },
        { "latin": "poco", "japanese": ["あんまり", "あまり"] },
        { "latin": "mi alumno", "japanese": "せいと" },
        { "latin": "natación", "japanese": "すいえい" },
        { "latin": "no es fácil", "japanese": "なかなか" },
        { "latin": "ruidoso", "japanese": ["うるさい", "やかましい"] },
        { "latin": "plan", "japanese": "よてい" },
        { "latin": "propósito", "japanese": "もくひょう" },
        { "latin": "antes de", "japanese": "まえに" },
        { "latin": "cepillarse los dientes", "japanese": "「ほを」みがきます" },
        { "latin": "personalidad", "japanese": "せいかく" },
        { "latin": "planear", "japanese": "「よていを」つくります" },
        { "latin": "época", "japanese": "じだい" },
        { "latin": "otra vez", "japanese": "もういちど" },
        { "latin": "me encantaría", "japanese": "ぜひもいちど" },
        { "latin": "peluche", "japanese": "ぬいぐるみ" },
        { "latin": "especialmente", "japanese": "とくに" },
        { "latin": "historia", "japanese": "れきし" },
        { "latin": "saltear", "japanese": "やきます" },
        { "latin": "matemáticas", "japanese": "すうがく" },
        { "latin": "educación física", "japanese": "たいいく" },
        { "latin": "crecer", "japanese": "ふえます" },
        { "latin": "estricto", "japanese": "きびし" },
        { "latin": "terraza", "japanese": "テラス" },
        { "latin": "comida del comedor", "japanese": "きゅうしょく" }
        
    ],
    


    "lesson19": [
        { "latin": ["subir", "escalar"], "japanese": "「やまに」のぼります" },
        { "latin": ["alojarse", "hospedarse"], "japanese": "「ホテルに」とまります" },
        { "latin": "limpiar", "japanese": "そうじします" },
        { "latin": ["lavar la ropa", "hacer la colada"], "japanese": "せんたくします" },
        { "latin": ["convertirse", "hacerse", "llegar"], "japanese": "なります" },
        { "latin": "tener sueño", "japanese": "ねむい" },
        { "latin": "fuerte", "japanese": "つよい" },
        { "latin": "débil", "japanese": "よわい" },
        { "latin": ["práctica", "ensayo"], "japanese": "れんしゅう" },
        { "latin": ["practicar", "ensayar"], "japanese": "れんしゅう「を」します" },
        { "latin": "golf", "japanese": "ゴルフ" },
        { "latin": "sumo", "japanese": "すもう" },
        { "latin": "practicar sumo", "japanese": "すもうします" },
        { "latin": "ceremonia del té", "japanese": "おちゃ" },
        { "latin": "hacer ceremonia del té", "japanese": "おちゃをします" },
        { "latin": ["día", "fecha"], "japanese": "ひ" },
        { "latin": ["forma", "condición"], "japanese": "ちょうし" },
        { "latin": "una vez", "japanese": "いちど" },
        { "latin": "nunca", "japanese": "いちども" },
        { "latin": "poco a poco", "japanese": "だんだん" },
        { "latin": ["dentro de poco", "pronto"], "japanese": "もうすぐ" },
        { "latin": ["gracias a usted", "gracias a Dios"], "japanese": "おかげさまで" },
        { "latin": ["pero", "sin embargo"], "japanese": ["でも", "けど"] },


        
        { "latin": "lavadora", "japanese": "せんたくき" },
        { "latin": "olor", "japanese": "におい" },
        { "latin": "marear", "japanese": "よいます" },
        { "latin": "teleférico", "japanese": "ロープウェー" },
        { "latin": "guía", "japanese": "ガイド" },
        { "latin": "elegante", "japanese": "エレガント" },
        { "latin": ["dejar de funcionar", "estropearse"], "japanese": "こしょうします" }
    ],
    


    "lesson20": [
        { "latin": ["necesitar", "requerir"], "japanese": "「ビザが」いります" },
        { "latin": ["buscar", "averiguar", "investigar"], "japanese": "しらべます" },
        { "latin": "reparar", "japanese": "しゅうりします" },
        { "latin": "yo", "japanese": "ぼく" },
        { "latin": "tú", "japanese": "きみ" },
        { "latin": "señor", "japanese": "～くん" },
        { "latin": "sí", "japanese": "うん" },
        { "latin": "no", "japanese": "ううん" },
        { "latin": ["palabra", "lenguaje", "idioma"], "japanese": "ことば" },
        { "latin": "kimono", "japanese": "きもの" },
        { "latin": ["visa", "visado"], "japanese": "ビザ" },
        { "latin": ["comienzo", "principio"], "japanese": "はじめ" },
        { "latin": "fin", "japanese": "おわり" },
        { "latin": ["por aquí", "aquí"], "japanese": "こっち" },
        { "latin": ["por ahí", "ahí"], "japanese": "そっち" },
        { "latin": ["por allí", "allí"], "japanese": "あっち" },
        { "latin": ["cuál", "dónde", "por dónde"], "japanese": "どっち" },
        { "latin": "todos juntos", "japanese": "みんなで" },
        { "latin": "pero", "japanese": "～けど" },
        { "latin": ["estoy satisfecho", "estoy lleno"], "japanese": "おなかがいっぱいです" },

        { "latin": "lo siento pero me voy primero", "japanese": "おさきにしつれいします" },
        { "latin": "ayuntamiento", "japanese": "しやくしょ" },
        { "latin": "cómo", "japanese": "どう" },
        { "latin": "cómo fue", "japanese": "どうだった" },
        { "latin": ["vamos a", "hagámoslo"], "japanese": "そうします" },
        { "latin": "ida y vuelta", "japanese": "おうふく" },
        { "latin": "?", "japanese": "はてな" },
        { "latin": "!", "japanese": "ビックリマーク" },
        { "latin": "si no te importa", "japanese": "よかったら" },
        { "latin": "más o menos cuando", "japanese": "いつごろ" },
        { "latin": "creo que no", "japanese": "ないかも" },
    ]
}