const book_json = {
    "days": [
        { "spanish": ["sol", "día"], "kana": "ひ", "kanji": "日" },
        { "spanish": "domingo", "kana": "にちようび", "kanji": "日曜日" },
        { "spanish": "Japón", "kana": "にほん", "kanji": "日本" },
        { "spanish": "Japón", "kana": "にっぽん", "kanji": "日本" },
        { "spanish": "todos los días", "kana": "まいにち", "kanji": "毎日" },
        { "spanish": ["vacaciones", "día libre"], "kana": "きゅうじつ", "kanji": "休日" },
        { "spanish": "mañana", "kana": "あす", "kanji": "明日" },
        { "spanish": "mañana", "kana": "あした", "kanji": "明日" },

        { "spanish": "Luna", "kana": "つき", "kanji": "月" },
        { "spanish": ["días", "años"], "kana": "つきひ", "kanji": "月日" },
        { "spanish": "todos los meses", "kana": "まいつき", "kanji": "毎月" },
        { "spanish": "lunes", "kana": "げつようび", "kanji": "月曜日" },
        { "spanish": "Año Nuevo", "kana": "しょうがつ", "kanji": "正月" },
        { "spanish": "próximo mes", "kana": "らいげつ", "kanji": "来月" },

        { "spanish": "fuego", "kana": "ひ", "kanji": "火" },
        { "spanish": "fuego artificial", "kana": "はなび", "kanji": "花火" },
        { "spanish": "incendio", "kana": "かじ", "kanji": "火事" },
        { "spanish": "martes", "kana": "かようび", "kanji": "火曜日" },
        { "spanish": "extintor", "kana": "しょうかき", "kanji": "消火器" },
        { "spanish": "simulacro de incendio", "kana": "ぼうかくんれん", "kanji": "防火訓練" },
        
        { "spanish": "agua", "kana": "みず", "kanji": "水" },
        { "spanish": "planta depuradora de agua", "kana": "すいどう", "kanji": "水道" },
        { "spanish": "azul claro", "kana": "みずいろ", "kanji": "水色" },
        { "spanish": "humedad", "kana": "すいぶん", "kanji": "水分" },
        { "spanish": "bañador", "kana": "みずぎ", "kanji": "水着" },
        { "spanish": "miércoles", "kana": "すいようび", "kanji": "水曜日" },

        { "spanish": "árbol", "kana": "き", "kanji": "木" },
        { "spanish": "viento frío", "kana": "こがらし", "kanji": "木枯らし" },
        { "spanish": "madera", "kana": "ざいもく", "kanji": "材木" },
        { "spanish": "de madera", "kana": "もくぞう", "kanji": "木造" },
        { "spanish": "lana", "kana": "もめん", "kanji": "木綿" },
        { "spanish": "jueves", "kana": "もくようび", "kanji": "木曜日" },

        { "spanish": "persona rica", "kana": "かねもち", "kanji": "金持ち" },
        { "spanish": "precio", "kana": "きんがく", "kanji": "金額" },
        { "spanish": "dinero", "kana": "おかね", "kanji": "お金" },
        { "spanish": "finanzas", "kana": "きんゆう", "kanji": "金融" },
        { "spanish": "oro", "kana": "きん", "kanji": "金" },
        { "spanish": "viernes", "kana": "きんようび", "kanji": "金曜日" },

        { "spanish": "tierra", "kana": "つち", "kanji": "土" },
        { "spanish": "arcilla", "kana": "ねんど", "kanji": "粘土" },
        { "spanish": "cimientos", "kana": "どだい", "kanji": "土台" },
        { "spanish": "tierra", "kana": "とち", "kanji": "土地" },
        { "spanish": "sábado", "kana": "どようび", "kanji": "土曜日" },
        { "spanish": "regalo", "kana": "みやげ", "kanji": "土産" },

        { "spanish": "día de la semana", "kana": "ようび", "kanji": "曜日" },
        { "spanish": "jueves", "kana": "もくようび", "kanji": "木曜日" },
        { "spanish": "domingo", "kana": "にちようび", "kanji": "日曜日" },
        { "spanish": "viernes", "kana": "きんようび", "kanji": "金曜日" },
        { "spanish": "lunes", "kana": "げつようび", "kanji": "月曜日" },
        { "spanish": "sábado", "kana": "どようび", "kanji": "土曜日" },
    ],

    "numbers_1": [
        { "spanish": "uno", "kana": "ひとつ", "kanji": "一つ" },
        { "spanish": "enero", "kana": "いちがつ", "kanji": "一月" },
        { "spanish": "una vez", "kana": "いちど", "kanji": "一度" },
        { "spanish": "primero", "kana": "だいいち", "kanji": "第一" },
        { "spanish": "solo", "kana": "ひとり", "kanji": "一人" },
        { "spanish": "día 1", "kana": "ついたち", "kanji": "一日" },
        
        { "spanish": "dos", "kana": "ふたつ", "kanji": "二つ" },
        { "spanish": "20 años", "kana": "はたち", "kanji": "二十歲" },
        { "spanish": "febrero", "kana": "にがつ", "kanji": "二月" },
        { "spanish": "dos personas", "kana": "ふたり", "kanji": "二人" },
        { "spanish": "doble", "kana": "にじゅう", "kanji": "二重" },
        { "spanish": "día 2", "kana": "ふつか", "kanji": "二日" },
        
        { "spanish": "luna creciente", "kana": "みかづき", "kanji": "三日月" },
        { "spanish": "tres", "kana": "みっつ", "kanji": "三つ" },
        { "spanish": "triángulo", "kana": "さんかく", "kanji": "三角" },
        { "spanish": "marzo", "kana": "さんがつ", "kanji": "三月" },
        { "spanish": "baja calidad", "kana": "さんりゅう", "kanji": "三流" },
        { "spanish": "día 3", "kana": "みっか", "kanji": "三日" },
        
        { "spanish": "día 4", "kana": "よっか", "kanji": "四日" },
        { "spanish": "cuadrado", "kana": "しかく", "kanji": "四角" },
        { "spanish": "cruce", "kana": "よつかど", "kanji": "四つ角" },
        { "spanish": "abril", "kana": "しがつ", "kanji": "四月" },
        { "spanish": "cuatro", "kana": "よっつ", "kanji": "四つ" },
        { "spanish": "cuatro estaciones", "kana": "しき", "kanji": "四季" },
        
        { "spanish": "día 5", "kana": "いつか", "kanji": "五日" },
        { "spanish": "cinco cosas", "kana": "いつつ", "kanji": "五つ" },
        { "spanish": "mayo", "kana": ["ごがつ", "さつき"], "kanji": "五月" },
        { "spanish": "silabario japonés", "kana": "ごじゅうおん", "kanji": "五十音" },
        { "spanish": "redondear", "kana": "ししゃごにゅう", "kanji": "四捨五入" },
        
        { "spanish": "día 6", "kana": "むいか", "kanji": "六日" },
        { "spanish": "hexágono", "kana": "ろっかっけい", "kanji": "六角形" },
        { "spanish": "seis", "kana": "むっつ", "kanji": "六つ" },
        { "spanish": "siempre", "kana": "しろくじちゅう", "kanji": "四六時中" },
        { "spanish": "junio", "kana": "ろくがつ", "kanji": "六月" },
        { "spanish": "sexto sentido", "kana": "だいろっかん", "kanji": "第六感" },
        
        { "spanish": "siete colores", "kana": "なないろ", "kanji": "七色" },
        { "spanish": "día 7", "kana": "なのか", "kanji": "七日" },
        { "spanish": "siete veces", "kana": "ななかい", "kanji": "七回" },
        { "spanish": "julio", "kana": "しちがつ", "kanji": "七月" },
        { "spanish": "siete", "kana": "ななつ", "kanji": "七つ" },
        { "spanish": "Tanabata", "kana": "たなばた", "kanji": "七夕" },

        { "spanish": "ocho", "kana": "やっつ", "kanji": "八つ" },
        { "spanish": "agosto", "kana": "はちがつ", "kanji": "八月" },
        { "spanish": "enfurecerse", "kana": "やつあたり", "kanji": "八つ当たり" },
        { "spanish": "octágono", "kana": "はっかっけい", "kanji": "八角形" },
        { "spanish": "día 8", "kana": "ようか", "kanji": "八日" },
        { "spanish": "tienda de frutas y verduras", "kana": "やおや", "kanji": "八百屋" },
    ],

    "numbers_2": [
        { "spanish": "día 9", "kana": "ここのか", "kanji": "九日" },
        { "spanish": "nueve", "kana": "ここのつ", "kanji": "九つ" },
        { "spanish": "Kyuushuu", "kana": "きゅうしゅう", "kanji": "九州" },
        { "spanish": "900", "kana": "きゅうひゃく", "kanji": "九百" },
        { "spanish": "septiembre", "kana": "くがつ", "kanji": "九月" },
        { "spanish": "diez a uno", "kana": "くぶくりん", "kanji": "九分九厘" },

        { "spanish": "diez", "kana": "じゅう", "kanji": "十" },
        { "spanish": "día 10", "kana": "とおか", "kanji": "十日" },
        { "spanish": "octubre", "kana": "じゅうがつ", "kanji": "十月" },
        { "spanish": "noche de luna llena", "kana": "じゅうごや", "kanji": "十五夜" },
        { "spanish": "moneda de 10 yenes", "kana": "じゅうえんだま", "kanji": "十円玉" },
        { "spanish": "cruce", "kana": "じゅうじろ", "kanji": "十字路" },
        
        { "spanish": "cien", "kana": "ひゃく", "kanji": "百" },
        { "spanish": "cien yenes", "kana": "ひゃくえん", "kanji": "百円" },
        { "spanish": "tienda de 100 yenes", "kana": "ひゃくえんショップ", "kanji": "百円ショップ" },
        { "spanish": "enciclopedia", "kana": "ひゃっかじてん", "kanji": "百科事典" },
        { "spanish": "tienda departamental", "kana": "ひゃっかてん", "kanji": "百貨店" },
        { "spanish": "cientos", "kana": "すうひゃく", "kanji": "数百" },
        
        { "spanish": "Chiba", "kana": "ちば", "kanji": "千葉" },
        { "spanish": "distrito de Chiyoda", "kana": "ちよだく", "kanji": "千代田区" },
        { "spanish": "mil", "kana": "せん", "kanji": "千" },
        { "spanish": "mil yenes", "kana": "せんえん", "kanji": "千円" },
        { "spanish": "diverso", "kana": "せんさばんべつ", "kanji": "千差万別" },
        { "spanish": "miles de veces", "kana": "せんばい", "kanji": "千倍" },
        
        { "spanish": "pluma estilográfica", "kana": "まんねんひつ", "kanji": "万年筆" },
        { "spanish": "un millón", "kana": "ひゃくまん", "kanji": "百万" },
        { "spanish": "billete de diez mil yenes", "kana": "いちまんえんさつ", "kanji": "一万円札" },
        { "spanish": "multifunción", "kana": "ばんのお", "kanji": "万能" },
        { "spanish": "billonario", "kana": "おくまんちょうじゃ", "kanji": "億万長者" },
        { "spanish": "emergencia", "kana": "まんいち", "kanji": "万一" },
        
        { "spanish": "en medio", "kana": "なかば", "kanji": "半ば" },
        { "spanish": "segunda mitad", "kana": "こうはん", "kanji": "後半" },
        { "spanish": "mitad de precio", "kana": "はんがく", "kanji": "半額" },
        { "spanish": "primera mitad", "kana": "ぜんはん", "kanji": "前半" },
        { "spanish": "mitad", "kana": "はんぶん", "kanji": "半分" },
        { "spanish": "doce y media", "kana": "じゅうにじはん", "kanji": "十二時半" },
        
        { "spanish": "todo", "kana": "すべて", "kanji": "全て" },
        { "spanish": "total", "kana": "ぜんぶ", "kanji": "全部" },
        { "spanish": "todos los miembros", "kana": "ぜんいん", "kanji": "全員" },
        { "spanish": "seguro", "kana": "あんぜん", "kanji": "安全" },
        { "spanish": "todo", "kana": "ぜんたい", "kanji": "全体" },
        { "spanish": ["completitud", "perfección"], "kana": "かんぜん", "kanji": "完全" },
        
        { "spanish": "número", "kana": "かず", "kanji": "数" },
        { "spanish": "número de personas", "kana": "にんずう", "kanji": "人数" },
        { "spanish": "contar", "kana": "かぞえる", "kanji": "数える" },
        { "spanish": "número de años", "kana": "ねんずう", "kanji": "年数" },
        { "spanish": "matemáticas", "kana": "すうがく", "kanji": "数学" },
        { "spanish": "plural", "kana": "ふくすう", "kanji": "複数" },
    ],

    "money": [
        { "spanish": "redondo", "kana": "まるい", "kanji": "円い" },
        { "spanish": "liso", "kana": "えんかつ", "kanji": "円滑" },
        { "spanish": ["redondo", "círculo"], "kana": "えんけい", "kanji": "円形" },
        { "spanish": ["afable", "amigable"], "kana": "えんまん", "kanji": "円満" },
        { "spanish": "un yen", "kana": "いちえん", "kanji": "一円" },
        { "spanish": "billete de mil yenes", "kana": "せんえんさつ", "kanji": "千円札" },
        
        { "spanish": "padres", "kana": "りょうしん", "kanji": "両親" },
        { "spanish": "ambas manos", "kana": "りょうて", "kanji": "両手" },
        { "spanish": "ambos", "kana": "りょうほう", "kanji": "両方" },
        { "spanish": "ambos lados", "kana": "りょうめん", "kanji": "両面" },
        { "spanish": "doble uso", "kana": "りょうよう", "kanji": "両用" },
        { "spanish": "coexistir", "kana": "りょうりつ", "kanji": "両立" },
        
        { "spanish": "intercambio", "kana": "かえる", "kanji": "替える" },
        { "spanish": "cambio", "kana": "きがえ", "kanji": "着替え" },
        { "spanish": "intercambio de dinero", "kana": "りょうがえ", "kanji": "両替" },
        { "spanish": "remplazar", "kana": "かわる", "kanji": "替わる" },
        { "spanish": "giro postal", "kana": "かわせ", "kanji": "為替" },
        { "spanish": "alternación", "kana": "こうたい", "kanji": "交替" },
        
        { "spanish": "cargamento", "kana": "かもつ", "kanji": "貨物" },
        { "spanish": "moneda", "kana": "こうか", "kanji": "硬貨" },
        { "spanish": "divisa extranjera", "kana": "がいか", "kanji": "外貨" },
        { "spanish": "bienes variados", "kana": "ざっか", "kanji": "雑貨" },
        { "spanish": "moneda de oro", "kana": "きんか", "kanji": "金貨" },
        { "spanish": "tienda departamental", "kana": "ひゃっかてん", "kanji": "百貨店" },
        
        { "spanish": "impuesto", "kana": "ぜえ", "kanji": "税" },
        { "spanish": "oficina de impuestos", "kana": "ぜいむしょ", "kanji": "税務署" },
        { "spanish": "aduanas", "kana": "ぜいかん", "kanji": "税関" },
        { "spanish": "contable certificado de impuestos", "kana": "ぜいりし", "kanji": "税理士" },
        { "spanish": "impuesto", "kana": "ぜいきん", "kanji": "税金" },
        { "spanish": "impuesto de consumición", "kana": "しょうひぜい", "kanji": "消費税" },
        
        { "spanish": ["perder", "escape"], "kana": "まぬかれる", "kanji": "免れる" },
        { "spanish": "excepción", "kana": "めんじょ", "kanji": "免除" },
        { "spanish": ["inmunización", "inmunidad"], "kana": "めんえき", "kanji": "免疫" },
        { "spanish": "despido", "kana": "めんしょく", "kanji": "免職" },
        { "spanish": "licencia", "kana": "めんきょう", "kanji": "免許" },
        { "spanish": "libre de impuestos", "kana": "めんぜい", "kanji": "免税" },
        
        { "spanish": ["campo", "territorio"], "kana": "りょういき", "kanji": "領域" },
        { "spanish": "dominio", "kana": "りょうど", "kanji": "領土" },
        { "spanish": "consulado", "kana": "りょうじかん", "kanji": "領事館" },
        { "spanish": "punto", "kana": "ようりょう", "kanji": "要領" },
        { "spanish": "recibo", "kana": "りょうしゅうしょう", "kanji": "領収証" },
        { "spanish": "presidente", "kana": "だいとうりょう", "kanji": "大統領" },
        
        { "spanish": "obtener", "kana": "おさめる", "kanji": "収める" },
        { "spanish": "ingresos", "kana": "しゅうにゅう", "kanji": "収入" },
        { "spanish": "asentarse", "kana": "おさまる", "kanji": "収まる" },
        { "spanish": ["recolectar", "coleccionar"], "kana": "しゅうしゅう", "kanji": "収集" },
        { "spanish": "recolectar", "kana": "しゅうかく", "kanji": "収穫" },
        { "spanish": "absorción", "kana": "きゅうしゅう", "kanji": "吸収" },
        
        { "spanish": "testimonio", "kana": "しょうげん", "kanji": "証言" },
        { "spanish": ["certificación", "verificación"], "kana": "しょうめい", "kanji": "証明" },
        { "spanish": ["evidencia", "prueba"], "kana": "しょうこ", "kanji": "証拠" },
        { "spanish": "identificación de estudiante", "kana": "がくせいしょう", "kanji": "学生証" },
        { "spanish": "testigo", "kana": "しょうにん", "kanji": "証人" },
        { "spanish": "licencia", "kana": "めんきょしょう", "kanji": "免許証" },
    ],

    "time": [
        { "spanish": "separar", "kana": "わける", "kanji": "分ける" },
        { "spanish": "distribución", "kana": "ぶんぱい", "kanji": "分配" },
        { "spanish": "descomposición", "kana": "ぶんかい", "kanji": "分解" },
        { "spanish": "treinta minutos", "kana": ["さんじっぷん", "さんじゅっぷん"], "kanji": "30分" },
        { "spanish": "análisis", "kana": "ぶんせき", "kanji": "分析" },
        { "spanish": "uno mismo", "kana": "じぶん", "kanji": "自分" },
        
        { "spanish": "tiempo", "kana": "とき", "kanji": "時" },
        { "spanish": "a veces", "kana": "ときどき", "kanji": "時々" },
        { "spanish": ["tiempo", "hora"], "kana": "じかん", "kanji": "時間" },
        { "spanish": "horario", "kana": "じこくひょう", "kanji": "時刻表" },
        { "spanish": "primer período", "kana": "いちじかんめ", "kanji": "1時間目" },
        { "spanish": "reloj", "kana": "とけい", "kanji": "時計" },
        
        { "spanish": "revista semanal", "kana": "しゅうかんし", "kanji": "週刊誌" },
        { "spanish": "fin de semana", "kana": "しゅうまつ", "kanji": "週末" },
        { "spanish": "esta semana", "kana": "こんしゅう", "kanji": "今週" },
        { "spanish": "la semana pasada", "kana": "せんしゅう", "kanji": "先週" },
        { "spanish": "todas las semanas", "kana": "まいしゅう", "kanji": "毎週" },
        { "spanish": "la semana que viene", "kana": "らいしゅう", "kanji": "来週" },
        
        { "spanish": "persona mayor", "kana": "としより", "kanji": "年寄り" },
        { "spanish": "año fiscal", "kana": "ねんど", "kanji": "年度" },
        { "spanish": "anual", "kana": "ねんかん", "kanji": "年間" },
        { "spanish": ["edad", "años"], "kana": "ねんれい", "kanji": "年齢" },
        { "spanish": ["era", "año"], "kana": "ねんだい", "kanji": "年代" },
        { "spanish": "estudiante de primer grado", "kana": "いちねんせい", "kanji": "1年生" },
        
        { "spanish": ["ahora", "presente"], "kana": "いま", "kanji": "今" },
        { "spanish": "próxima vez", "kana": "こんど", "kanji": "今度" },
        { "spanish": "este mes", "kana": "こんげつ", "kanji": "今月" },
        { "spanish": "a partir de ahora", "kana": "こんご", "kanji": "今後" },
        { "spanish": "hoy", "kana": "きょう", "kanji": "今日" },
        { "spanish": "este año", "kana": "ことし", "kanji": "今年" },
        
        { "spanish": ["inicio", "comienzo"], "kana": "はじめ", "kanji": "初め" },
        { "spanish": "etapa inicial", "kana": "しょき", "kanji": "初期" },
        { "spanish": "la primera vez", "kana": "はじめて", "kanji": "初めて" },
        { "spanish": "principiante", "kana": "しょしんしゃ", "kanji": "初心者" },
        { "spanish": "primera nieve", "kana": "はつゆき", "kanji": "初雪" },
        { "spanish": "comienzo", "kana": "さいしょ", "kanji": "最初" },
        
        { "spanish": "inicio", "kana": "はじめ", "kanji": "始め" },
        { "spanish": "disculpa escrita", "kana": "しまつしょ", "kanji": "始末書" },
        { "spanish": ["inicio", "comienzo"], "kana": "はじめる", "kanji": "始める" },
        { "spanish": ["inicio", "principio"], "kana": "かいし", "kanji": "開始" },
        { "spanish": "primer tren", "kana": "しはつ", "kanji": "始発" },
        { "spanish": "inicio del año", "kana": "ねんし", "kanji": "年始" },
        
        { "spanish": "fin", "kana": "おわり", "kanji": "終わり" },
        { "spanish": ["final", "completo"], "kana": "おわる", "kanji": "終わる" },
        { "spanish": "terminal", "kana": "しゅうてん", "kanji": "終点" },
        { "spanish": "último tren", "kana": "しゅうでん", "kanji": "終電" },
        { "spanish": "último", "kana": "さいしゅう", "kanji": "最終" },
        { "spanish": ["siempre", "constantemente"], "kana": "しじゅう", "kanji": "始終" },
    ],

    "interrogative_counters": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],
};