const kanjij3words_json = {
    "kanji_day_1": [
        { "spanish": "dirección", "kana": "じゅうしょ", "kanji": "住所" },
        { "spanish": "lugar", "kana": "ばしょ", "kanji": "ば所" },
        { "spanish": "cocina", "kana": "だいどころ", "kanji": "だい所" },
        { "spanish": "Tokyo", "kana": "とうきょう", "kanji": "東京" },
        { "spanish": "Kyoto", "kana": "きょうと", "kanji": "京都" },
        { "spanish": "conveniente", "kana": "つごうがいい", "kanji": "都合がいい" },
        { "spanish": "capital", "kana": "しゅと", "kanji": "首都" },
        { "spanish": "prefectura de Kyoto", "kana": "きょうとふ", "kanji": "京都府" },
        { "spanish": "provincia de Yamaguchi", "kana": "やまぐちけん", "kanji": "山口県" },
        { "spanish": "alcalde", "kana": "しちょう", "kanji": "市長" },
        { "spanish": "ayuntamiento", "kana": "しやくしょ", "kanji": "市やく所" },
        { "spanish": "distrito de Shinjuku", "kana": "しんじゅくく", "kanji": "新じゅく区" },
        { "spanish": "barrio de Kabuki", "kana": "かぶきちょう", "kanji": "かぶき町" },
        { "spanish": "alcalde", "kana": "そんちょう", "kanji": "村長" }
    ],

    "kanji_day_2": [
        { "spanish": "explicación", "kana": "せつめい", "kanji": "せつ明" },
        { "spanish": "mañana", "kana": "あした", "kanji": "明日" },
        { "spanish": "contraseña", "kana": "あんしょうばんごう", "kanji": "暗しょうばんごう" },
        { "spanish": "viaje escolar", "kana": "えんそく", "kanji": "遠足" },
        { "spanish": "últimamente", "kana": "さいきん", "kanji": "さい近" },
        { "spanish": "vecindario", "kana": "きんじょ", "kanji": "近所" },
        { "spanish": "estudio", "kana": "べんきょう", "kanji": "べん強" },
        { "spanish": "debilidad", "kana": "じゃくてん", "kanji": "弱てん" },
        { "spanish": ["importante", "serio"], "kana": "じゅうだいな", "kanji": "重大な" },
        { "spanish": ["snack", "picoteo"], "kana": "けいしょく", "kanji": "軽食" },
        { "spanish": "vehículo ligero", "kana": "けいじどうしゃ", "kanji": "軽自どう車" },
        { "spanish": "Sol", "kana": "たいよう", "kanji": "太よう" },
        { "spanish": "bacteria", "kana": "さいきん", "kanji": "細きん" }
    ],

    "kanji_day_3": [
        { "spanish": "especialmente", "kana": "とくに", "kanji": "特に" },
        { "spanish": "especial", "kana": "とくべつ", "kanji": "特別" },
        { "spanish": "por separado", "kana": "べつべつに", "kanji": "別々に" },
        { "spanish": "famoso", "kana": "ゆうめい", "kanji": "有名" },
        { "spanish": "de pago", "kana": "ゆうりょう", "kanji": "有りょう" },
        { "spanish": "oficina de correos", "kana": "ゆうびんきょく", "kanji": "ゆう便きょく" },
        { "spanish": "envío aéreo", "kana": "こうくうびん", "kanji": "こう空便" },
        { "spanish": "útil", "kana": "りようする", "kanji": "利ようする" },
        { "spanish": "usar cosas públicas", "kana": "ふべん", "kanji": "不便" },
        { "spanish": "inconveniente", "kana": "ふあん", "kanji": "不安" },
        { "spanish": "escasear", "kana": "ふそく", "kanji": "不足" },
        { "spanish": "sello", "kana": "きって", "kanji": "切手" },
        { "spanish": "amable", "kana": "しんせつ", "kanji": "しん切" },
        { "spanish": "importante", "kana": "たいせつ", "kanji": "大切" },
        { "spanish": "exnovio", "kana": "もとカレ", "kanji": "元カレ" },
        { "spanish": "uno de enero", "kana": "がんじつ", "kanji": "元日" },
        { "spanish": "animado", "kana": "げんき", "kanji": "元気" },
        { "spanish": "lugar donde estaba", "kana": "もとのところ", "kanji": "元の所" },
        { "spanish": "comida favorita", "kana": "だいこうぶつ", "kanji": "大好ぶつ" },
        { "spanish": "de repente", "kana": "きゅうに", "kanji": "急に" },
        { "spanish": "tren sin paradas", "kana": "とっきゅうでんしゃ", "kanji": "特急電車" },
        { "spanish": "ambulancia", "kana": "きゅうきゅうしゃ", "kanji": "きゅう急車" }
    ],

    "kanji_day_4": [
        { "spanish": "primer ciclo de primaria", "kana": "ていがくねん", "kanji": "低学年" },
        { "spanish": "el más bajo", "kana": "さい低", "kanji": "さい低" },
        { "spanish": "plaza", "kana": "ひろば", "kanji": "広ば" },
        { "spanish": "anuncio", "kana": "こうこく", "kanji": "広こく" },
        { "spanish": ["irascible", "irritable"], "kana": "たんき", "kanji": "短気" },
        { "spanish": "feliz año", "kana": "よいおとしを", "kanji": "良いお年を" },
        { "spanish": ["consciencia", "moral"], "kana": "りょうしん", "kanji": "良しん" },
        { "spanish": "mala intención", "kana": "わるぎ", "kanji": "悪気" },
        { "spanish": ["el peor", "lo peor"], "kana": "さいあく", "kanji": "さい悪" },
        { "spanish": "Año Nuevo", "kana": "おしょうがつ", "kanji": "お正月" },
        { "spanish": "honesto", "kana": "しょうじき", "kanji": "正じき" },
        { "spanish": "puerta principal", "kana": "せいもん", "kanji": "正門" },
        { "spanish": "respuesta correcta", "kana": "せいかい", "kanji": "正かい" },
        { "spanish": "duro", "kana": "たいへん", "kanji": "大変" },
        { "spanish": ["clima", "tiempo raro"], "kana": "へんなてんき", "kanji": "変な天気" },
        { "spanish": "ecuador", "kana": "せきどう", "kanji": "赤道" },
        { "spanish": "bebé", "kana": "あかちゃん", "kanji": "赤ちゃん" },
        { "spanish": "juventud", "kana": "せいしゅん", "kanji": "青しゅん" },
        { "spanish": "joven", "kana": "せいねん", "kanji": "青年" },
        { "spanish": "foto en blanco y negro", "kana": "しろくろしゃしん", "kanji": "白黒しゃしん" },
        { "spanish": "pizarra", "kana": "こくばん", "kanji": "黒ばん" }
    ],
// ["", ""]
    "kanji_day_5": [
        { "spanish": ["fecha de emisión", "fecha de estreno"], "kana": "じょうえいび", "kanji": "上映日" },
        { "spanish": "película", "kana": "えいが", "kanji": "映画" },
        { "spanish": ["plan", "proyecto", "programación"], "kana": "けいかく", "kanji": "けい画" },
        { "spanish": ["pintor", "dibujante"], "kana": "がか", "kanji": "画家" },
        { "spanish": "forma de leer", "kana": "おんよみ", "kanji": "音読み" },
        { "spanish": "pronunciación", "kana": "はつおん", "kanji": "はつ音" },
        { "spanish": "música", "kana": "おんがく", "kanji": "音楽" },
        { "spanish": "diversión", "kana": "たのしみ", "kanji": "楽しみ" },
        { "spanish": "cómodo", "kana": "らくな", "kanji": "楽な" },
        { "spanish": "cantante", "kana": "かしゅ", "kanji": "歌手" },
        { "spanish": "himno", "kana": "こっか", "kanji": "国歌" },
        { "spanish": "letra de canción", "kana": "かし", "kanji": "歌し" },
        { "spanish": "poema antiguo", "kana": "たんか", "kanji": "短歌" },
        { "spanish": "centro", "kana": "まんなか", "kanji": "真ん中" },
        { "spanish": "serio", "kana": "まじめ", "kanji": "真じ目" },
        { "spanish": "fotografía", "kana": "しゃしん", "kanji": "写真" },
        { "spanish": "muy negro", "kana": "まっくろ", "kanji": "真っ黒" },
        { "spanish": "viaje", "kana": "りょこう", "kanji": "旅行" },
        { "spanish": "hostal", "kana": "りょかん", "kanji": "旅かん" },
        { "spanish": "cuidar", "kana": "せわをする", "kanji": "世話をする" },
        { "spanish": "sociedad", "kana": "よのなか", "kanji": "世の中" },
        { "spanish": "siglo 21", "kana": "にじゅういっせき", "kanji": "２１世き" },
        { "spanish": "mundo", "kana": "せかい", "kanji": "世界" }
    ],

    "kanji_day_6": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ]
};