const kanjij2words_json = {
    "kanji_day_1": [
        { "spanish": "una cosa", "kana": "ひとつ", "kanji": "一つ" },
        { "spanish": "día 1", "kana": "ついたち", "kanji": "一日" },
        { "spanish": "dos cosas", "kana": "ふたつ", "kanji": "二つ" },
        { "spanish": "día 2", "kana": "ふつか", "kanji": "二日" },
        { "spanish": "tres cosas", "kana": "みっつ", "kanji": "三つ" },
        { "spanish": "día 3", "kana": "みっか", "kanji": "三日" },
        { "spanish": "cuatro cosas", "kana": "よっつ", "kanji": "四つ" },
        { "spanish": "día 4", "kana": "よっか", "kanji": "四日" },
        { "spanish": "cinco cosas", "kana": "いつつ", "kanji": "五つ" },
        { "spanish": "día 5", "kana": "いつか", "kanji": "五日" },
        { "spanish": "seis cosas", "kana": "むっつ", "kanji": "六つ" },
        { "spanish": "día 6", "kana": "むいか", "kanji": "六日" },
        { "spanish": "siete cosas", "kana": "ななつ", "kanji": "七つ" },
        { "spanish": "día 7", "kana": "なのか", "kanji": "七日" },
        { "spanish": "ocho cosas", "kana": "やっつ", "kanji": "八つ" },
        { "spanish": "día 8", "kana": "ようか", "kanji": "八日" },
        { "spanish": "nueve cosas", "kana": "ここのつ", "kanji": "九つ" },
        { "spanish": "día 9", "kana": "ここのか", "kanji": "九日" },
        { "spanish": "diez cosas", "kana": "とお", "kanji": "十" },
        { "spanish": "día 10", "kana": "とおか", "kanji": "十日" }
    ],

    "kanji_day_2": [
        { "spanish": "montaña", "kana": "やま", "kanji": "山" },
        { "spanish": "Yamada", "kana": "やまだ", "kanji": "山田" },
        { "spanish": "volcán", "kana": "かさん", "kanji": "か山" },
        { "spanish": "río", "kana": "かわ", "kanji": "川" },
        { "spanish": "Kawasaki", "kana": "かわさき", "kanji": "川さき" },
        { "spanish": "un mes", "kana": "いっかげつ", "kanji": "一か月" },
        { "spanish": "enero", "kana": "いちがつ", "kanji": "一月" },
        { "spanish": "lunes", "kana": "げつようび", "kanji": "月曜日" },
        { "spanish": "fuegos artificiales", "kana": "はなび", "kanji": "はな火" },
        { "spanish": "hoguera", "kana": "たきび", "kanji": "たき火" },
        { "spanish": "martes", "kana": "かようび", "kanji": "火曜日" },
        { "spanish": "incendio", "kana": "かじ", "kanji": "火じ" },
        { "spanish": "miércoles", "kana": "すいようび", "kanji": "水曜日" },
        { "spanish": "jueves", "kana": "もくようび", "kanji": "木曜日" },
        { "spanish": "dinero", "kana": "おかね", "kanji": "お金" },
        { "spanish": "viernes", "kana": "きんようび", "kanji": "金曜日" },
        { "spanish": "jugar en el suelo", "kana": "つちあそびます", "kanji": "土あそびます" },
        { "spanish": "sábado", "kana": "どようび", "kanji": "土曜日" },
        { "spanish": "entrar en casa con zapatos", "kana": "どそく", "kanji": "土足" },
        { "spanish": "Japón", "kana": "にほん", "kanji": "日本" },
        { "spanish": "cumpleaños", "kana": "たんじょうび", "kanji": "たんじょう日" },
        { "spanish": "domingo", "kana": "にちようび", "kanji": "日曜日" },
        { "spanish": "este año", "kana": "ことし", "kanji": "今年" },
        { "spanish": "un año", "kana": "いちねん", "kanji": "一年" },
        { "spanish": "el año pasado", "kana": "きょうねん", "kanji": "きょう年" },
    ],

    "kanji_day_3": [
        { "spanish": "hombre musculoso", "kana": "ちからもち", "kanji": "力もち" },
        { "spanish": "fuerza física", "kana": "たいりょく", "kanji": "たい力" },
        { "spanish": "hacer esfuerzo", "kana": "どりょく", "kanji": "ど力" },
        { "spanish": "campo de arroz", "kana": "たんぼ", "kanji": "田んぼ" },
        { "spanish": "campo de arroz", "kana": "すいでん", "kanji": "水田" },
        { "spanish": "atardecer", "kana": "ゆうがた", "kanji": "夕がた" },
        { "spanish": "cena", "kana": "ゆうごはん", "kanji": "夕ごはん" },
        { "spanish": "puesta de sol", "kana": "ゆうひ", "kanji": "夕日" },
        { "spanish": "tiempo", "kana": "てんき", "kanji": "天気" },
        { "spanish": "genio", "kana": "てんさい", "kanji": "天さい" },
        { "spanish": "cielo", "kana": "てんごく", "kanji": "天国" },
        { "spanish": "angel", "kana": "てんし", "kanji": "天し" },
        { "spanish": "cielo azul", "kana": "あおいそら", "kanji": "青い空" },
        { "spanish": "aire", "kana": "くうき", "kanji": "空気" },
        { "spanish": "aeropuerto", "kana": "くうこう", "kanji": "空こう" },
        { "spanish": "karate", "kana": "からて", "kanji": "空手" },
        { "spanish": "llover", "kana": "あめがふります", "kanji": "雨がふります" },
        { "spanish": "tiempo lluvioso", "kana": "うてん", "kanji": "雨天" },
        { "spanish": "salida este", "kana": "ひがしぐち", "kanji": "東口" },
        { "spanish": "Tokyo", "kana": "とうきょう", "kanji": "東京" },
        { "spanish": "oriente", "kana": "とうよう", "kanji": "東よう" },
        { "spanish": "salida oeste", "kana": "にしぐち", "kanji": "西口" },
        { "spanish": "Kansai", "kana": "かんさい", "kanji": "かん西" },
        { "spanish": "occidente", "kana": "せいよう", "kanji": "西よう" },
        { "spanish": "América del Sur", "kana": "みなみアメリカ", "kanji": "南アメリカ" },
        { "spanish": "Asia", "kana": "とうなん", "kanji": "東南" },
        { "spanish": "Antártico", "kana": "なんきょく", "kanji": "南きょく" },
        { "spanish": "Sudamérica", "kana": "なんべい", "kanji": "南べい" },
        { "spanish": "Hokkaido", "kana": "ほっかいどう", "kanji": "北かい道" },
        { "spanish": "Ártico", "kana": "ほっきょく", "kanji": "北きょく" },
    ],

    "kanji_day_4": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_5": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_6": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_7": [
        { "spanish": "todos los días", "kana": "まいにち", "kanji": "毎日" },
        { "spanish": "todos los meses", "kana": "まいつき", "kanji": "毎月" },
        { "spanish": "todas las mañanas", "kana": "まいあさ", "kanji": "毎あさ" },
        { "spanish": "a veces", "kana": "ときどき", "kanji": "時どき" },
        { "spanish": "reloj", "kana": "とけい", "kanji": "時けい" },
        { "spanish": "tiempo", "kana": "じかん", "kanji": "時間" },
        { "spanish": "entender", "kana": "わかる", "kanji": "分かる" },
        { "spanish": "dividir", "kana": "わける", "kanji": "分ける" },
        { "spanish": "cuantos minutos", "kana": "なんふん", "kanji": "何分" },
        { "spanish": "quizás", "kana": "たぶん", "kanji": "た分" },
        { "spanish": "medio año", "kana": "はんとし", "kanji": "半年" },
        { "spanish": "medio día", "kana": "はんにち", "kanji": "半日" },
        { "spanish": "manga corta", "kana": "はんそで", "kanji": "半そで" },
        { "spanish": "país", "kana": "くに", "kanji": "国" },
        { "spanish": "rey", "kana": "こくおう", "kanji": "国おう" },
        { "spanish": "China", "kana": "ちゅうごく", "kanji": "中国" },
        { "spanish": "extranjero", "kana": "がいこくじん", "kanji": "外国人" },
        { "spanish": "diccionario", "kana": "じしょ", "kanji": "じ書" },
        { "spanish": "biblioteca", "kana": "としょかん", "kanji": "と書かん" },
        { "spanish": "caligrafía", "kana": "しょどう", "kanji": "書どう" },
        { "spanish": "libro de texto", "kana": "きょうかしょ", "kanji": "きょうか書" },
        { "spanish": "amigo", "kana": "ともだち", "kanji": "友だち" },
        { "spanish": "amigo desde niños", "kana": "ママとも", "kanji": "ママ友" },
        { "spanish": "amigo", "kana": "ゆうじん", "kanji": "友人" },
        { "spanish": "hoy", "kana": "きょう", "kanji": "今日" },
        { "spanish": "siguiente vez", "kana": "こんど", "kanji": "今ど" },
        { "spanish": "este mes", "kana": "こんげつ", "kanji": "今月" },
        { "spanish": "este año", "kana": "ことし", "kanji": "今年" },
        { "spanish": "buenas tardes", "kana": "こんにちは", "kanji": "今日は" },
        { "spanish": "esta semana", "kana": "こんしゅう", "kanji": "今週" },
        { "spanish": "semana pasada", "kana": "せんしゅう", "kanji": "先週" },
        { "spanish": "semana que viene", "kana": "らいしゅう", "kanji": "来週" },
        { "spanish": "fin de semana", "kana": "しゅうまつ", "kanji": "週まつ" },
        { "spanish": "vacaciones de verano", "kana": "なつやすみ", "kanji": "なつ休み" },
        { "spanish": "días de descanso", "kana": "きゅうじつ", "kanji": "休日" },
        { "spanish": "descanso", "kana": "きゅうけい", "kanji": "休けい" },
    ],

    "kanji_day_8": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_9": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_10": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],
    
    "kanji_day_11": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ]
};