const kanjiwordscustom_json = {
    "kanji_day_1": [
        { "spanish": ["vivir", "residir"], "kana": "すむ", "kanji": "住む" },
        { "spanish": "lugar", "kana": "ところ", "kanji": "所" },
        { "spanish": "tokio", "kana": "とうきょう", "kanji": "東京" },
        { "spanish": ["brillante", "claro"], "kana": "あかるい", "kanji": "明るい" },
        { "spanish": ["conveniente", "útil"], "kana": "べんり", "kanji": "便利" },
        { "spanish": "especial", "kana": "とくべつ", "kanji": "特別" },
        { "spanish": "trabajar", "kana": "はたらく", "kanji": "働く" },
        { "spanish": "escuela", "kana": "がっこう", "kanji": "学校" },
    ],
    "kanji_day_2": [
        { "spanish": ["residente", "habitante"], "kana": "じゅうみん", "kanji": "住民" },
        { "spanish": ["lugar", "ubicación"], "kana": "ばしょ", "kanji": "場所" },
        { "spanish": ["conveniencia", "circunstancias"], "kana": "つごう", "kanji": "都合" },
        { "spanish": "mañana", "kana": "あした", "kanji": "明日" },
        { "spanish": "tren exprés", "kana": "とっきゅう", "kanji": "特急" },
        { "spanish": ["conveniente", "útil"], "kana": "べんり", "kanji": "便利" },
        { "spanish": "trabajar", "kana": "はたらく", "kanji": "働く" },
        { "spanish": "película", "kana": "えいが", "kanji": "映画" },
    ],
    "kanji_day_3": [
        { "spanish": "ciudadano", "kana": "しみん", "kanji": "市民" },
        { "spanish": ["distinción", "diferencia"], "kana": "くべつ", "kanji": "区別" },
        { "spanish": "administrado por la prefectura", "kana": "ふりつ", "kanji": "府立" },
        { "spanish": "dentro de la prefectura", "kana": "けんない", "kanji": "県内" },
        { "spanish": "comida ligera", "kana": "けいしょく", "kanji": "軽食" },
        { "spanish": ["tren rápido", "prisa"], "kana": "きゅうこう", "kanji": "急行" },
        { "spanish": "empeoramiento", "kana": "あっか", "kanji": "悪化" },
        { "spanish": "posada japonesa", "kana": "りょかん", "kanji": "旅館" },
    ],
    "kanji_day_4": [
        { "spanish": "centro de la ciudad", "kana": "としん", "kanji": "都心" },
        { "spanish": "alcalde", "kana": "しちょう", "kanji": "市長" },
        { "spanish": ["sección", "división"], "kana": "くかく", "kanji": "区画" },
        { "spanish": ["fuerte", "poderoso"], "kana": "きょうりょく", "kanji": "強力" },
        { "spanish": ["artesanía", "trabajo manual"], "kana": "さいく", "kanji": "細工" },
        { "spanish": "música", "kana": "おんがく", "kanji": "音楽" },
        { "spanish": ["boceto", "dibujo"], "kana": "しゃせい", "kanji": "写生" },
        { "spanish": "industria", "kana": "さんぎょう", "kanji": "産業" },
    ],
    "kanji_day_5": [
        { "spanish": "ciudad metropolitana", "kana": "とかい", "kanji": "都会" },
        { "spanish": "alcalde de una aldea", "kana": "そんちょう", "kanji": "村長" },
        { "spanish": ["claro", "evidente"], "kana": "めいはく", "kanji": "明白" },
        { "spanish": "sonido agudo", "kana": "こうおん", "kanji": "高音" },
        { "spanish": ["venta especial", "oferta"], "kana": "とくばい", "kanji": "特売" },
        { "spanish": "año nuevo", "kana": "しんねん", "kanji": "新年" },
        { "spanish": "empleado de tienda", "kana": "てんいん", "kanji": "店員" },
        { "spanish": "viaje", "kana": "りょこう", "kanji": "旅行" },
    ],
    "kanji_day_6": [
        { "spanish": "por cierto", "kana": "ところで", "kanji": "所で" },
        { "spanish": ["saludable", "energético"], "kana": "げんきな", "kanji": "元気な" },
        { "spanish": "empresa de videojuegos", "kana": "ゲームがいしゃ", "kanji": "ゲーム会社" },
        { "spanish": "tienda", "kana": "おみせ", "kanji": "お店" },
        { "spanish": "ciudad grande", "kana": "おおきいまち", "kanji": "大きい町" },
        { "spanish": "bebé", "kana": "あかちゃん", "kanji": "赤ちゃん" },
        { "spanish": "tomar el tren", "kana": "でんしゃにのる", "kanji": "電車に乗る" },
        { "spanish": "desayuno", "kana": "あさごはん", "kanji": "朝ごはん" },
    ],
    "kanji_day_7": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],
    "kanji_day_8": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],
    "kanji_day_9": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],
    "kanji_day_10": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],
    "kanji_day_11": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ]
};