const kanjij3words_json = {
    "kanji_day_1": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_2": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_3": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_4": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_5": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_6": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_7": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_8": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_9": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],

    "kanji_day_10": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ],
    
    "kanji_day_11": [
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
        { "spanish": "", "kana": "", "kanji": "" },
    ]
};