const lessonsj3j4_json = {
    "lesson_26": [
        { "spanish": ["ver", "mirar", "observar", "revisar", "inspeccionar", "examinar", "evaluar"], "kana": ["みます", "見ます", "診ます"] },
        { "spanish": "buscar", "kana": ["さがします", "探します", "捜します"] },
        { "spanish": ["retrasarse", "llegar tarde"], "kana": ["おくれます", "遅れます"] },
        { "spanish": "llegar a tiempo", "kana": ["まにあいます", "間に合います"] },
        { "spanish": "hacer", "kana": "やります" },
        { "spanish": ["coger", "recoger"], "kana": ["ひろいます", "拾います"] },
        { "spanish": ["avisar", "comunicar", "ponerse en contacto"], "kana": ["れんらくします", "連絡します"] },
        { "spanish": ["sentirse bien", "sentirse sano"], "kana": ["きぶんがいい", "気分がいい"] },
        { "spanish": ["sentirse enfermo", "sentirse mal"], "kana": ["きぶんがわるい", "気分が悪い"] },
        { "spanish": ["evento deportivo", "fiesta deportiva"], "kana": ["うんどうかい", "運動会"] },
        { "spanish": "baile de la fiesta Bon", "kana": ["ぼんおどり", "盆踊り"] },
        { "spanish": "mercadillo", "kana": "フリーマーケット" },
        { "spanish": ["lugar", "ubicación", "posición"], "kana": ["ばしょ", "場所"] },
        { "spanish": "voluntariado", "kana": "ボランティア" },
        { "spanish": ["cartera", "monedero"], "kana": ["さいふ", "財布"] },
        { "spanish": ["basura", "desperdicios"], "kana": "ごみ" },
        { "spanish": ["Palacio de Dieta", "parlamento"], "kana": ["こっかいぎじどう", "国会議事堂"] },
        { "spanish": "días laborables", "kana": ["へいじつ", "平日"] },
        { "spanish": "dialecto de", "kana": ["～べん", "～弁"] },
        { "spanish": "la próxima vez", "kana": ["こんど", "今度"] },
        { "spanish": ["muy", "bastante"], "kana": "ずいぶん" },
        { "spanish": ["directo", "inmediato", "personal", "de primera mano"], "kana": ["ちょくせつ", "直接"] },
        { "spanish": ["a cualquier hora", "en cualquier momento"], "kana": "いつでも" },
        { "spanish": ["en cualquier sitio", "dondequiera"], "kana": "どこでも" },
        { "spanish": "cualquier persona", "kana": ["だれでも", "誰でも"] },
        { "spanish": "cualquier cosa", "kana": ["なんでも", "何でも"] },
        { "spanish": ["como este", "tal"], "kana": "こんな～" },
        { "spanish": ["como ese", "como esa", "tal"], "kana": "そんな～" },
        { "spanish": "como aquel", "kana": "あんな～" },
        { "spanish": ["universo", "espacio"], "kana": ["うちゅう", "宇宙"] },
        { "spanish": ["sra", "señora"], "kana": ["～さま", "～様"] },
        { "spanish": ["nave espacial", "astro nave"], "kana": ["うちゅうせん", "宇宙船"] },
        { "spanish": "tener miedo a", "kana": ["こわい", "怖い"] },
        { "spanish": "estación espacial", "kana": ["うちゅうステーション", "宇宙ステーション"] },
        { "spanish": "ser diferente", "kana": ["ちがいます", "違います"] },
        { "spanish": "astronauta", "kana": ["うちゅうひこうし", "宇宙飛行士"] },

        { "spanish": "avería", "kana": "こしょう" },
        { "spanish": "conveniencia", "kana": "つごう" },
        { "spanish": ["me viene mal", "inconveniente"], "kana": "つごうがわるい" },
        { "spanish": ["me viene bien", "conveniente"], "kana": "つごうがいい" },
        { "spanish": "basurero de barrio", "kana": "ごみおきば" },
        { "spanish": "quemar", "kana": "もえます" },
        { "spanish": "vidrio", "kana": "びん" }
    ],



    "lesson_27": [
        { "spanish": ["tener", "criar"], "kana": ["かう", "飼う"] },
        { "spanish": "correr", "kana": ["はしる", "走る"] },
        { "spanish": "verse", "kana": ["みえる", "見える"] },
        { "spanish": "oírse", "kana": ["きこえる", "聞こえる"] },
        { "spanish": ["fundarse", "contruirse", "hacerse", "estar lista"], "kana": "できる" },
        { "spanish": ["organizar", "celebrar", "realizar"], "kana": ["ひらく", "開く"] },
        { "spanish": "preocupado", "kana": ["しんぱい", "心配"] },
        { "spanish": "mascota", "kana": "ペット" },
        { "spanish": ["pájaro", "ave"], "kana": ["とり", "鳥"] },
        { "spanish": ["voz", "canto"], "kana": ["こえ", "声"] },
        { "spanish": ["ola", "onda"], "kana": ["なみ", "波"] },
        { "spanish": "fuegos artificiales", "kana": ["はなび", "花火"] },
        { "spanish": ["herramienta", "instrumento", "equipo"], "kana": ["どうぐ", "道具"] },
        { "spanish": "lavado en seco", "kana": "クリーニング" },
        { "spanish": ["casa", "piso", "departamento"], "kana": ["いえ", "家"] },
        { "spanish": ["condominio", "edificio de pisos", "edificio de apartamentos"], "kana": "マンション" },
        { "spanish": "cocina", "kana": "キッチン" },
        { "spanish": "clase de", "kana": ["きょうしつ", "教室"] },
        { "spanish": "sala de fiestas", "kana": "パーチールーム" },
        { "spanish": "persona", "kana": ["かた", "方"] },
        { "spanish": "después de", "kana": ["ご", "後"] },
        { "spanish": ["no más que", "solamente"], "kana": "しか" },
        { "spanish": "otro", "kana": "ほかの" },
        { "spanish": "claramente", "kana": "はっきり" },
        { "spanish": "muebles", "kana": ["かぐ", "家具"] },
        { "spanish": ["estantería", "estante"], "kana": ["ほんだな", "本棚"] },
        { "spanish": "algún día", "kana": "いつか" },
        { "spanish": "construir", "kana": ["たてます", "立てます"] },
        { "spanish": "maravilloso", "kana": "すばらしい" },
        { "spanish": "niños", "kana": ["こどもたち", "子供たち"] },
        { "spanish": ["favorito", "preferido"], "kana": ["だいすき", "大好き"] },
        { "spanish": ["protagonista", "personaje principal"], "kana": ["しゅじんこう", "主人公"] },
        { "spanish": "forma", "kana": ["かたち", "形"] },
        { "spanish": ["fantástico", "mágico", "extraño", "misterioso"], "kana": ["ふしぎ", "不思議"] },
        { "spanish": "bolsillo", "kana": "ポケット" },
        { "spanish": "por ejemplo", "kana": ["たとえば", "例えば"] },
        { "spanish": "poner", "kana": ["つけます", "付けます"] },
        { "spanish": "libremente", "kana": ["じゆうに", "自由に"] },
        { "spanish": "cielo", "kana": ["そら", "空"] },
        { "spanish": "volar", "kana": ["とびます", "飛びます"] },
        { "spanish": ["en el pasado", "antiguamente"], "kana": ["むかし", "昔"] },
        { "spanish": ["mí mismo", "tí mismo", "sí mismo"], "kana": ["じぶん", "自分"] },
        { "spanish": "futuro", "kana": ["しょうらい", "将来"] },
    ],



    "lesson_28": [
        { "spanish": "venderse", "kana": ["売れます", "うれます"] },
        { "spanish": "bailar", "kana": ["踊ります", "おどります"] },
        { "spanish": ["masticar", "morder"], "kana": "かみます" },
        { "spanish": ["elegir", "escoger"], "kana": ["選びます", "えらびます"] },
        { "spanish": ["ir", "frecuentar"], "kana": ["通います", "かよいます"] },
        { "spanish": ["anotar", "tomar notas"], "kana": "メモします" },
        { "spanish": "serio", "kana": "まじめ" },
        { "spanish": ["entusiasmado", "diligente"], "kana": ["熱心「な」", "ねっしん「な」"] },
        { "spanish": ["respetable", "admirable"], "kana": "えらい" },
        { "spanish": ["venir bien", "venir justo", "ser apropiado"], "kana": "ちょうどいい" },
        { "spanish": "paisaje", "kana": ["景色", "けしき"] },
        { "spanish": ["salón de belleza", "peluquería"], "kana": ["美容院", "びよういん"] },
        { "spanish": "cocina", "kana": ["台所", "だいどころ"] },
        { "spanish": ["experiencia", "vivir experiencia"], "kana": ["経験", "けいけん"] },
        { "spanish": "fuerza", "kana": ["力", "ちから"] },
        { "spanish": "popularidad", "kana": ["人気", "にんき"] },
        { "spanish": ["forma", "figura"], "kana": ["形", "かたち"] },
        { "spanish": "color", "kana": ["色", "いろ"] },
        { "spanish": "sabor", "kana": ["味", "あじ"] },
        { "spanish": "chicle", "kana": "がむ" },
        { "spanish": ["bienes", "artículos", "mercancías", "productos"], "kana": ["品物", "しなもの"] },
        { "spanish": "precio", "kana": ["値段", "ねだん"] },
        { "spanish": ["sueldo", "salario"], "kana": ["給料", "きゅうりょう"] },
        { "spanish": ["paga extra", "gratificación", "prima", "bonificación"], "kana": "ボーナス" },
        { "spanish": ["juego", "videojuego"], "kana": "ゲーム" },
        { "spanish": "programa", "kana": ["番組", "ばんぐみ"] },
        { "spanish": ["drama", "serie de televisión"], "kana": "ドラマ" },
        { "spanish": "cantante", "kana": ["歌手", "かしゅ"] },
        { "spanish": "novela", "kana": ["小説", "しょうせつ"] },
        { "spanish": "novelista", "kana": ["小説家", "しょうせつか"] },
        { "spanish": "experto en", "kana": ["～家", "～か"] },
        { "spanish": "máquina", "kana": ["～機", "～き"] },
        { "spanish": "hijo", "kana": ["息子", "むすこ"] },
        { "spanish": "hija", "kana": ["娘", "むすめ"] },
        { "spanish": ["el propio", "mí mismo", "ti mismo", "sí mismo"], "kana": ["自分", "じぶん"] },
        { "spanish": "vida futura", "kana": ["将来", "しょうらい"] },
        { "spanish": ["por un tiempo", "por un rato"], "kana": "しばらく" },
        { "spanish": ["habitualmente", "casi siempre"], "kana": "たいてい" },
        { "spanish": "además", "kana": "それに" },
        { "spanish": ["por eso", "por lo tanto"], "kana": "それで" },
        { "spanish": "aviso", "kana": ["お知らせ", "おしらせ"] },
        { "spanish": "participar", "kana": ["参加します", "さんかします"] },
        { "spanish": "fecha", "kana": ["日にち", "ひにち"] },
        { "spanish": "sábado", "kana": ["土", "ど"] },
        { "spanish": "gimnasio escolar", "kana": ["体育館", "たいいくかん"] },
        { "spanish": "gratis", "kana": ["無料", "むりょう"] },
        { "spanish": "invitar", "kana": ["誘います", "さそいます"] },
        { "spanish": "evento", "kana": "イベント" },

        { "spanish": ["producto manufacturado", "producto en fábrica"], "kana": "せいひん" }
    ],



    "lesson_29": [
        { "spanish": "abrirse", "kana": ["開きます", "あきます"] },
        { "spanish": "cerrarse", "kana": ["閉まります", "しまります"] },
        { "spanish": "encenderse", "kana": ["点きます", "つきます"] },
        { "spanish": ["apagarse", "desvanecerse", "desaparecerse"], "kana": ["消えます", "きえます"] },
        { "spanish": ["descomponerse", "romperse"], "kana": ["壊れます", "こわれます"] },
        { "spanish": ["romperse", "quebrarse", "agrietarse"], "kana": ["割れます", "われます"] },
        { "spanish": ["romperse", "quebrarse", "partirse"], "kana": ["折れます", "おれます"] },
        { "spanish": ["romperse", "rasgarse", "desgarrarse", "desgastarse"], "kana": ["破れます", "やぶれます"] },
        { "spanish": "ensuciarse", "kana": ["汚れます", "よごれます"] },
        { "spanish": ["ser puesto", "poner"], "kana": ["付きます", "つきます"] },
        { "spanish": ["desconectarse", "salirse de su lugar", "desbotonarse"], "kana": ["外れます", "はずれます"] },
        { "spanish": ["detenerse", "pararse", "suspenderse"], "kana": ["止まります", "とまります"] },
        { "spanish": "cerrarse", "kana": "かかります" },
        { "spanish": "equivocarse", "kana": ["間違えます", "まちがえます"] },
        { "spanish": "perder", "kana": ["落とします", "おとします"] },
        { "spanish": "limpiar", "kana": ["拭きます", "ふきます"] },
        { "spanish": ["cambiar", "sustituir", "reemplazar"], "kana": ["取り替えます", "とりかえます"] },
        { "spanish": "ordenar", "kana": ["片付けます", "かたづけます"] },
        { "spanish": "plato", "kana": ["皿", "さら"] },
        { "spanish": ["taza", "cuenco"], "kana": ["茶碗", "ちゃわん"] },
        { "spanish": "vaso", "kana": "コップ" },
        { "spanish": ["vidrio", "cristal"], "kana": "ガラス" },
        { "spanish": "bolsa", "kana": ["袋", "ふくろ"] },
        { "spanish": ["papel", "documento"], "kana": ["書類", "しょるい"] },
        { "spanish": "rama de árbol", "kana": ["枝", "えだ"] },
        { "spanish": "empleado de estación", "kana": ["駅員", "えきいん"] },
        { "spanish": "puesto de policía", "kana": ["交番", "こうばん"] },
        { "spanish": "discurso", "kana": "スピーチ" },
        { "spanish": "respuesta", "kana": ["返事", "へんじ"] },
        { "spanish": ["adelante, por favor", "pase usted"], "kana": ["お先にどうぞ", "おさきにどうぞ"] },
        { "spanish": "terremoto", "kana": ["地震", "じしん"] },
        { "spanish": "pared", "kana": ["壁", "かべ"] },
        { "spanish": ["manecilla", "aguja", "puntero"], "kana": ["針", "はり"] },
        { "spanish": ["apuntar", "indicar"], "kana": ["指します", "さします"] },
        { "spanish": "frente a la estación", "kana": ["駅前", "えきまえ"] },
        { "spanish": ["caerse", "derrumbarse"], "kana": ["倒れます", "たおれます"] },
        { "spanish": "oeste", "kana": ["西", "にし"] },
        { "spanish": ["en la parte de", "en dirección a", "rumbo a", "hacia"], "kana": ["の方", "のほう"] },
        { "spanish": "quemarse", "kana": ["燃えます", "もえます"] },
        { "spanish": "reportero", "kana": "レポータ" },

        { "spanish": "capítulo", "kana": ["話", "わ"] },
        { "spanish": "pedir", "kana": "たのみます" },
        { "spanish": "puente festivo", "kana": ["連休", "れんきゅう"] },
        { "spanish": "cremallera", "kana": "チャック" },
        { "spanish": "tener la cremallera abierta", "kana": "チャックがおいています" },
        { "spanish": "pelo de la nariz", "kana": "はなげ" },
        { "spanish": "moco", "kana": "はなクソ" },
        { "spanish": "sobre", "kana": "ふうと" },
        { "spanish": "rejilla", "kana": "あみだな" },
        { "spanish": "exterior", "kana": ["外側", "そとがわ"] }
    ],



    "lesson_30": [
        { "spanish": ["pegar", "fijar"], "kana": ["はる", "張る"] },
        { "spanish": "colgar", "kana": ["かける", "掛ける"] },
        { "spanish": ["adornar", "decorar"], "kana": ["さがる", "飾る"] },
        { "spanish": ["poner en fila", "colocar", "enfilar"], "kana": ["ならべる", "並べる"] },
        { "spanish": "plantar", "kana": ["うえる", "植える"] },
        { "spanish": ["devolver", "reponer"], "kana": ["もどす", "戻す"] },
        { "spanish": ["reunir", "juntar", "resumir", "compilar"], "kana": ["まとめる", "纏める"] },
        { "spanish": ["poner en su lugar", "guardar"], "kana": ["しまう", "仕舞う"] },
        { "spanish": ["determinar", "decidir"], "kana": ["きめる", "決める"] },
        { "spanish": "preparar la lección", "kana": ["よしゅうする", "予習する"] },
        { "spanish": "repasar la lección", "kana": ["ふくしゅうする", "復習する"] },
        { "spanish": "dejar las cosas como están", "kana": ["そのままにする", "其の儘にする"] },
        { "spanish": "clase", "kana": ["じゅぎょう", "授業"] },
        { "spanish": ["conferencia", "clase"], "kana": ["こうぎ", "講義"] },
        { "spanish": "reunión", "kana": "ミーチング" },
        { "spanish": ["plan", "programa"], "kana": ["よてい", "予定"] },
        { "spanish": "aviso", "kana": ["おしらせ", "お知らせ"] },
        { "spanish": "guía", "kana": "ガイドブック" },
        { "spanish": "calendario", "kana": "カレンダー" },
        { "spanish": ["cartel", "letrero", "póster"], "kana": "ポスター" },
        { "spanish": ["programa", "horario", "agenda"], "kana": ["よていひょう", "予定表"] },
        { "spanish": ["papelera", "cubo de basura"], "kana": ["ごみばこ", "ごみ箱"] },
        { "spanish": "muñeca", "kana": ["にんぎょう", "人形"] },
        { "spanish": "florero", "kana": ["かびん", "花瓶"] },
        { "spanish": "espejo", "kana": ["かがみ", "鏡"] },
        { "spanish": "cajón", "kana": ["ひきだし", "引き出し"] },
        { "spanish": ["vestíbulo", "entrada"], "kana": ["げんかん", "玄関"] },
        { "spanish": ["pasillo", "corredor"], "kana": ["ろうか", "廊下"] },
        { "spanish": "pared", "kana": ["かべ", "壁"] },
        { "spanish": ["charca", "laguna", "estanque"], "kana": ["いけ", "池"] },
        { "spanish": ["lugar original", "donde estaba"], "kana": ["もとのところ", "元の所"] },
        { "spanish": "alrededor", "kana": ["まわり", "周り"] },
        { "spanish": "centro", "kana": ["まんなか", "真ん中"] },
        { "spanish": ["rincón", "esquina"], "kana": ["すみ", "隅"] },
        { "spanish": "todavía", "kana": "まだ" },
        { "spanish": "mochila", "kana": "リュック" },
        { "spanish": "bolsa para emergencias", "kana": ["ひじょうぶくろ", "非常袋"] },
        { "spanish": "caso de emergencia", "kana": ["ひじょうじ", "非常時"] },
        { "spanish": ["subsistir", "vivir"], "kana": ["せいかつします", "生活します"] },
        { "spanish": "linterna", "kana": ["かいちゅうでんとう", "懐中電灯"] },
        { "spanish": "etc", "kana": "とか" },
        { "spanish": "redondo", "kana": ["まるい", "丸い"] },
        { "spanish": "un cierto", "kana": "ある" },
        { "spanish": "soñar", "kana": ["ゆめをみます", "夢を見ます"] },
        { "spanish": ["feliz", "alegre", "contento"], "kana": "うれしい" },
        { "spanish": ["desagradable", "molesto", "detestable"], "kana": ["いや", "嫌"] },
        { "spanish": ["y", "entonces"], "kana": "すると" },
        { "spanish": "despertarse", "kana": ["めがさめます", "目が覚めます"] },
    ],



    "lesson_31": [
        { "spanish": ["continuar", "seguir"], "kana": ["つづける", "続ける"] },
        { "spanish": "encontrar", "kana": ["みつける", "見つける"] },
        { "spanish": ["obtener", "tomar", "tomarse"], "kana": ["とる", "取る"] },
        { "spanish": "presentarse", "kana": ["うける", "受ける"] },
        { "spanish": ["inscribirse", "pedir", "subscribir"], "kana": ["もうしこむ", "申し込む"] },
        { "spanish": ["descansar", "tomar un descanso"], "kana": ["きゅうけいする", "休憩する"] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
    ],



    "lesson_32": [
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
    ],



    "lesson_33": [
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
    ],



    "lesson_34": [
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
    ],



    "lesson_35": [
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
    ],



    "lesson_36": [
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
        { "spanish": "", "kana": ["", ""] },
    ],

    

    "verbos": [
        { "spanish": "levantarse", "kana": ["おきる", "起きる"] },
        { "spanish": ["acostarse", "ir a la cama"], "kana": ["ねる", "寝る"] },
        { "spanish": "trabajar", "kana": ["はたらく", "働く"] },
        { "spanish": ["descansar", "estar de vacaciones", "ausentarse", "faltar"], "kana": ["やすむ", "休む"] },
        { "spanish": "estudiar", "kana": ["べんきょうする", "勉強する"] },
        { "spanish": "terminar", "kana": ["おわる", "終わる"] },
        { "spanish": "ir", "kana": ["いく", "行く"] },
        { "spanish": "vivir", "kana": ["いきる", "生きる"] },
        { "spanish": "venir", "kana": ["くる", "来る"] },
        { "spanish": "volver, regresar, irse a casa", "kana": ["かえる", "帰る"] },
        { "spanish": "comer", "kana": ["たべる", "食べる"] },
        { "spanish": ["beber", "tomar"], "kana": ["のむ", "飲む"] },
        { "spanish": "fumar", "kana": ["すう", "吸う"] },
        { "spanish": ["ver", "mirar"], "kana": ["みる", "見る"] },
        { "spanish": ["oír", "escuchar", "preguntar"], "kana": ["きく", "聞く"] },
        { "spanish": "leer", "kana": ["よむ", "読む"] },
        { "spanish": ["escribir", "dibujar"], "kana": ["かく", "書く"] },
        { "spanish": "comprar", "kana": ["かう", "買う"] },
        { "spanish": "sacar fotos", "kana": ["しゃしんをとる", "取る"] },
        { "spanish": "hacer", "kana": "する" },
        { "spanish": ["ver a", "encontrarse con"], "kana": ["あう", "会う"] },
        { "spanish": "cortar", "kana": ["きる", "切る"] },
        { "spanish": "recibir", "kana": ["もらう", "貰う"] },
        { "spanish": "prestar", "kana": ["かす", "貸す"] },
        { "spanish": "tomar prestado", "kana": ["かりる", "借りる"] },
        { "spanish": "enseñar", "kana": ["おしえる", "教える"] },
        { "spanish": "aprender", "kana": ["ならう", "習う"] },
        { "spanish": ["hacer una llamada", "llamar"], "kana": ["でんわをかける", "でんわを掛ける"] },
        { "spanish": ["entender", "comprender"], "kana": ["わかる", "分かる"] },
        { "spanish": ["estar", "haber", "existir"], "kana": ["ある", "有る"] },
        { "spanish": ["estar", "haber", "existir", "permanecer"], "kana": ["いる", "居る"] },
        { "spanish": ["montar", "subir"], "kana": ["のる", "乗る"] },
        { "spanish": "pasear", "kana": ["さんぽをする", "散歩をする"] },
        { "spanish": "tener hijos", "kana": ["こどもがいる", "子供がが居る"] },
        { "spanish": ["tardar", "costar"], "kana": ["かかる", "掛かる"] },
        { "spanish": "hacer encuesta", "kana": "アンケートする" },
        { "spanish": ["votar", "emitir un voto"], "kana": ["とうひょうする", "投票する"] },
        { "spanish": ["luchar contra una enfermedad", "combatir una enfermedad"], "kana": ["とうびょうする", "闘病する"] },
        { "spanish": ["jugar", "divertirse"], "kana": ["あそぶ", "遊ぶ"] },
        { "spanish": "nadar", "kana": ["およぐ", "泳ぐ"] },
        { "spanish": ["recoger", "recibir"], "kana": ["むかえる", "迎える"] },
        { "spanish": ["cansarse", "estar cansado"], "kana": ["つかれる", "疲れる"] },
        { "spanish": "casarse", "kana": ["けっこんする", "結婚する"] },
        { "spanish": "hacer compras", "kana": ["かいものする", "買い物する"] },
        { "spanish": "comer", "kana": ["しょくじする", "食事する"] },
        { "spanish": "pescar", "kana": ["つりをする", "釣りをする"] },
        { "spanish": "esquiar", "kana": ["スキーをする", "スキーをする"] },
        { "spanish": "secar", "kana": ["かわく", "乾く"] },
        { "spanish": "estar vacío", "kana": ["すく", "空く"] },
        { "spanish": ["recoger", "recibir", "aceptar"], "kana": ["うけとる", "受け取る"] },
        { "spanish": "pagar", "kana": ["はらう", "払う"] },
        { "spanish": "esperar", "kana": ["まつ", "待つ"] },
        { "spanish": "encender", "kana": ["つける", "付ける"] },
        { "spanish": "apagar", "kana": ["けす", "消す"] },
        { "spanish": "abrir", "kana": ["あける", "開ける"] },
        { "spanish": "cerrar", "kana": ["しめる", "締める"] },
        { "spanish": ["apresurarse", "darse prisa"], "kana": ["いそぐ", "急ぐ"] },
        { "spanish": ["tener algo en la mano", "tomar"], "kana": ["もつ", "持つ"] },
        { "spanish": ["pasar", "dar"], "kana": ["とる", "取る"] },
        { "spanish": "ayudar", "kana": ["てつだう", "手伝う"] },
        { "spanish": "llamar", "kana": ["よぶ", "呼ぶ"] },
        { "spanish": "hablar", "kana": ["はなす", "話す"] },
        { "spanish": "usar", "kana": ["つかう", "使う"] },
        { "spanish": ["parar", "estacionar"], "kana": ["とめる", "止める"] },
        { "spanish": ["mostrar", "enseñar"], "kana": ["みせる", "見せる"] },
        { "spanish": "sentarse", "kana": ["すわる", "座る"] },
        { "spanish": "ponerse de pie", "kana": ["たつ", "立つ"] },
        { "spanish": "salir", "kana": ["でる", "出る"] },
        { "spanish": "llover", "kana": ["あめがふる", "雨が降る"] },
        { "spanish": "sacar fotocopias", "kana": "コピーする" },
        { "spanish": "explicar", "kana": ["せつめいする", "説明する"] },
        { "spanish": "girar", "kana": ["まわる", "回る"] },
        { "spanish": "reservar", "kana": ["よやくする", "予約する"] },
        { "spanish": "lavar", "kana": ["あらう", "洗う"] },
        { "spanish": ["poner", "colocar"], "kana": ["おく", "置く"] },
        { "spanish": ["crear", "hacer", "producir"], "kana": ["つくる", "作る"] },
        { "spanish": "vender", "kana": ["うる", "売る"] },
        { "spanish": ["enterarse", "saber", "conocer"], "kana": ["しる", "知る"] },
        { "spanish": ["vivir", "residir"], "kana": ["すむ", "住む"] },
        { "spanish": "investigar", "kana": ["けんきゅうする", "研究する"] },
        { "spanish": ["recordar", "acordarse"], "kana": ["おもいだす", "思い出す"] },
        { "spanish": ["jubilado", "renunciar"], "kana": ["たいしょくする", "退職する"] },
        { "spanish": "subir", "kana": ["でんしゃにのる", "電車に乗る"] },
        { "spanish": "bajar", "kana": ["でんしゃをおりる", "電車を降りる"] },
        { "spanish": ["trasbordo", "transbordo"], "kana": ["のりかえる", "乗り換える"] },
        { "spanish": "ducharse", "kana": ["シャワーをあびる", "シャワーを浴びる"] },
        { "spanish": ["meter", "introducir", "insertar"], "kana": ["いれる", "入れる"] },
        { "spanish": ["sacar", "entregar", "presentar", "enviar"], "kana": ["だす", "出す"] },
        { "spanish": ["retirar", "sacar"], "kana": ["おろす", "下ろす"] },
        { "spanish": ["entrar", "ingresar"], "kana": ["はいる", "入る"] },
        { "spanish": "graduarse", "kana": ["だいがくをでる", "大学を出る"] },
        { "spanish": ["presionar", "empujar", "pulsar"], "kana": ["おす", "押す"] },
        { "spanish": ["empezar", "comenzar", "iniciar"], "kana": ["はじめる", "始める"] },
        { "spanish": "visitar", "kana": ["けんがくする", "見学する"] },
        { "spanish": ["llamar por teléfono", "telefonear"], "kana": ["でんわする", "電話する"] },
        { "spanish": "memorizar", "kana": ["おぼえる", "覚える"] },
        { "spanish": "olvidar", "kana": ["わすれる", "忘れる"] },
        { "spanish": "perder", "kana": ["なくす", "無くす"] },
        { "spanish": "devolver", "kana": ["かえす", "返す"] },
        { "spanish": ["salir", "ir", "venir", "volver"], "kana": ["でかける", "出かける"] },
        { "spanish": ["quitarse", "desvestirse"], "kana": ["ぬぐ", "脱ぐ"] },
        { "spanish": "llevar", "kana": ["もっていく", "持っていく"] },
        { "spanish": "traer", "kana": ["もってくる", "持ってくる"] },
        { "spanish": "preocuparse", "kana": ["しんぱいする", "心配する"] },
        { "spanish": "trabajar horas extra", "kana": ["ざんぎょうする", "残業する"] },
        { "spanish": "ir de viaje de trabajo", "kana": ["しゅっちょうする", "出張する"] },
        { "spanish": ["tomar medicinas", "medicarse"], "kana": ["くすりをのむ", "薬を飲む"] },
        { "spanish": ["tomar un baño", "bañarse"], "kana": ["おふろにはいる", "お風呂に入る"] },
        { "spanish": ["comprobar", "confirmar"], "kana": ["かくにんする", "確認する"] },
        { "spanish": ["poder", "ser capaz de"], "kana": ["できる", "出来る"] },
        { "spanish": "tocar", "kana": ["ひく", "弾く"] },
        { "spanish": "cantar", "kana": ["うたう", "歌う"] },
        { "spanish": ["coleccionar", "reunir"], "kana": ["あつめる", "集める"] },
        { "spanish": ["tirar", "desechar"], "kana": ["すてる", "捨てる"] },
        { "spanish": ["cambiar", "reemplazar"], "kana": ["かえる", "変える"] },
        { "spanish": "conducir", "kana": ["うんてんする", "運転する"] },
        { "spanish": ["rezar", "orar"], "kana": ["おいのりする", "お祈りする"] },
        { "spanish": "cepillarse los dientes", "kana": ["はをみがく", "歯を磨く"] },
        { "spanish": "planear", "kana": ["よていをつくる", "予定を作る"] },
        { "spanish": "saltear", "kana": ["やく", "焼く"] },
        { "spanish": ["crecer", "incrementar", "multiplicar"], "kana": ["ふえる", "増える"] },
        { "spanish": ["subir", "escalar"], "kana": ["やまにのぼる", "山に上る"] },
        { "spanish": ["alojarse", "hospedarse"], "kana": ["ホテルにとまる", "ホテルに止まる"] },
        { "spanish": "limpiar", "kana": ["そうじする", "掃除する"] },
        { "spanish": ["lavar la ropa", "hacer la colada"], "kana": ["せんたくする", "洗濯する"] },
        { "spanish": ["convertirse", "hacerse", "llegar"], "kana": ["なる", "成る"] },
        { "spanish": ["practicar", "ensayar"], "kana": ["れんしゅうする", "練習する"] },
        { "spanish": "practicar sumo", "kana": ["すもうする", "相撲する"] },
        { "spanish": "hacer ceremonia del té", "kana": ["おちゃをする", "お茶をする"] },
        { "spanish": ["marear", "emborracharse", "intoxicarse"], "kana": ["よう", "酔う"] },
        { "spanish": ["dejar de funcionar", "estropearse", "averiarse"], "kana": ["こしょうする", "故障する"] },
        { "spanish": ["necesitar", "requerir"], "kana": ["いる", "要る"] },
        { "spanish": ["buscar", "averiguar", "investigar", "examinar"], "kana": ["しらべる", "調べる"] },
        { "spanish": "reparar", "kana": ["しゅうりする", "修理する"] },
        { "spanish": ["creer", "opinar", "pensar"], "kana": ["おもう", "思う"] },
        { "spanish": "decir", "kana": ["いう", "言う"] },
        { "spanish": "ganar", "kana": ["かつ", "勝つ"] },
        { "spanish": ["perder", "ser derrotado"], "kana": ["まける", "負ける"] },
        { "spanish": "ser útil", "kana": ["やくにたつ", "役に立つ"] },
        { "spanish": ["funcionar", "moverse"], "kana": ["うごく", "動く"] },
        { "spanish": ["dimitir", "dejar"], "kana": ["やめる", "辞める"] },
        { "spanish": ["prestar atención", "tener cuidado"], "kana": ["きをつける", "気をつける"] },
        { "spanish": "estudiar en el extranjero", "kana": ["りゅうがくする", "留学する"] },
        { "spanish": "jugar un partido", "kana": ["しあいをする", "試合をする"] },
        { "spanish": "reformar", "kana": "リフォームする" },
        { "spanish": ["dar", "freir", "regalar"], "kana": ["あげる", "上げる"] },
        { "spanish": ["tener suficiente", "ser suficiente"], "kana": ["たりる", "足りる"] },
        { "spanish": "ponerse camisa", "kana": ["ふくをきる", "服を着る"] },
        { "spanish": ["ponerse zapatos", "ponerse pantalones"], "kana": ["くつをはきる", "靴を履く"] },
        { "spanish": "ponerse sombrero", "kana": ["ぼうしをかぶる", "ぼうしを被る"] },
        { "spanish": "ponerse gafas", "kana": ["メガネをかける", "メガネを掛ける"] },
        { "spanish": "ponerse corbata", "kana": ["ネクタイをする", "ネクタイをしめる", "ネクタイを締める"] },
        { "spanish": "nacer", "kana": ["うまれる", "生まれる"] },
        { "spanish": "ponerse accesorio", "kana": ["とけいをつける", "時計を付ける"] },
        { "spanish": "mentir", "kana": ["うそをつく", "嘘を付く"] },
        { "spanish": "aprender", "kana": ["まなぶ", "学ぶ"] },
        { "spanish": "ver una pesadilla", "kana": ["あくむをみる", "悪夢を見る"] },
        { "spanish": ["girar", "rotar"], "kana": ["まわす", "回す"] },
        { "spanish": ["tirar", "jalar", "enfermar"], "kana": ["ひく", "引く"] },
        { "spanish": ["tocar", "sentir"], "kana": ["さわる", "触る"] },
        { "spanish": "caminar", "kana": ["あるく", "歩く"] },
        { "spanish": "cruzar", "kana": ["わたる", "渡る"] },
        { "spanish": ["doblar", "girar"], "kana": ["まがる", "曲がる"] },
        { "spanish": ["fugarse", "escaparse para casarse"], "kana": ["かけおちする", "駆け落ちする"] },
        { "spanish": "buscar", "kana": ["さがす", "探す", "捜す"] },
        { "spanish": "pintar", "kana": ["ぬる", "塗る"] },
        { "spanish": "engordar", "kana": ["ふとる", "太る"] },
        { "spanish": "darme", "kana": ["くれる", "呉れる"] },
        { "spanish": "oscurecer", "kana": ["くれる", "暮れる"] },
        { "spanish": ["reparar", "arreglar", "corregir"], "kana": ["なおす", "直す"] },
        { "spanish": "llevar", "kana": ["つれていく", "連れて行く"] },
        { "spanish": "traer", "kana": ["つれてくる", "連れてくる"] },
        { "spanish": ["acompañar", "llevar", "enviar"], "kana": ["おくる", "送る"] },
        { "spanish": "presentar", "kana": ["しょうかいする", "紹介する"] },
        { "spanish": ["guiar", "indicar"], "kana": ["あんないする", "案内する"] },
        { "spanish": "quedarse en habitaciones separadas", "kana": ["べつべつにとまる", "別々に止まる"] },
        { "spanish": ["pensar", "considerar"], "kana": ["かんがえる", "考える"] },
        { "spanish": "llegar", "kana": ["つく", "着く"] },
        { "spanish": "envejecer", "kana": ["としをとる", "年をとる"] },
        { "spanish": "enfadarse", "kana": ["むかつく", "むかつく"] },
        { "spanish": "pasar tiempo", "kana": ["たつ", "経つ"] },


        // J3


        { "spanish": ["revisar", "inspeccionar", "examinar", "evaluar"], "kana": ["みる", "診る"] },
        { "spanish": ["retrasarse", "llegar tarde"], "kana": ["おくれる", "遅れる"] },
        { "spanish": "llegar a tiempo", "kana": ["まにあう", "間に合う"] },
        { "spanish": "hacer", "kana": ["やる", "遣る"] },
        { "spanish": ["coger", "recoger"], "kana": ["ひろう", "拾う"] },
        { "spanish": ["avisar", "comunicar", "ponerse en contacto"], "kana": ["れんらくする", "連絡する"] },
        { "spanish": "ordenar", "kana": ["かたづく", "片付く"] },
        { "spanish": ["tener", "criar"], "kana": ["かう", "飼う"] },
        { "spanish": "correr", "kana": ["はしる", "走る"] },
        { "spanish": "verse", "kana": ["みえる", "見える"] },
        { "spanish": "oírse", "kana": ["きこえる", "聞こえる"] },
        { "spanish": ["fundarse", "contruirse", "hacerse", "estar lista"], "kana": "できる" },
        { "spanish": ["organizar", "celebrar", "realizar"], "kana": ["ひらく", "開く"] },
        { "spanish": "construir", "kana": ["たてる", "建てる"] },
        { "spanish": "volar", "kana": ["とぶ", "飛ぶ"] },
        { "spanish": "venderse", "kana": ["うれる", "売れる"] },
        { "spanish": "bailar", "kana": ["おどる", "踊る"] },
        { "spanish": ["masticar", "morder"], "kana": ["かむ", "噛む"] },
        { "spanish": ["elegir", "escoger"], "kana": ["えらぶ", "選ぶ"] },
        { "spanish": "frecuentar", "kana": ["かよう", "通う"] },
        { "spanish": "anotar", "kana": "メモする" },
        { "spanish": "participar", "kana": ["さんかする", "参加する"] },
        { "spanish": "invitar", "kana": ["さそう", "誘う"] },
        { "spanish": "abrirse", "kana": ["あく", "開く"] },
        { "spanish": "cerrarse", "kana": ["しまる", "閉まる"] },
        { "spanish": "encenderse", "kana": ["つく", "付く"] },
        { "spanish": ["irse", "apagarse"], "kana": ["きえる", "消える"] },
        { "spanish": ["averiarse", "romperse"], "kana": ["こわれる", "壊れる"] },
        { "spanish": "romperse", "kana": ["われる", "割れる"] },
        { "spanish": ["romperse", "quebrarse"], "kana": ["おれる", "折れる"] },
        { "spanish": ["romperse", "desgarrarse"], "kana": ["やぶれる", "破れる"] },
        { "spanish": "ensuciarse", "kana": ["よごれる", "汚れる"] },
        { "spanish": "ser puesto", "kana": ["つく", "着く"] },
        { "spanish": ["salirse", "caerse"], "kana": ["はずれる", "外れる"] },
        { "spanish": "pararse", "kana": ["とまる", "止まる"] },
        { "spanish": "equivocarse", "kana": ["ちがえる", "違える"] },
        { "spanish": ["caerse", "perder"], "kana": ["おとす", "落とす"] },
        { "spanish": "cerrarse con llave", "kana": ["かかる", "掛かる"] },
        { "spanish": "limpiar", "kana": ["ふく", "拭く"] },
        { "spanish": ["cambiar", "reemplazar", "sustituir"], "kana": ["とりかえる", "取り替える"] },
        { "spanish": ["arreglar", "ordenar"], "kana": ["かたづける", "片付ける"] },
        { "spanish": "responder", "kana": ["へんじをする", "返事をする"] },
        { "spanish": ["apuntar", "indicar"], "kana": ["さす", "指す"] },
        { "spanish": ["caerse", "derrumbarse"], "kana": ["たおえれる", "倒れる"] },
        { "spanish": ["quemar", "quemarse"], "kana": ["もえる", "燃える"] },
        { "spanish": ["pegar", "fijar"], "kana": ["はる", "張る"] },
        { "spanish": "colgar", "kana": ["かける", "掛ける"] },
        { "spanish": ["adornar", "decorar"], "kana": ["さがる", "飾る"] },
        { "spanish": ["poner en fila", "colocar", "enfilar"], "kana": ["ならべる", "並べる"] },
        { "spanish": "plantar", "kana": ["うえる", "植える"] },
        { "spanish": ["devolver", "reponer"], "kana": ["もどす", "戻す"] },
        { "spanish": ["reunir", "juntar", "resumir", "compilar"], "kana": ["まとめる", "纏める"] },
        { "spanish": ["poner en su lugar", "guardar"], "kana": ["しまう", "仕舞う"] },
        { "spanish": ["determinar", "decidir"], "kana": ["きめる", "決める"] },
        { "spanish": "preparar la lección", "kana": ["よしゅうする", "予習する"] },
        { "spanish": "repasar la lección", "kana": ["ふくしゅうする", "復習する"] },
        { "spanish": "dejar las cosas como están", "kana": ["そのままにする", "其の儘にする"] },
        { "spanish": ["subsistir", "vivir"], "kana": ["せいかつする", "生活する"] },
        { "spanish": "soñar", "kana": ["ゆめをみる", "夢を見る"] },
        { "spanish": "despertarse", "kana": ["めがさめる", "目が覚める"] },
        { "spanish": ["continuar", "seguir"], "kana": ["つづける", "続ける"] },
        { "spanish": "encontrar", "kana": ["みつける", "見つける"] },
        { "spanish": ["obtener", "tomar", "tomarse"], "kana": ["とる", "取る"] },
        { "spanish": "presentarse", "kana": ["うける", "受ける"] },
        { "spanish": ["inscribirse", "pedir", "subscribir"], "kana": ["もうしこむ", "申し込む"] },
        { "spanish": ["descansar", "tomar un descanso"], "kana": ["きゅうけいする", "休憩する"] },
        { "spanish": ["quedar", "sobrar"], "kana": ["のこる", "残る"] },
        { "spanish": "graduarse", "kana": ["そつぎょうする", "卒業する"] },
        { "spanish": "cerrar", "kana": ["とじる", "閉じる"] },
        { "spanish": ["hacer ejercicio", "ejercitarse"], "kana": ["うんどうする", "運動する"] },
        { "spanish": "tener éxito", "kana": ["せいこうする", "成功する"] },
        { "spanish": ["fracasar", "suspender"], "kana": ["しっぱいする", "失敗する"] },
        { "spanish": ["pasar", "aprobar"], "kana": ["ごうかくする", "合格する"] },
        { "spanish": ["cesar", "parar"], "kana": ["やむ", "止む"] },
        { "spanish": "despejarse", "kana": ["はれる", "晴れる"] },
        { "spanish": "nublarse", "kana": ["くもりる", "曇りる"] },
        { "spanish": "resfriarse", "kana": ["かぜをひく", "風邪をひく"] },
        { "spanish": "enfriar", "kana": ["ひやす", "冷やす"] },
        { "spanish": ["llenarse", "congestionarse"], "kana": ["こむ", "込む"] },
        { "spanish": "descongestionarse", "kana": ["すく", "空く"] },
        { "spanish": "participar", "kana": ["でる", "出る"] },
        { "spanish": ["trabajar demasiado", "esforzarse demasiado"], "kana": ["むりをする", "無理をする"] },
        { "spanish": "quemarse", "kana": ["やけどをする", "火傷をする"] },
        { "spanish": ["lesionarse", "herirse"], "kana": ["けがをする", "怪我をする"] },
        { "spanish": ["toser", "tener tos"], "kana": ["せきをする", "咳をする", "せきがでる", "咳がでる"] },
        { "spanish": ["tener problemas", "estar en apuros"], "kana": ["こまる", "困る"] },
        { "spanish": "tocarle", "kana": ["あたる", "当たる"] },
        { "spanish": "huir", "kana": ["にげる", "逃げる"] },
        { "spanish": "hacer ruido", "kana": ["さわぐ", "騒ぐ"] },
        { "spanish": "desistir", "kana": ["あきらめる", "諦める"] },
        { "spanish": "lanzar", "kana": ["なげる", "投げる"] },
        { "spanish": ["cumplir", "obedecer"], "kana": ["まもる", "守る"] },
        { "spanish": "empezar", "kana": ["はじまる", "始まる"] },
        { "spanish": "asistir", "kana": ["しゅっせきする", "出席する"] },
        { "spanish": ["comunicar", "transmitir"], "kana": ["つたえる", "伝える"] },
        { "spanish": "tener cuidado", "kana": ["ちゅういする", "注医する"] },
        { "spanish": "dejar", "kana": ["はずす", "外す"] },
        { "spanish": ["volver", "regresar"], "kana": ["もどる", "戻る"] },
        { "spanish": ["haber", "tener"], "kana": ["ある", "有る"] },
        { "spanish": "reciclar", "kana": "レサイクルする" },
        { "spanish": "ocurrir", "kana": ["おきる", "起きる"] },
        { "spanish": ["ayudarse mutuamente", "cooperar"], "kana": ["たすけあう", "助け合う"] },
        { "spanish": "lavarse los dientes", "kana": ["はをみがく", "はを磨く"] },
        { "spanish": ["lavar", "pulir"], "kana": ["みがく", "磨く"] },
        { "spanish": ["montar", "ensamblar"], "kana": ["くみたてる", "組み立てる"] },
        { "spanish": ["doblar", "romper"], "kana": ["おる", "折る"] },
        { "spanish": ["notar", "darse cuenta"], "kana": ["きがつく", "気がつく"] },
        { "spanish": "echar", "kana": "つける" },
        { "spanish": "encontrar", "kana": ["みつかる", "見つかる"] },
        { "spanish": "preguntar", "kana": ["しつもんする", "質問する"] },
        { "spanish": ["abrir", "usar"], "kana": "さす" },
        { "spanish": ["colocar", "poner"], "kana": ["のせる", "載せる"] },
        { "spanish": "poner al fuego", "kana": ["ひにかける", "火にかける"] },
        { "spanish": ["cocer", "guisar"], "kana": ["にる", "煮る"] },
        { "spanish": ["cocerse", "guisar"], "kana": ["にえる", "煮える"] },
        { "spanish": ["pasar", "transcurrir"], "kana": ["たつ", "経つ"] },
        { "spanish": ["asar", "tostar"], "kana": ["やく", "焼く"] },
        { "spanish": "freír", "kana": ["あげる", "揚げる"] },
        { "spanish": "saltear", "kana": ["いためる", "炒める"] },
        { "spanish": ["cocer", "hervir"], "kana": ["ゆでる", "茹でる"] },
        { "spanish": "cocer al vapor", "kana": ["むす", "蒸す"] },
        { "spanish": "cocer arroz", "kana": ["たく", "炊く"] },
        { "spanish": ["pelar", "mondar"], "kana": ["むく", "剥く"] },
        { "spanish": "picar", "kana": ["きざむ", "刻む"] },
        { "spanish": ["mezclar", "agitar", "batir", "remover"], "kana": ["かきまぜる", "かき混ぜる"] },
        { "spanish": ["florecer", "abrirse"], "kana": ["さく", "咲く"] },
        { "spanish": "cambiar", "kana": ["かわる", "変わる"] },
        { "spanish": ["tener problemas", "estar en apuros"], "kana": ["こまる", "困る"] },
        { "spanish": "marcar", "kana": ["つける", "付ける"] },
        { "spanish": ["recuperarse", "curarse"], "kana": ["なおる", "治る", "直る"] },
        { "spanish": "repararse", "kana": ["なおる", "治る", "直る"] },
        { "spanish": ["hacer clic", "clicar"], "kana": "クリックする" },
        { "spanish": ["grabar", "almacenar", "introducir"], "kana": ["にゅううりょくする", "入力する"] },
        { "spanish": "encontrarse", "kana": "あう" },
        { "spanish": "ahorrar", "kana": ["ちょきんする", "貯金する"] },
        { "spanish": "pasar", "kana": ["すぎる", "過ぎる"] },
        { "spanish": "acostumbrarse", "kana": ["なれる", "慣れる"] },
        { "spanish": ["pudrirse", "descomponerse", "agriarse"], "kana": ["くさる", "腐る"] },
        { "spanish": ["llevar", "transportar"], "kana": ["はこぶ", "運ぶ"] },
        { "spanish": ["usar", "utilizar", "aprovechar"], "kana": ["りようする", "利用する"] },

        
        // J4


        { "spanish": ["alabar", "elogiar"], "kana": ["ほめる", "褒める"] },
        { "spanish": ["reprochar", "reñir", "regañar"], "kana": ["しかる", "叱る"] },
        { "spanish": "invitar", "kana": ["さそう", "誘う"] },
        { "spanish": "invitar", "kana": ["しょうたいする", "招待する"] },
        { "spanish": ["pedir", "solicitar"], "kana": ["たのむ", "頼む"] },
        { "spanish": ["advertir", "avisar"], "kana": ["ちゅういする", "注意する"] },
        { "spanish": ["robar", "quitar"], "kana": ["とる", "取る"] },
        { "spanish": "pisar", "kana": ["ふむ", "踏む"] },
        { "spanish": ["destruir", "demoler"], "kana": ["こわす", "壊す"] },
        { "spanish": "ensuciar", "kana": ["よごす", "汚す"] },
        { "spanish": ["celebrar", "realizar"], "kana": ["おこなう", "行う"] },
        { "spanish": "exportar", "kana": ["ゆしゅつする", "輸出する"] },
        { "spanish": "importar", "kana": ["ゆにゅうする", "輸入する"] },
        { "spanish": "traducir", "kana": ["ほんやくする", "翻訳する"] },
        { "spanish": "inventar", "kana": ["はつめいする", "発明する"] },
        { "spanish": "descubrir", "kana": ["はっけんする", "発見する"] },
        { "spanish": "incendiarse", "kana": ["やける", "焼ける"] },
        { "spanish": "dormir", "kana": ["ねむる", "眠る"] },
        { "spanish": ["grabar", "cincelar"], "kana": ["ほる", "彫る"] },
        { "spanish": "participar", "kana": ["さんかする", "参加する"] },
        { "spanish": ["cuidar", "criar", "cultivar"], "kana": ["そだてる", "育てる"] },
        { "spanish": ["llevar", "transportar"], "kana": ["はこぶ", "運ぶ"] },
        { "spanish": "ingresar en el hospital", "kana": ["にゅういんする", "入院する"] },
        { "spanish": "salir del hospital", "kana": ["たいいんする", "退院する"] },
        { "spanish": ["conectar", "encender"], "kana": ["いれる", "入れる"] },
        { "spanish": ["cortar", "apagar"], "kana": ["きる", "切る"] },
        { "spanish": "cerrar", "kana": ["かける", "掛ける"] },
        { "spanish": ["decir una mentira", "mentir"], "kana": "つく" },
        { "spanish": "ordenar", "kana": ["せいりする", "整理する"] },
        { "spanish": ["ser parecido", "parecerse"], "kana": ["にている", "似ている"] },
        { "spanish": ["cuidar", "atender"], "kana": ["せわをする", "世話をする"] },
        { "spanish": ["pasar", "transcurrir"], "kana": ["じかんがたつ", "時間がたつ"] },
        { "spanish": ["pelearse", "discutir"], "kana": "けんかする" },
        { "spanish": "contestar", "kana": ["こたえる", "答える"] },
        { "spanish": ["caerse", "derrumbarse"], "kana": ["たおれる", "倒れる"] },
        { "spanish": "pasar", "kana": ["とおる", "通る"] },
        { "spanish": ["morir", "morirse"], "kana": ["しぬ", "死ぬ"] },
        { "spanish": "sorprenderse", "kana": "びっくりする" },
        { "spanish": "decepcionarse", "kana": "がっかりする" },
        { "spanish": "tranquilizarse", "kana": ["あんしんする", "安心する"] },
        { "spanish": ["pelearse", "discutir"], "kana": "けんかする" },
        { "spanish": "divorciarse", "kana": ["りこんする", "離婚する"] },
        { "spanish": "engordar", "kana": ["ふとる", "太る"] },
        { "spanish": "adelgazar", "kana": "やせる" },
        { "spanish": "ir", "kana": ["うかがう", "伺う"] },
        { "spanish": "chocar", "kana": "ぶつかる" },
        { "spanish": "occidentalizarse", "kana": ["せいようかする", "西洋化する"] },
        { "spanish": ["venir bien a", "sentar bien a", "ser apto para", "quedar bien"], "kana": ["あう", "会う"] },
        { "spanish": "contar", "kana": ["かぞえる", "数える"] },
        { "spanish": ["medir", "pesar"], "kana": ["はかる", "量る", "測る"] },
        { "spanish": ["confirmar", "asegurar", "comprobar"], "kana": ["たしかめる", "確かめる"] },
        { "spanish": ["quedar bien", "venir bien a", "sentar bien a", "ser apto para"], "kana": ["あう", "合う"] },
        { "spanish": ["salir", "partir"], "kana": ["しゅっぱつする", "出発する"] },
        { "spanish": "llegar", "kana": ["とうちゃくする", "到着する"] },
        { "spanish": "emborracharse", "kana": ["よう", "酔う"] },
        { "spanish": "ir bien", "kana": "うまくいく" },
        { "spanish": "salir", "kana": ["でる", "出る"] },
        { "spanish": "consultar", "kana": ["そうだんする", "相談する"] },
        { "spanish": "venir", "kana": "いらっしゃう" },
        { "spanish": ["cargar", "montar"], "kana": ["つむ", "積む"] },
        { "spanish": ["mover", "accionar", "manejar"], "kana": ["うごかす", "動かす"] },
        { "spanish": ["obtener", "conseguir", "lograr"], "kana": ["てにいれる", "手に入れる"] },
    
        { "spanish": "recibir", "kana": "いただく" },
        { "spanish": "dar", "kana": ["くださる", "下さる"] },
        { "spanish": "dar", "kana": "やる" },
        { "spanish": ["subir", "elevar", "levantar"], "kana": ["あげる", "上げる"] },
        { "spanish": "bajar", "kana": ["さげる", "下げる"] },
        { "spanish": "ser amable con", "kana": ["しんせつにする", "親切にする"] },
        { "spanish": ["abusar", "maltratar", "acosar"], "kana": "いじめる" },
        { "spanish": ["salvar", "ayudar"], "kana": ["たすける", "助ける"] },
        { "spanish": ["vivir", "pasar la vida"], "kana": ["くらす", "暮らす"] },
        
        // { "spanish": "", "kana": ["", ""] },
        
    ]
}