const lessonsj3j4_json = {
    "lesson_26": [
        { "spanish": ["ver", "mirar", "observar", "revisar", "inspeccionar", "examinar", "evaluar"], "kana": ["みます", "見ます", "診ます"] },
        { "spanish": "buscar", "kana": ["さがします", "探します", "捜します"] },
        { "spanish": ["retrasarse", "llegar tarde"], "kana": ["おくれます", "遅れます"] },
        { "spanish": "llegar a tiempo", "kana": ["まにあいます", "間に合います"] },
        { "spanish": "hacer", "kana": "やります" },
        { "spanish": ["coger", "recoger"], "kana": ["ひろいます", "拾います"] },
        { "spanish": ["avisar", "comunicar", "ponerse en contacto"], "kana": ["れんらくします", "連絡します"] },
        { "spanish": ["sentirse bien", "sentirse sano"], "kana": ["きぶんがいい", "気分がいい"] },
        { "spanish": ["sentirse enfermo", "sentirse mal"], "kana": ["きぶんがわるい", "気分が悪い"] },
        { "spanish": ["evento deportivo", "fiesta deportiva"], "kana": ["うんどうかい", "運動会"] },
        { "spanish": "baile de la fiesta Bon", "kana": ["ぼんおどり", "盆踊り"] },
        { "spanish": "mercadillo", "kana": "フリーマーケット" },
        { "spanish": ["lugar", "ubicación", "posición"], "kana": ["ばしょ", "場所"] },
        { "spanish": "voluntariado", "kana": "ボランティア" },
        { "spanish": ["cartera", "monedero"], "kana": ["さいふ", "財布"] },
        { "spanish": ["basura", "desperdicios"], "kana": "ごみ" },
        { "spanish": ["Palacio de Dieta", "parlamento"], "kana": ["こっかいぎじどう", "国会議事堂"] },
        { "spanish": "días laborables", "kana": ["へいじつ", "平日"] },
        { "spanish": "dialecto de", "kana": ["～べん", "～弁"] },
        { "spanish": "la próxima vez", "kana": ["こんど", "今度"] },
        { "spanish": ["muy", "bastante"], "kana": "ずいぶん" },
        { "spanish": ["directo", "inmediato", "personal", "de primera mano"], "kana": ["ちょくせつ", "直接"] },
        { "spanish": ["a cualquier hora", "en cualquier momento"], "kana": "いつでも" },
        { "spanish": ["en cualquier sitio", "dondequiera"], "kana": "どこでも" },
        { "spanish": "cualquier persona", "kana": ["だれでも", "誰でも"] },
        { "spanish": "cualquier cosa", "kana": ["なんでも", "何でも"] },
        { "spanish": ["como este", "tal"], "kana": "こんな～" },
        { "spanish": ["como ese", "como esa", "tal"], "kana": "そんな～" },
        { "spanish": "como aquel", "kana": "あんな～" },
        { "spanish": ["universo", "espacio"], "kana": ["うちゅう", "宇宙"] },
        { "spanish": ["sra", "señora"], "kana": ["～さま", "～様"] },
        { "spanish": ["nave espacial", "astro nave"], "kana": ["うちゅうせん", "宇宙船"] },
        { "spanish": "tener miedo a", "kana": ["こわい", "怖い"] },
        { "spanish": "estación espacial", "kana": ["うちゅうステーション", "宇宙ステーション"] },
        { "spanish": "ser diferente", "kana": ["ちがいます", "違います"] },
        { "spanish": "astronauta", "kana": ["うちゅうひこうし", "宇宙飛行士"] },

        { "spanish": "avería", "kana": "こしょう" },
        { "spanish": "conveniencia", "kana": "つごう" },
        { "spanish": ["me viene mal", "inconveniente"], "kana": "つごうがわるい" },
        { "spanish": ["me viene bien", "conveniente"], "kana": "つごうがいい" },
        { "spanish": "basurero de barrio", "kana": "ごみおきば" },
        { "spanish": "quemar", "kana": "もえます" },
        { "spanish": "vidrio", "kana": "びん" }
    ],



    "lesson_27": [
        { "spanish": ["", ""], "kana": "" },
        { "spanish": "", "kana": "" }
    ],



    "lesson_28": [
        { "spanish": "venderse", "kana": ["売れます", "うれます"] },
        { "spanish": "bailar", "kana": ["踊ります", "おどります"] },
        { "spanish": ["masticar", "morder"], "kana": "かみます" },
        { "spanish": ["elegir", "escoger"], "kana": ["選びます", "えらびます"] },
        { "spanish": ["ir", "frecuentar"], "kana": ["通います", "かよいます"] },
        { "spanish": ["anotar", "tomar notas"], "kana": "メモします" },
        { "spanish": "serio", "kana": "まじめ" },
        { "spanish": ["entusiasmado", "diligente"], "kana": ["熱心「な」", "ねっしん「な」"] },
        { "spanish": ["respetable", "admirable"], "kana": "えらい" },
        { "spanish": ["venir bien", "venir justo", "ser apropiado"], "kana": "ちょうどいい" },
        { "spanish": "paisaje", "kana": ["景色", "けしき"] },
        { "spanish": ["salón de belleza", "peluquería"], "kana": ["美容院", "びよういん"] },
        { "spanish": "cocina", "kana": ["台所", "だいどころ"] },
        { "spanish": ["experiencia", "vivir experiencia"], "kana": ["経験", "けいけん"] },
        { "spanish": "fuerza", "kana": ["力", "ちから"] },
        { "spanish": "popularidad", "kana": ["人気", "にんき"] },
        { "spanish": ["forma", "figura"], "kana": ["形", "かたち"] },
        { "spanish": "color", "kana": ["色", "いろ"] },
        { "spanish": "sabor", "kana": ["味", "あじ"] },
        { "spanish": "chicle", "kana": "がむ" },
        { "spanish": ["bienes", "artículos", "mercancías", "productos"], "kana": ["品物", "しなもの"] },
        { "spanish": "precio", "kana": ["値段", "ねだん"] },
        { "spanish": ["sueldo", "salario"], "kana": ["給料", "きゅうりょう"] },
        { "spanish": ["paga extra", "gratificación", "prima", "bonificación"], "kana": "ボーナス" },
        { "spanish": ["juego", "videojuego"], "kana": "ゲーム" },
        { "spanish": "programa", "kana": ["番組", "ばんぐみ"] },
        { "spanish": ["drama", "serie de televisión"], "kana": "ドラマ" },
        { "spanish": "cantante", "kana": ["歌手", "かしゅ"] },
        { "spanish": "novela", "kana": ["小説", "しょうせつ"] },
        { "spanish": "novelista", "kana": ["小説家", "しょうせつか"] },
        { "spanish": "experto en", "kana": ["～家", "～か"] },
        { "spanish": "máquina", "kana": ["～機", "～き"] },
        { "spanish": "hijo", "kana": ["息子", "むすこ"] },
        { "spanish": "hija", "kana": ["娘", "むすめ"] },
        { "spanish": ["el propio", "mí mismo", "ti mismo", "sí mismo"], "kana": ["自分", "じぶん"] },
        { "spanish": "vida futura", "kana": ["将来", "しょうらい"] },
        { "spanish": ["por un tiempo", "por un rato"], "kana": "しばらく" },
        { "spanish": ["habitualmente", "casi siempre"], "kana": "たいてい" },
        { "spanish": "además", "kana": "それに" },
        { "spanish": ["por eso", "por lo tanto"], "kana": "それで" },
        { "spanish": "aviso", "kana": ["お知らせ", "おしらせ"] },
        { "spanish": "participar", "kana": ["参加します", "さんかします"] },
        { "spanish": "fecha", "kana": ["日にち", "ひにち"] },
        { "spanish": "sábado", "kana": ["土", "ど"] },
        { "spanish": "gimnasio escolar", "kana": ["体育館", "たいいくかん"] },
        { "spanish": "gratis", "kana": ["無料", "むりょう"] },
        { "spanish": "invitar", "kana": ["誘います", "さそいます"] },
        { "spanish": "evento", "kana": "イベント" },

        { "spanish": ["producto manufacturado", "producto en fábrica"], "kana": "せいひん" },
    ],



    "verbos": [
        { "spanish": "levantarse", "kana": "おきます" },
        { "spanish": ["acostarse", "ir a la cama"], "kana": "ねます" },
        { "spanish": "trabajar", "kana": "はたらきます" },
        { "spanish": ["descansar", "estar de vacaciones", "ausentarse", "faltar"], "kana": "やすみます" },
        { "spanish": "estudiar", "kana": "べんきょします" },
        { "spanish": "terminar", "kana": "おわります" },
        { "spanish": "ir", "kana": "いきます" },
        { "spanish": "venir", "kana": "きます" },
        { "spanish": "volver, regresar, irse a casa", "kana": "かえります" },
        { "spanish": "comer", "kana": "たべます" },
        { "spanish": ["beber", "tomar"], "kana": "のみます" },
        { "spanish": "fumar", "kana": "すいます" },
        { "spanish": ["ver", "mirar"], "kana": "みます" },
        { "spanish": ["oír", "escuchar", "preguntar"], "kana": "ききます" },
        { "spanish": "leer", "kana": "よみます" },
        { "spanish": ["escribir", "dibujar"], "kana": "かきます" },
        { "spanish": "comprar", "kana": "かいます" },
        { "spanish": "sacar fotos", "kana": "しゃしんをとります" },
        { "spanish": "hacer", "kana": "します" },
        { "spanish": ["ver a", "encontrarse con"], "kana": "あいます" },
        { "spanish": "cortar", "kana": "きります" },
        { "spanish": "recibir", "kana": "もらいます" },
        { "spanish": "prestar", "kana": "かします" },
        { "spanish": "tomar prestado", "kana": "かります" },
        { "spanish": "enseñar", "kana": "おしえます" },
        { "spanish": "aprender", "kana": "ならいます" },
        { "spanish": ["hacer una llamada", "llamar"], "kana": "でんわをかけます" },
        { "spanish": ["entender", "comprender"], "kana": "わかります" },
        { "spanish": ["estar", "haber", "existir"], "kana": "あります" },
        { "spanish": ["estar", "haber", "existir", "permanecer"], "kana": "います" },
        { "spanish": "construir", "kana": "たてます" },
        { "spanish": ["montar", "subir"], "kana": "のります" },
        { "spanish": "pasear", "kana": "さんぽをします" },
        { "spanish": "tener hijos", "kana": "こどもがいます" },
        { "spanish": ["tardar", "costar"], "kana": "かかります" },
        { "spanish": "descansar", "kana": "きゅうけいします" },
        { "spanish": "hacer encuesta", "kana": "アンケートします" },
        { "spanish": "votar", "kana": "とうびょうします" },
        { "spanish": ["jugar", "divertirse"], "kana": "あそびます" },
        { "spanish": "nadar", "kana": "およぎます" },
        { "spanish": ["recoger", "recibir"], "kana": "むかえます" },
        { "spanish": ["cansarse", "estar cansado"], "kana": "つかれます" },
        { "spanish": "casarse", "kana": "けっこんします" },
        { "spanish": "hacer compras", "kana": "かいものします" },
        { "spanish": "comer", "kana": "しょくじします" },
        { "spanish": "pescar", "kana": "つりをします" },
        { "spanish": "esquiar", "kana": "スキーをします" },
        { "spanish": "secar", "kana": "かわきます" },
        { "spanish": "estar vacío", "kana": "すきます" },
        { "spanish": "recoger", "kana": "うけとります" },
        { "spanish": "pagar", "kana": "はらいます" },
        { "spanish": "esperar", "kana": "まちます" },
        { "spanish": "encender", "kana": "つけます" },
        { "spanish": "apagar", "kana": "けします" },
        { "spanish": "abrir", "kana": "あけます" },
        { "spanish": "cerrar", "kana": "しめます" },
        { "spanish": ["apresurarse", "darse prisa"], "kana": "いそぎます" },
        { "spanish": ["tener algo en la mano", "tomar"], "kana": "もちます" },
        { "spanish": ["pasar", "dar"], "kana": "とります" },
        { "spanish": "ayudar", "kana": "てつだいます" },
        { "spanish": "llamar", "kana": "よびます" },
        { "spanish": "hablar", "kana": "はなします" },
        { "spanish": "usar", "kana": "つかいます" },
        { "spanish": ["parar", "estacionar"], "kana": "とめます" },
        { "spanish": ["mostrar", "enseñar"], "kana": "みせます" },
        { "spanish": "sentarse", "kana": "すわります" },
        { "spanish": "ponerse de pie", "kana": "たちます" },
        { "spanish": "salir", "kana": "でます" },
        { "spanish": "llover", "kana": "あめがふります" },
        { "spanish": "sacar fotocopias", "kana": "コピーします" },
        { "spanish": "explicar", "kana": "せつめいします" },
        { "spanish": "girar", "kana": "まわります" },
        { "spanish": "reservar", "kana": "よやくします" },
        { "spanish": "lavar", "kana": "あらいます" },
        { "spanish": ["poner", "colocar"], "kana": "おきます" },
        { "spanish": ["crear", "hacer", "producir"], "kana": "つくります" },
        { "spanish": "vender", "kana": "うります" },
        { "spanish": ["enterarse", "saber", "conocer"], "kana": "しります" },
        { "spanish": ["vivir", "residir"], "kana": "すみます" },
        { "spanish": "investigar", "kana": "けんきゅうします" },
        { "spanish": ["recordar", "acordarse"], "kana": "おもいだします" },
        { "spanish": ["jubilado", "renunciar"], "kana": "たいしょくします" },
        { "spanish": "subir", "kana": "でんしゃにのります" },
        { "spanish": "bajar", "kana": "でんしゃおおります" },
        { "spanish": ["trasbordo", "transbordo"], "kana": "のりかえます" },
        { "spanish": "ducharse", "kana": "シャワーおあびます" },
        { "spanish": ["meter", "introducir", "insertar"], "kana": "いれます" },
        { "spanish": ["sacar", "entregar", "presentar", "enviar"], "kana": "だします" },
        { "spanish": ["retirar", "sacar"], "kana": "おろします" },
        { "spanish": ["entrar", "ingresar"], "kana": "はいります" },
        { "spanish": "graduarse", "kana": "だいがくおでます" },
        { "spanish": ["presionar", "empujar", "pulsar"], "kana": "おします" },
        { "spanish": ["empezar", "comenzar", "iniciar"], "kana": "はじめます" },
        { "spanish": "visitar", "kana": "けんがくします" },
        { "spanish": ["llamar por teléfono", "telefonear"], "kana": "でんわします" },
        { "spanish": "memorizar", "kana": "おぼえます" },
        { "spanish": "olvidar", "kana": "わすれます" },
        { "spanish": "perder", "kana": "なくします" },
        { "spanish": "devolver", "kana": "かえします" },
        { "spanish": ["salir", "ir", "venir", "volver"], "kana": "でかけます" },
        { "spanish": "quitarse", "kana": "ぬぎます" },
        { "spanish": "llevar", "kana": "もっていきます" },
        { "spanish": "traer", "kana": "もってきます" },
        { "spanish": "preocuparse", "kana": "しんぱいします" },
        { "spanish": "trabajar horas extra", "kana": "ざんぎょうします" },
        { "spanish": "ir de viaje de trabajo", "kana": "しゅっちょうします" },
        { "spanish": ["tomar medicinas", "medicarse"], "kana": "くすりをのみます" },
        { "spanish": ["tomar un baño", "bañarse"], "kana": "おふろにはいります" },
        { "spanish": ["comprobar", "confirmar"], "kana": "かくにんします" },
        { "spanish": ["poder", "ser capaz de"], "kana": "できます" },
        { "spanish": "tocar", "kana": "ひきます" },
        { "spanish": "cantar", "kana": "うたいます" },
        { "spanish": ["coleccionar", "reunir"], "kana": "あつめます" },
        { "spanish": ["tirar", "desechar"], "kana": "すてます" },
        { "spanish": ["cambiar", "reemplazar"], "kana": "かえます" },
        { "spanish": "conducir", "kana": "うんてんします" },
        { "spanish": ["rezar", "orar"], "kana": "おいのりします" },
        { "spanish": "cepillarse los dientes", "kana": "はをみがきます" },
        { "spanish": "planear", "kana": "よていをつくります" },
        { "spanish": "saltear", "kana": "やきます" },
        { "spanish": "crecer", "kana": "ふえます" },
        { "spanish": ["subir", "escalar"], "kana": "やまにのぼります" },
        { "spanish": ["alojarse", "hospedarse"], "kana": "ホテルにとまります" },
        { "spanish": "limpiar", "kana": "そうじします" },
        { "spanish": ["lavar la ropa", "hacer la colada"], "kana": "せんたくします" },
        { "spanish": ["convertirse", "hacerse", "llegar"], "kana": "なります" },
        { "spanish": ["practicar", "ensayar"], "kana": "れんしゅうします" },
        { "spanish": "practicar sumo", "kana": "すもうします" },
        { "spanish": "hacer ceremonia del té", "kana": "おちゃをします" },
        { "spanish": "marear", "kana": "よいます" },
        { "spanish": ["dejar de funcionar", "estropearse", "averiarse"], "kana": "こしょうします" },
        { "spanish": ["necesitar", "requerir"], "kana": "いります" },
        { "spanish": ["buscar", "averiguar", "investigar"], "kana": "しらべます" },
        { "spanish": "reparar", "kana": "しゅうりします" },
        { "spanish": ["vamos a", "hagámoslo"], "kana": "そうします" },
        { "spanish": ["creer", "opinar"], "kana": "おもいます" },
        { "spanish": "decir", "kana": "いいます" },
        { "spanish": "ganar", "kana": "かちます" },
        { "spanish": ["perder", "ser derrotado"], "kana": "まけます" },
        { "spanish": "ser útil", "kana": "やくにたちます" },
        { "spanish": ["funcionar", "moverse"], "kana": "うごきます" },
        { "spanish": ["dimitir", "dejar"], "kana": "やめます" },
        { "spanish": ["prestar atención", "tener cuidado"], "kana": "きをつけます" },
        { "spanish": "estudiar en el extranjero", "kana": "りゅうがくします" },
        { "spanish": "jugar un partido", "kana": "しあいをします" },
        { "spanish": "reformar", "kana": "リフォームします" },
        { "spanish": ["dar", "freir", "regalar"], "kana": "あげます" },
        { "spanish": ["tener suficiente", "ser suficiente"], "kana": "たります" },
        { "spanish": "lo creo", "kana": "そうだとおもいます" },
        { "spanish": "no lo creo", "kana": "ちがうとおもいます" },
        { "spanish": "ponerse camisa", "kana": "ふくをきます" },
        { "spanish": ["ponerse zapatos", "ponerse pantalones"], "kana": "くつをはきます" },
        { "spanish": "ponerse sombrero", "kana": "ぼうしをかぶります" },
        { "spanish": "ponerse gafas", "kana": "めがねをかけます" },
        { "spanish": "ponerse corbata", "kana": ["ネクタイをします", "ネクタイをしめます"] },
        { "spanish": "nacer", "kana": "うまれます" },
        { "spanish": ["felicidades", "felicitaciones"], "kana": "おめでとうございます" },
        { "spanish": "ponerse accesorio", "kana": "とけいをつけます" },
        { "spanish": "mentir", "kana": "うそをつきます" },
        { "spanish": "aprender", "kana": "まなびます" },
        { "spanish": "ver una pesadilla", "kana": "あくむをみます" },
        { "spanish": "girar", "kana": "まわします" },
        { "spanish": ["tirar", "jalar", "enfermar"], "kana": "ひきます" },
        { "spanish": "tocar", "kana": "さわります" },
        { "spanish": "caminar", "kana": "あるきます" },
        { "spanish": "cruzar", "kana": "わたります" },
        { "spanish": ["doblar", "girar"], "kana": "まがります" },
        { "spanish": "lanzar", "kana": "なげます" },
        { "spanish": ["ir sin permiso de los padres", "fugarse"], "kana": "かけおちします" },
        { "spanish": "buscar", "kana": "さがします" },
        { "spanish": "pintar", "kana": "ぬります" },
        { "spanish": "engordar", "kana": "ふとります" },
        { "spanish": "darme", "kana": "くれます" },
        { "spanish": ["reparar", "arreglar", "corregir"], "kana": "なおします" },
        { "spanish": "llevar", "kana": "つれていきます" },
        { "spanish": "traer", "kana": "つれてきます" },
        { "spanish": ["acompañar", "llevar", "enviar"], "kana": "おくります" },
        { "spanish": "presentar", "kana": "しょうかいします" },
        { "spanish": ["guiar por", "indicar el camino"], "kana": "あんないします" },
        { "spanish": "quedarse en habitaciones separadas", "kana": "べつべつにとまります" },
        { "spanish": ["pensar", "considerar"], "kana": "かんがえます" },
        { "spanish": "llegar", "kana": "つきます" },
        { "spanish": "envejecer", "kana": "としをとります" },
        { "spanish": "enfadarse", "kana": "むかつきます" },
        { "spanish": "pasar tiempo", "kana": "たちます" }
    ]
}