const lessons_json = {
    "lesson_1": [
        { "latin": "yo", "kana": "わたし" },
        { "latin": "tú, usted", "kana": "あなた" },
        { "latin": "aquella persona", "kana": ["あのひと", "あのかた"] },
        { "latin": ["señor", "señora", "señorita"], "kana": "~さん" },
        { "latin": "chan", "kana": "~ちゃん" },
        { "latin": "jin", "kana": "~じん" },
        { "latin": ["maestro", "profesor", "instructor"], "kana": "せんせい" },
        { "latin": ["maestro", "profesor", "instructor"], "kana": "きょうし" },
        { "latin": "estudiante", "kana": "がくせい" },
        { "latin": "empleado de la empresa", "kana": "かいしゃいん" },
        { "latin": "empleado de la empresa", "kana": "しゃいん" },
        { "latin": "empleado de un banco", "kana": "ぎんこういん" },
        { "latin": "médico", "kana": "いしゃ" },
        { "latin": "investigador", "kana": "けんきゅうしゃ" },
        { "latin": "universidad", "kana": "さいがく" },
        { "latin": "hospital", "kana": "びょういん" },
        { "latin": "quién", "kana": "だれ(どなた)" },
        { "latin": "años de edad", "kana": "~さい" },
        { "latin": "cuántos años", "kana": ["なんさい", "おいくつ"] },
        { "latin": "sí", "kana": "はい" },
        { "latin": "no", "kana": "いいえ" },

        { "latin": "1 años", "kana": "いっさい" },
        { "latin": "2 años", "kana": "にさい" },
        { "latin": "3 años", "kana": "さんさい" },
        { "latin": "4 años", "kana": "よんさい" },
        { "latin": "5 años", "kana": "ごさい" },
        { "latin": "6 años", "kana": "ろくさい" },
        { "latin": "7 años", "kana": "ななさい" },
        { "latin": "8 años", "kana": "はっさい" },
        { "latin": "9 años", "kana": "きゅうさい" },
        { "latin": "10 años", "kana": "じゅさい" }
    ],


    "lesson_2": [
        { "latin": ["este", "esta", "esto"], "kana": "これ" },
        { "latin": ["ese", "esa", "eso"], "kana": "それ" },
        { "latin": ["aquel", "aquella", "aquello"], "kana": "あれ" },
        { "latin": ["este~", "esta~"], "kana": "この~" },
        { "latin": ["ese~", "esa~"], "kana": "その~" },
        { "latin": ["aquel~", "aquella~"], "kana": "あの~" },
        { "latin": ["libro"], "kana": "ほん" },
        { "latin": "diccionario", "kana": "じしょ" },
        { "latin": "revista", "kana": "ざっし" },
        { "latin": "periódico", "kana": "しんぶん" },
        { "latin": "cuaderno", "kana": "ノート" },
        { "latin": "agenda", "kana": "てちょお" },
        { "latin": "tarjeta de visita", "kana": "めいし" },
        { "latin": "tarjeta", "kana": "カード" },
        { "latin": "lápiz", "kana": "えんぴつ" },
        { "latin": "bolígrafo", "kana": "ボールペン" },
        { "latin": "portaminas", "kana": "シャープペンシル" },
        { "latin": "llave", "kana": "かぎ" },
        { "latin": "reloj", "kana": "とけい" },
        { "latin": "paraguas", "kana": "かさ" },
        { "latin": "bolso, maleta", "kana": "かばん" },
        { "latin": "CD", "kana": "CD" },
        { "latin": ["televisión", "televisor"], "kana": "テレビ" },
        { "latin": "radio", "kana": "ラジオ" },
        { "latin": "máquina fotográfica", "kana": "カメラ" },
        { "latin": "ordenador", "kana": "コンピューター" },
        { "latin": ["coche", "automóvil"], "kana": "くるま" },
        { "latin": "escritorio", "kana": "つくえ" },
        { "latin": "silla", "kana": "いす" },
        { "latin": "chocolate", "kana": "チョコレート" },
        { "latin": "café", "kana": "コーヒー" },
        { "latin": ["souvenir", "recuerdo de un viaje", "regalo que se lleva al visitar a alguien"], "kana": "[お]みやげ" },
        { "latin": "el idioma inglés", "kana": "えいご" },
        { "latin": "el idioma japonés", "kana": "にほんご" },
        { "latin": "idioma~", "kana": "~ご" },
        { "latin": "qué", "kana": "なん" },
        { "latin": "sí, eso", "kana": "そう" }
    ],


    "lesson_3": [
        { "latin": ["aquí", "este lugar"], "kana": "ここ" },
        { "latin": ["ahí", "ese lugar"], "kana": "そこ" },
        { "latin": ["allí", "aquel lugar"], "kana": "あそこ" },
        { "latin": ["dónde", "en qué lugar"], "kana": "そこ" },
        { "latin": ["por aquí", "aquí"], "kana": "こちら" },
        { "latin": ["por ahí", "ahí"], "kana": "そちら" },
        { "latin": ["por allí", "allí"], "kana": "あちら" },
        { "latin": ["por dónde", "dónde"], "kana": "どちら" },
        { "latin": "aula", "kana": "きょうしつ" },
        { "latin": "comedor", "kana": "しょくどう" },
        { "latin": "oficina", "kana": "きむしょ" },
        { "latin": "sala de reuniones", "kana": "かいぎしつ" },
        { "latin": "recepción", "kana": "うけつけ" },
        { "latin": ["recepción", "vestíbulo"], "kana": "ロビー" },
        { "latin": ["habitación", "cuarto"], "kana": "へや" },
        { "latin": ["baño", "servicio"], "kana": "トイレ（おてあらい）" },
        { "latin": "escalera", "kana": "かいだん" },
        { "latin": "ascensor", "kana": "エレベーター" },
        { "latin": "escalera mecánica", "kana": "エスカレーター" },
        { "latin": "máquina expendedora", "kana": "じどうはんばいき" },
        { "latin": ["teléfono", "llamada telefónica"], "kana": "でんわ" },
        { "latin": ["país", "patria"], "kana": "［お］くに" },
        { "latin": ["empresa", "compañía", "firma"], "kana": "かいしゃ" },
        { "latin": "casa", "kana": "うち、いえ" },
        { "latin": "zapatos", "kana": "くつ" },
        { "latin": "corbata", "kana": "ネクタイ" },
        { "latin": "vino", "kana": "ワイン" },
        { "latin": "sección", "kana": "うりば" },
        { "latin": "sótano", "kana": "ちか" },
        { "latin": ["piso", "planta"], "kana": "ーかい（ーがい）" },
        { "latin": "qué piso", "kana": "なんがい" },
        { "latin": "yen", "kana": "ーえん" },
        { "latin": "cuánto", "kana": "いくら" },
        { "latin": "cien", "kana": "ひゃく" },
        { "latin": "mil", "kana": "せん" },
        { "latin": "diez mil", "kana": "まん" }
    ],


    "lesson_4": [
        { "latin": "levantarse", "kana": "おきます" },
        { "latin": ["acostarse", "ir a la cama"], "kana": "ねます" },
        { "latin": "trabajar", "kana": "はたらきませ" },
        { "latin": ["descansar", "estar de vacaciones"], "kana": "やすみます" },
        { "latin": "estudiar", "kana": "べんきょします" },
        { "latin": "terminar", "kana": "おわります" },
        { "latin": "grandes almacenes", "kana": "デパート" },
        { "latin": "banco", "kana": "ぎんこう" },
        { "latin": "oficina de correos", "kana": "ゆうびんきょく" },
        { "latin": "biblioteca", "kana": "としょかん" },
        { "latin": "museo de arte", "kana": "びじゅつかん" },
        { "latin": "ahora", "kana": "いま" },
        { "latin": "hora", "kana": "ーじ" },
        { "latin": "minutos", "kana": "ーふん、ーぷん" },
        { "latin": "y media", "kana": "はん" },
        { "latin": "¿qué hora?", "kana": "なんじ" },
        { "latin": "¿qué minuto?", "kana": "なんぷん" },
        { "latin": ["la mañana", "AM"], "kana": "ごぜん" },
        { "latin": ["la tarde", "PM", "por la tarde"], "kana": "ごご" },
        { "latin": "por la mañana", "kana": "あさ" },
        { "latin": ["día", "mediodía"], "kana": "ひる" },
        { "latin": "noche", "kana": "ばん、よる" },
        { "latin": "anteayer", "kana": "おととい" },
        { "latin": "ayer", "kana": "きのう" },
        { "latin": "hoy", "kana": "きょう" },
        { "latin": "mañana", "kana": "あした" },
        { "latin": "pasado mañana", "kana": "あさって" },
        { "latin": "esta mañana", "kana": "けさ" },
        { "latin": "esta noche", "kana": "こんばん" },
        { "latin": ["descanso", "día libre"], "kana": "やすみ" },
        { "latin": "descanso de mediodía", "kana": "ひるやすみ" },
        { "latin": "número", "kana": "ばんごう" },
        { "latin": "qué número", "kana": "なんばん" },
        { "latin": "examen", "kana": "しけん" },
        { "latin": "reunión", "kana": "かいぎ" },
        { "latin": "película", "kana": "えいが" },
        { "latin": "todas las mañanas", "kana": "まいあさ" },
        { "latin": "todas las noches", "kana": "まいばん" },
        { "latin": "todos los días", "kana": "まいにち" },
        { "latin": "lunes", "kana": "げつようび" },
        { "latin": "martes", "kana": "かようび" },
        { "latin": "miércoles", "kana": "すいようび" },
        { "latin": "jueves", "kana": "もくようび" },
        { "latin": "viernes", "kana": "きんようび" },
        { "latin": "sábado", "kana": "どようび" },
        { "latin": "domingo", "kana": "にちようび" },
        { "latin": "desde ~", "kana": "～から" },
        { "latin": "hasta ~", "kana": "～まで" },
        { "latin": "y", "kana": "～と～" }
    ],


    "lesson_5": [
        { "latin": "ir", "kana": "いきます" },
        { "latin": "venir", "kana": "きます" },
        { "latin": "volver, regresar, irse a casa", "kana": "かえります" },
        { "latin": "escuela", "kana": "がっこう" },
        { "latin": "supermercado", "kana": "スーパー" },
        { "latin": "estación", "kana": "えき" },
        { "latin": "avión", "kana": "ひこうき" },
        { "latin": "barco", "kana": "ふね" },
        { "latin": "tren eléctrico", "kana": "でんしゃ" },
        { "latin": "metro", "kana": "ちかてつ" },
        { "latin": "shinkansen, tren bala", "kana": "しんかんせん" },
        { "latin": "autobús", "kana": "バス" },
        { "latin": "taxi", "kana": "タクシー" },
        { "latin": "bicicleta", "kana": "じてんしゃ" },
        { "latin": "a pie, andando", "kana": "あるいて" },
        { "latin": "persona, gente", "kana": "ひと" },
        { "latin": "amigo(s)", "kana": "ともだち" },
        { "latin": "él, novio", "kana": "かれ" },
        { "latin": "ella, novia", "kana": "かのじょ" },
        { "latin": "familia", "kana": "かぞく" },
        { "latin": "solo", "kana": "ひとりで" },
        { "latin": "la semana pasada", "kana": "せんしゅう" },
        { "latin": "esta semana", "kana": "こんしゅう" },
        { "latin": "la semana que viene", "kana": "らいしゅう" },
        { "latin": "el mes pasado", "kana": "せんげつ" },
        { "latin": "este mes", "kana": "こんげつ" },
        { "latin": "el mes que viene", "kana": "らいげつ" },
        { "latin": "el año pasado", "kana": "きょねん" },
        { "latin": "este año", "kana": "ことし" },
        { "latin": "el año que viene", "kana": "らいねん" },
        { "latin": "año ー", "kana": "ーねん" },
        { "latin": "qué año", "kana": "なんねん" },
        { "latin": "mes de", "kana": "ーげつ" },
        { "latin": "qué mes", "kana": "なんがつ" },
        { "latin": "el día uno", "kana": "ついたち" },
        { "latin": "el día dos, 2 días", "kana": "ふつか" },
        { "latin": "el día cuatro, 4 días", "kana": "みっか" },
        { "latin": "el día tres, 3 días", "kana": "よっか" },
        { "latin": "el día seis, 6 días", "kana": "いつか" },
        { "latin": "el día cinco, 5 días", "kana": "むいか" },
        { "latin": "el día ocho, 8 días", "kana": "なのか" },
        { "latin": "el día siete, 7 días", "kana": "ようか" },
        { "latin": "el día diez, 10 días", "kana": "ここのか" },
        { "latin": "el día nueve, 9 días", "kana": "とおか" },
        { "latin": "el día veinte, 20 días", "kana": "じゅうよっか" },
        { "latin": "el día catorce, 14 días", "kana": "はつか" },
        { "latin": "díaー, ーdía(s)", "kana": "にじゅうよっか" },
        { "latin": "el día veinticuatro, 24 días", "kana": "ーにち" },
        { "latin": "cuándo", "kana": "なんいち" },
        { "latin": "qué día del mes, cuántos días", "kana": "いつ" },
        { "latin": "a ningún sitio", "kana": "たんじょうび" },
        { "latin": "cumpleaños", "kana": "どこ「へ」も（いきませんでした" },
        { "latin": "hacer solo", "kana": "一で verb + します" }
    ],


    "lesson_6": [
        { "latin": "comer", "kana": "たべます" },
        { "latin": ["beber", "tomar"], "kana": "のみます" },
        { "latin": "fumar", "kana": "すいます" },
        { "latin": ["ver", "mirar"], "kana": "みます" },
        { "latin": ["oír", "escuchar"], "kana": "ききます" },
        { "latin": "leer", "kana": "よみます" },
        { "latin": ["escribir", "dibujar"], "kana": "かきます" },
        { "latin": "comprar", "kana": "かいます" },
        { "latin": "sacar fotos", "kana": "しゃしんをとります" },
        { "latin": "hacer", "kana": "します" },
        { "latin": ["ver a", "encontrarse con"], "kana": "あります" },
        { "latin": ["comida", "arroz cocido"], "kana": "ごはん" },
        { "latin": "desayuno", "kana": "あさごはん" },
        { "latin": ["almuerzo", "comida"], "kana": "ひるごはん" },
        { "latin": "cena", "kana": "ばんごはん" },
        { "latin": "pan", "kana": "パン" },
        { "latin": "huevo", "kana": "たまご" },
        { "latin": "carne", "kana": "にく" },
        { "latin": ["pescado", "pez"], "kana": "さかな" },
        { "latin": "verduras", "kana": "やさい" },
        { "latin": "frutas", "kana": "くだもの" },
        { "latin": "agua", "kana": "みず" },
        { "latin": ["té", "té verde"], "kana": "おちゃ" },
        { "latin": ["té negro", "té inglés"], "kana": "こちゃ" },
        { "latin": "leche", "kana": ["ぎゅうにゅう", "ミルク"] },
        { "latin": ["zumo", "refresco"], "kana": "ジューズ" },
        { "latin": "cerveza", "kana": "ビール" },
        { "latin": ["bebida alcohólica", "sake"], "kana": "さけ" },
        { "latin": ["cigarrillo", "tabaco"], "kana": "たばこ" },
        { "latin": ["carta", "correspondencia"], "kana": "てがみ" },
        { "latin": ["informe", "reporte"], "kana": "レポート" },
        { "latin": "fotografía", "kana": "しゃしん" },
        { "latin": "video", "kana": "ビデオ" },
        { "latin": ["tienda", "negocio"], "kana": "みせ" },
        { "latin": "jardín", "kana": "にわ" },
        { "latin": ["deberes", "tarea"], "kana": "しゅくだい" },
        { "latin": "tenis", "kana": "テニス" },
        { "latin": "fútbol", "kana": "サッカー" },
        { "latin": "ver cerezos en flor", "kana": "はなみ" },
        { "latin": "qué", "kana": "なに" },
        { "latin": ["junto", "juntos"], "kana": "いっしょに" },
        { "latin": "un poco", "kana": "ちょっと" },
        { "latin": ["siempre", "normalmente"], "kana": "いつも" },
        { "latin": ["de vez en cuando", "a veces"], "kana": "ときどき" },
        { "latin": ["y luego", "y después"], "kana": "それから" },
        { "latin": "sí", "kana": "ええ" },
        { "latin": "es buena idea", "kana": "いいですね" },
        { "latin": ["entendido", "muy bien"], "kana": "わかりました" }
    ],


    "lesson_7": [
        { "latin": "cortar", "kana": "きります" },
        { "latin": "enviar", "kana": "おくります" },
        { "latin": "dar", "kana": "あげます" },
        { "latin": "recibir", "kana": "もらいます" },
        { "latin": "prestar", "kana": "かします" },
        { "latin": "tomar prestado", "kana": "かります" },
        { "latin": "enseñar", "kana": "おしえます" },
        { "latin": "aprender", "kana": "ならいます" },
        { "latin": "hacer una llamada", "kana": "でんわをかけます" },
        { "latin": "mano", "kana": "て" },
        { "latin": "palillos", "kana": "はし" },
        { "latin": "cuchara", "kana": "スプーン" },
        { "latin": "cuchillo", "kana": "ナイフ" },
        { "latin": "tenedor", "kana": "フォーク" },
        { "latin": "tijeras", "kana": "はさみ" },
        { "latin": "ordenador", "kana": "パソコン" },
        { "latin": "teléfono móvil", "kana": "ケータイ" },
        { "latin": ["email", "correo electrónico"], "kana": "メール" },
        { "latin": "tarjeta de año nuevo", "kana": "ねんがじょう" },
        { "latin": "perforadora", "kana": "パンチ" },
        { "latin": "grapadora", "kana": "ホッチキス" },
        { "latin": "cinta adhesiva", "kana": "セロテープ" },
        { "latin": "goma de borrar", "kana": "けしゴム" },
        { "latin": "papel", "kana": "かみ" },
        { "latin": "flor", "kana": "はな" },
        { "latin": "camisa", "kana": "シャツ" },
        { "latin": "regalo", "kana": "プレセント" },
        { "latin": ["equipaje", "paquete"], "kana": "にもつ" },
        { "latin": "dinero", "kana": "おかね" },
        { "latin": "billete", "kana": "きっぷ" },
        { "latin": "Navidad", "kana": "クリスマス" },
        { "latin": "mi padre", "kana": "ちち" },
        { "latin": "mi madre", "kana": "はは" },
        { "latin": "padre", "kana": "おとうさん" },
        { "latin": "madre", "kana": "おかあさん" },
        { "latin": "ya", "kana": "もう" },
        { "latin": "todavía", "kana": "まだ" },
        { "latin": ["desde ahora", "dentro de poco"], "kana": "これから" }
    ],


    "lesson_8": [
        { "latin": "guapo", "kana": "ハンサム「な」" },
        { "latin": ["hermoso", "limpio"], "kana": "きれい「な」" },
        { "latin": "silencioso", "kana": "しずか「な」" },
        { "latin": ["concurrido", "animado"], "kana": "にぎやか「な」" },
        { "latin": ["famoso", "célebre"], "kana": "ゆうめい「な」" },
        { "latin": ["amable", "generoso"], "kana": "しんせつ「な」" },
        { "latin": ["sano", "con ánimo"], "kana": "げんき「な」" },
        { "latin": "estar libre", "kana": "ひま「な」" },
        { "latin": ["útil", "práctico", "conveniente"], "kana": "べんり「な」" },
        { "latin": ["bonito", "precioso"], "kana": "すてき「な」" },
        { "latin": "grande", "kana": "おおきい" },
        { "latin": "pequeño", "kana": "ちいさい" },
        { "latin": "nuevo", "kana": "あたらしい" },
        { "latin": ["antiguo", "viejo"], "kana": "ふるい" },
        { "latin": "bueno", "kana": ["いい", "よい"] },
        { "latin": "malo", "kana": "わるい" },
        { "latin": ["caluroso", "caliente"], "kana": "あつい" },
        { "latin": "frío", "kana": "さむい" },
        { "latin": "frío", "kana": "つめたい" },
        { "latin": "difícil", "kana": "むずかしい" },
        { "latin": ["fácil", "amable"], "kana": "やさしい" },
        { "latin": "fácil", "kana": "かんたん「な」" },
        { "latin": ["caro", "alto"], "kana": "たかい" },
        { "latin": "barato", "kana": "やすい" },
        { "latin": "bajo", "kana": "ひくい" },
        { "latin": ["interesante", "gracioso"], "kana": "おもしろい" },
        { "latin": ["delicioso", "sabroso", "rico"], "kana": "おいしい" },
        { "latin": ["atareado", "ocupado"], "kana": "おそがしい" },
        { "latin": ["divertido", "placentero"], "kana": "たのしい" },
        { "latin": "blanco", "kana": "しろい" },
        { "latin": "negro", "kana": "くろい" },
        { "latin": "rojo", "kana": "あかい" },
        { "latin": "azul", "kana": "あおい" },
        { "latin": ["árbol de cerezo", "flor de cerezo"], "kana": "さくら" },
        { "latin": "montaña", "kana": "やま" },
        { "latin": ["población", "ciudad"], "kana": "まち" },
        { "latin": ["comida", "alimentos"], "kana": "たべもの" },
        { "latin": "lugar", "kana": "ところ" },
        { "latin": ["residencia", "dormitorios"], "kana": "りょう" },
        { "latin": "restaurante", "kana": "レストラン" },
        { "latin": "vida diaria", "kana": "せいかつ" },
        { "latin": ["trabajo", "profesión"], "kana": "「お」しごと" },
        { "latin": "cómo", "kana": "どう" },
        { "latin": "qué clase de", "kana": "どんな" },
        { "latin": ["muy", "mucho"], "kana": "とても" },
        { "latin": ["no muy", "no mucho"], "kana": "あまり" },
        { "latin": "y", "kana": "そして" },
        { "latin": "pero", "kana": "～が、～" }
    ],


    "lesson_9": [
        { "latin": ["entender", "comprender"], "kana": "わかります" },
        { "latin": ["haber", "estar", "existir"], "kana": "あります" },
        { "latin": "gustar", "kana": "すき" },
        { "latin": ["odiar", "detestar"], "kana": "きらい" },
        { "latin": ["ser bueno", "ser hábil"], "kana": "じょうず" },
        { "latin": ["ser malo", "ser inhábil"], "kana": "へた" },
        { "latin": "bebida", "kana": "のみもの" },
        { "latin": ["cocina", "plato"], "kana": "りょうり" },
        { "latin": "deporte", "kana": "スポーツ" },
        { "latin": "béisbol", "kana": "やきゅう" },
        { "latin": "baile", "kana": "ダンス" },
        { "latin": "viaje", "kana": "りょこう" },
        { "latin": "música", "kana": "おんがく" },
        { "latin": "canción", "kana": "うた" },
        { "latin": "música clásica", "kana": "クラシック" },
        { "latin": "jazz", "kana": "ジャズ" },
        { "latin": "concierto", "kana": "コンサート" },
        { "latin": "día laboral", "kana": "へいじつ" },
        { "latin": "día festivo", "kana": "きゅくじつ" },
        { "latin": "día", "kana": "じつ" },
        { "latin": "karaoke", "kana": "カラオケ" },
        { "latin": "kabuki", "kana": "かぶき" },
        { "latin": ["pintura", "dibujo", "cuadro"], "kana": "え" },
        { "latin": "letra", "kana": "じ" },
        { "latin": "caracteres chinos", "kana": "かんじ" },
        { "latin": "hiragana", "kana": "ひらがな" },
        { "latin": "katakana", "kana": "カタカナ" },
        { "latin": "alfabeto latino", "kana": "ローマじ" },
        { "latin": ["dinero suelto", "en monedas"], "kana": "こまかいおかね" },
        { "latin": "detallista", "kana": "こまかい" },
        { "latin": "entrada", "kana": "チケット" },
        { "latin": "tiempo", "kana": "じかん" },
        { "latin": "algo que hacer", "kana": "ようじ" },
        { "latin": ["cita", "compromiso", "promesa"], "kana": "やくそく" },
        { "latin": ["trabajo temporal", "trabajo eventual"], "kana": "アルバイト" },
        { "latin": "todo", "kana": "ぜんぶ" },
        { "latin": "crear", "kana": "つくります" },
        { "latin": ["su marido", "tu marido"], "kana": "ごしゅじん" },
        { "latin": ["mi marido", "mi esposo"], "kana": ["おっと", "しゅじん"] },
        { "latin": ["su esposa", "tu esposa"], "kana": "おくさん" },
        { "latin": "mi esposa", "kana": ["つま", "かない"] },
        { "latin": ["niño", "mi hijo"], "kana": "こども" },
        { "latin": ["bien", "mucho"], "kana": "よく" },
        { "latin": ["más o menos", "aproximadamente"], "kana": "だいたい" },
        { "latin": "mucho", "kana": "たくさん" },
        { "latin": ["poco", "un poco"], "kana": "すこし" },
        { "latin": "nada", "kana": "ぜんぜん" },
        { "latin": ["temprano", "rápido"], "kana": "はやく" },
        { "latin": "porque", "kana": "～から" },
        { "latin": "por qué", "kana": "どうして" },
        { "latin": "sano", "kana": "けんこう" },
        { "latin": "flexible", "kana": "フレキシブル" },
        { "latin": "dolor", "kana": "いたい" },
        { "latin": "cabeza", "kana": "あたま" },
        { "latin": "querer", "kana": "したい" },
        { "latin": ["guapo", "guay"], "kana": "かっこいい" }
    ],


    "lesson_10": [
        { "latin": ["estar", "haber", "existir"], "kana": "あります" },
        { "latin": ["estar", "haber", "existir"], "kana": "います" },
        { "latin": "diversos", "kana": "いろいろ「な」" },
        { "latin": "hombre", "kana": "おとこのひと" },
        { "latin": "mujer", "kana": "おんなのひと" },
        { "latin": "niño", "kana": "おとこのこ" },
        { "latin": "niña", "kana": "おんなのこ" },
        { "latin": "perro", "kana": "いぬ" },
        { "latin": "perrito", "kana": "こいぬ" },
        { "latin": "gato", "kana": "ねこ" },
        { "latin": "gatito", "kana": "こねこ" },
        { "latin": "panda", "kana": "パンダ" },
        { "latin": "elefante", "kana": "ぞう" },
        { "latin": "caballo", "kana": "うま" },
        { "latin": ["árbol", "madera"], "kana": "き" },
        { "latin": ["cosa", "objeto"], "kana": "もの" },
        { "latin": ["pila", "batería"], "kana": "でんち" },
        { "latin": "caja", "kana": "はこ" },
        { "latin": "cajón", "kana": "ひきだし" },
        { "latin": "interruptor", "kana": "スイッチ" },
        { "latin": ["refrigerador", "nevera"], "kana": "れいぞうこ" },
        { "latin": "congelador", "kana": "れいとうこ" },
        { "latin": "taza", "kana": "マグカップ" },
        { "latin": "vaso", "kana": "コップ" },
        { "latin": "mesa", "kana": "テーブル" },
        { "latin": "cama", "kana": "ベッド" },
        { "latin": "estante", "kana": "たな" },
        { "latin": "puerta", "kana": "ドア" },
        { "latin": "ventana", "kana": "まど" },
        { "latin": "buzón", "kana": "ポスト" },
        { "latin": "construir", "kana": "たてます" },
        { "latin": "edificio de oficinas", "kana": "ビル" },
        { "latin": "edificio", "kana": "たてもの" },
        { "latin": ["ATM", "cajero automático"], "kana": "ATM" },
        { "latin": ["tienda de conveniencia", "tienda de 24 horas"], "kana": "コンビニ" },
        { "latin": "parque", "kana": "こうえん" },
        { "latin": "cafetería", "kana": "きっさてん" },
        { "latin": "tienda de", "kana": "～や" },
        { "latin": "parada", "kana": "のりば" },
        { "latin": "provincia", "kana": "けん" },
        { "latin": ["encima", "arriba"], "kana": "うえ" },
        { "latin": ["debajo", "abajo"], "kana": "した" },
        { "latin": ["delante", "adelante", "en frente"], "kana": "まえ" },
        { "latin": ["montar", "subir"], "kana": "のります" },
        { "latin": "aire acondicionado", "kana": "エアコン" },
        { "latin": ["detrás", "atrás"], "kana": "うしろ" },
        { "latin": "derecha", "kana": "みぎ" },
        { "latin": "izquierda", "kana": "ひだり" },
        { "latin": "dentro", "kana": "なか" },
        { "latin": "fuera", "kana": "そと" },
        { "latin": "al lado", "kana": ["となり", "よこ"] },
        { "latin": "cerca", "kana": "ちかく" },
        { "latin": "lejos", "kana": "とおく" },
        { "latin": "entre", "kana": "あいだ" },
        { "latin": "y entre otros", "kana": "～や ～「など」" },
        { "latin": "banco", "kana": "ベンチ" },
        { "latin": "camión", "kana": "トラック" },
        { "latin": "animal", "kana": "どうぶつ" },
        { "latin": "zoo", "kana": "どうぶつえん" },
        { "latin": "zona al aire libre", "kana": "えん" },
        { "latin": "chanclas", "kana": "ビーチサンダル" },
        { "latin": "sandalias", "kana": "サンダル" },
        { "latin": ["barrio", "distrito"], "kana": "ちいき" },
        { "latin": "pasear", "kana": "さんぽ「を」します" },
        { "latin": "línea de transporte público", "kana": "せん" },
        { "latin": "plaza", "kana": "ひろば" },
        { "latin": ["sección", "esquina"], "kana": "コーナー" },
        { "latin": "centro", "kana": "まんなか" },
        { "latin": "al fondo", "kana": "おく" },
        { "latin": "despertar", "kana": "めぎまし" },
        { "latin": "reloj despertador", "kana": "めぎましどけい" },
        { "latin": "brazo", "kana": "うで" },
        { "latin": "reloj de muñeca", "kana": "うでどけい" },
        { "latin": "estadio", "kana": "スタジアム" },
        { "latin": "estadio", "kana": "ドーム" },
        { "latin": "padres", "kana": "りょうしん" },
        { "latin": "juego de mesa", "kana": "ポードゲーム" }
    ],


    "lesson_11": [
        { "latin": "tener hijos", "kana": "「こどもが」います" },
        { "latin": ["estar", "permanecer"], "kana": "います" },
        { "latin": ["tardar", "costar"], "kana": "かかります" },
        { "latin": ["ausentarse", "faltar"], "kana": "やすみます" },
        { "latin": ["cuántos", "cuántas"], "kana": "いくら" },
        { "latin": "una persona", "kana": "ひとり" },
        { "latin": "dos personas", "kana": "ふたり" },

        { "latin": "objetos", "kana": "ーつ" },
        { "latin": "personas", "kana": "ーにん" },
        { "latin": "orden", "kana": "ーばん" },
        { "latin": ["objetos finos y planos", "objetos planos y finos"], "kana": "ーまい" },
        { "latin": ["máquinas", "vehículos"], "kana": "ーだい" },
        { "latin": "edad", "kana": "ーさい" },
        { "latin": ["libros", "cuadernos"], "kana": "ーさつ" },
        { "latin": "ropas", "kana": "ーちゃく" },
        { "latin": "frecuencia", "kana": "ーかい" },
        { "latin": "objetos pequeños", "kana": "ーこ" },
        { "latin": ["calzados", "calcetines"], "kana": ["ーそく", "ーぞく"] },
        { "latin": "viviendas", "kana": ["ーけん", "ーげん"] },
        { "latin": ["pisos", "plantas"], "kana": ["ーかい", "ーがい"] },
        { "latin": ["objetos delgados y largos", "objetos largos y delgados"], "kana": ["ーほん", "ーぼん", "ーぽん"] },
        { "latin": ["bebidas", "vasos", "copas", "tazas"], "kana": ["ーはい", "ーばい", "ーぱい"] },
        { "latin": ["animales pequeños", "peces", "insectos"], "kana": ["ーひき", "ーびき", "ーぴき"] },

        { "latin": "manzana", "kana": "りんご" },
        { "latin": "mandarina", "kana": "みかん" },
        { "latin": "sándwich", "kana": "サンドイッチ" },
        { "latin": "curry con arroz", "kana": "カレーライス" },
        { "latin": "helado", "kana": "アイスクリーム" },
        { "latin": "sello postal", "kana": "きって" },
        { "latin": "tarjeta postal", "kana": "はがき" },
        { "latin": "sobre", "kana": "ふうとう" },
        { "latin": "padres", "kana": "りょうしん" },
        { "latin": "hermanas", "kana": "しまい" },
        { "latin": "hermanos", "kana": "きょうだい" },
        { "latin": "mi hermano mayor", "kana": "あに" },
        { "latin": "hermano mayor", "kana": "おにいさん" },
        { "latin": "mi hermana mayor", "kana": "あね" },
        { "latin": "hermana mayor", "kana": "おねえさん" },
        { "latin": "hermano pequeño", "kana": "あとうと" },
        { "latin": "hermana pequeña", "kana": "いもうと" },
        { "latin": "país extranjero", "kana": "がいこく" },
        { "latin": "extranjero", "kana": "がいこくじん" },
        { "latin": "estudiante extranjero", "kana": "りゅうがくせい" },
        { "latin": "clase", "kana": "クラス" },
        { "latin": "horas", "kana": "ーじかん" },
        { "latin": "semanas", "kana": "ーしゅうかん" },
        { "latin": "meses", "kana": "ーかげつ" },
        { "latin": "años", "kana": "ーねん" },
        { "latin": "alrededor de", "kana": "～ぐらい" },
        { "latin": ["cuánto tiempo", "cuánta cantidad"], "kana": "どのくらい" },
        { "latin": "en total", "kana": "ぜんぶで" },
        { "latin": "todos", "kana": "みんな" },
        { "latin": "solo", "kana": "～だけ" },
        { "latin": "descansar", "kana": "きゅうけいします" },
        { "latin": "descanso", "kana": "きゅうけい" },
        { "latin": "patinar", "kana": "スケートボード" }
    ],


    "lesson_12": [
        { "latin": ["fácil", "sencillo"], "kana": "かんたん「な」" },
        { "latin": "cercano", "kana": "ちかい" },
        { "latin": ["distante", "lejano"], "kana": "とおい" },
        { "latin": ["rápido", "temprano"], "kana": "はやい" },
        { "latin": ["tarde", "lento", "despacio"], "kana": "おそい" },
        { "latin": ["mucha", "muchos", "mucho"], "kana": "「ひとが」おおい" },
        { "latin": ["poca", "un poco", "escaso"], "kana": "「ひとが」すくない" },
        { "latin": ["cálido", "templado"], "kana": "あたたかい" },
        { "latin": "fresco", "kana": "すずしい" },
        { "latin": "dulce", "kana": "あまい" },
        { "latin": "picante", "kana": "からい" },
        { "latin": "pesado", "kana": "おもい" },
        { "latin": "ligero", "kana": "かるい" },
        { "latin": "preferir", "kana": "「コーヒーが」いい" },
        { "latin": ["estación", "temporada"], "kana": "きせつ" },
        { "latin": "primavera", "kana": "はる" },
        { "latin": "verano", "kana": "なつ" },
        { "latin": "otoño", "kana": "あき" },
        { "latin": "invierno", "kana": "ふゆ" },
        { "latin": ["tiempo", "clima"], "kana": "てんき" },
        { "latin": "lluvia", "kana": "あめ" },
        { "latin": "nieve", "kana": "ゆき" },
        { "latin": "nublado", "kana": "くもり" },
        { "latin": "soleado", "kana": "はれ" },
        { "latin": "hotel", "kana": "ホテル" },
        { "latin": "aeropuerto", "kana": "くうごう" },
        { "latin": ["mar", "océano"], "kana": "うみ" },
        { "latin": "mundo", "kana": "せかい" },
        { "latin": "fiesta", "kana": "パーティー" },
        { "latin": ["festival", "feria"], "kana": "「お」まつり" },
        { "latin": "estofado de ternera y verduras", "kana": "すきやき" },
        { "latin": "sashimi", "kana": "さしみ" },
        { "latin": "sushi", "kana": "「お」すし" },
        { "latin": "tempura", "kana": "てんぷら" },
        { "latin": "carne de cerdo", "kana": "ぶたにく" },
        { "latin": "carne de pollo", "kana": "とりにく" },
        { "latin": "carne de vaca", "kana": "ぎゅうにく" },
        { "latin": "limón", "kana": "レモン" },
        { "latin": "arreglo floral", "kana": "いけばな" },
        { "latin": ["arce", "hojas coloradas de otoño"], "kana": "もみじ" },
        { "latin": "cúal", "kana": "どちら" },
        { "latin": "ambos", "kana": "どちらも" },
        { "latin": ["el más", "el primero"], "kana": "いちばん" },
        { "latin": ["mucho más", "continuamente", "sin parar"], "kana": "ずっと" },
        { "latin": "por primera vez", "kana": "はじめて" },

        { "latin": "aburrido", "kana": "つまらない" },
        { "latin": "normal", "kana": "ふつう「な」" },
        { "latin": "espinacas", "kana": "ほうれんそう" },
        { "latin": "huevo frito", "kana": "めだまやき" },
        { "latin": "cuando tenía", "kana": "～のとき" },
        { "latin": ["buen tiempo", "buen clima"], "kana": "いいてんき" },
        { "latin": "más", "kana": "より" },
        { "latin": "más", "kana": "ほう" },
        { "latin": "igual", "kana": "おなじ" },
        { "latin": "meterse", "kana": "いれます" },
        { "latin": "vivir solo", "kana": "ひとりぐらし" },
        { "latin": "patinete eléctrico", "kana": "スクーター" },
        { "latin": "salmón crudo", "kana": "サーモン" },
        { "latin": "salmón cocinado", "kana": "さけ" },
        { "latin": "atún", "kana": "まぐる" },
        { "latin": "atún enlatado", "kana": "ツナ" },
        { "latin": "cansado", "kana": "つかれ" },
        { "latin": "encuesta", "kana": "アンケート" },
        { "latin": "hacer encuesta", "kana": "アンケートします" },
        { "latin": "primos", "kana": "いとこ" },
        { "latin": "votar", "kana": "とうびょうします" },
        { "latin": "elecciones", "kana": "せんきょ" },
        { "latin": "recomendar", "kana": "おすすめ「な」" },
        { "latin": ["mejórate", "espero que te mejores"], "kana": "おだいじに" },
        { "latin": "vacaciones", "kana": "きゅうじつ" }
    ],


    "lesson_13": [
        { "latin": ["jugar", "divertirse"], "kana": "あそびます" },
        { "latin": "nadar", "kana": "およぎます" },
        { "latin": ["recoger", "recibir"], "kana": "むかえます" },
        { "latin": "cansarse", "kana": "つかれます" },
        { "latin": "estar cansado", "kana": "つかれました" },
        { "latin": "casarse", "kana": "けっこんします" },
        { "latin": "hacer compras", "kana": "かいものします" },
        { "latin": "comer", "kana": "しょくじします" },
        { "latin": "pasear", "kana": "「こうえんを」さんぽします" },
        { "latin": ["duro", "terrible"], "kana": "たいへん「な」" },
        { "latin": "querer", "kana": "ほしい" },
        { "latin": ["amplio", "espacioso"], "kana": "ひるい" },
        { "latin": ["pequeño", "angosto", "estrecho"], "kana": "せまい" },
        { "latin": "piscina", "kana": "プール" },
        { "latin": "río", "kana": "かわ" },
        { "latin": "bellas artes", "kana": "びじゅつ" },
        { "latin": "pesca", "kana": "つり" },
        { "latin": "pescar", "kana": "つりをします" },
        { "latin": "esquí", "kana": "スキー" },
        { "latin": "esquiar", "kana": "スキーをします" },
        { "latin": "fin de semana", "kana": "しゅうまつ" },
        { "latin": "año nuevo", "kana": "「お」しょうがつ" },
        { "latin": "hacia", "kana": "～ごろ" },
        { "latin": "algo", "kana": "なにか" },
        { "latin": "algún lugar", "kana": "どこか" },
        { "latin": "tener sed", "kana": "のどがかわきました" },
        { "latin": "tener hambre", "kana": "おなかがすきました" },
        { "latin": "garganta", "kana": "のど" },
        { "latin": "secar", "kana": "かわきます" },
        { "latin": "estómago", "kana": "おなか" },
        { "latin": "estar vacío", "kana": "すきます" },
        { "latin": "alguien", "kana": "だれか" },
        { "latin": "algún momento", "kana": "いつか" },
        { "latin": "matrimonio", "kana": "けっこん" },
        { "latin": "boda", "kana": "けっこんしき" },
        { "latin": "siguiente", "kana": "つぎ" },
        { "latin": "estar lleno", "kana": "いっぱいです" },
        { "latin": "mucho", "kana": "いっぱい「たくさん」" },
        { "latin": "recoger", "kana": "うけとります" },
        { "latin": "pagar", "kana": "はらいます" },
        { "latin": "esperar", "kana": "まちます" },
        { "latin": "economía", "kana": "けいざい" },
        { "latin": "entrar", "kana": "はいります「に」" },
        { "latin": "salir", "kana": "でます「を」" },
    ],


    "lesson_14": [
        { "latin": "encender", "kana": "つけます" },
        { "latin": "apagar", "kana": "けします" },
        { "latin": "abrir", "kana": "あけます" },
        { "latin": "cerrar", "kana": "しめます" },
        { "latin": ["apresurarse", "darse prisa"], "kana": "いそぎます" },
        { "latin": "esperar", "kana": "まちます" },
        { "latin": ["tener algo en la mano", "tomar"], "kana": "もちます" },
        { "latin": ["pasar", "dar"], "kana": "とります" },
        { "latin": "ayudar", "kana": "てつだいます" },
        { "latin": "llamar", "kana": "よびます" },
        { "latin": "hablar", "kana": "はなします" },
        { "latin": "usar", "kana": "つかいます" },
        { "latin": ["parar", "estacionar"], "kana": "とめます" },
        { "latin": ["mostrar", "enseñar"], "kana": "みせます" },
        { "latin": ["enseñar, dar"], "kana": "［じゅうしょを］おしえます" },
        { "latin": "sentarse", "kana": "すわります" },
        { "latin": "ponerse de pie", "kana": "たちます" },
        { "latin": "entrar", "kana": "［きっさてんに］はいります" },
        { "latin": "salir", "kana": "［きっさてんを］でます" },
        { "latin": "llover", "kana": "［あめが］ふります" },
        { "latin": "sacar fotocopias", "kana": "コピーします" },
        { "latin": ["electricidad", "luz"], "kana": "でんき" },
        { "latin": "aire acondicionado", "kana": "エアコン" },
        { "latin": "pasaporte", "kana": "パスポート" },
        { "latin": "nombre", "kana": "なまえ" },
        { "latin": ["dirección, domicilio"], "kana": "じゅうしょ" },
        { "latin": ["mapa", "plano"], "kana": "ちず" },
        { "latin": "sal", "kana": "しお" },
        { "latin": "azúcar", "kana": "さとう" },
        { "latin": ["pregunta", "problema"], "kana": "もんだい" },
        { "latin": "respuesta", "kana": "こたえ" },
        { "latin": ["cómo leer", "modo de lectura"], "kana": "よみかた" },
        { "latin": ["cómo", "modo de", "manera de"], "kana": "～かた" },
        { "latin": ["derecho", "recto"], "kana": "まっすぐ" },
        { "latin": "despacio", "kana": "ゆっくり" },
        { "latin": "inmediatamente", "kana": "すぐ" },
        { "latin": "de nuevo", "kana": "また" },
        { "latin": ["después", "más tarde"], "kana": "あとで" },
        { "latin": "un poco más", "kana": "もうすこし" },
        { "latin": ["más", "otro"], "kana": "もう" },
        { "latin": "vamos", "kana": "さあ" },
        { "latin": ["¿Cómo?", "¿Eh?"], "kana": "あれ？" },
        { "latin": "mudanza", "kana": "ひっこし" },
        { "latin": "explicar", "kana": "せつめいします" },
        { "latin": "sacar", "kana": "だします" },
        { "latin": "solo", "kana": "だけ" },
        { "latin": "girar", "kana": "まわります" },
        { "latin": "recoger a alguien", "kana": "むかえます" },
        { "latin": "montar", "kana": "のります" },
        { "latin": "reservar", "kana": "よやくします" },
        { "latin": "jefe de departamento", "kana": "ぶちょう" },
        { "latin": "jefe", "kana": "かちょう" },
        { "latin": "materiales", "kana": "しりょう" },
        { "latin": "conductor", "kana": "うんてんしゅ" },
        { "latin": "semáforo", "kana": "しんごう" },
        { "latin": "lavar", "kana": "あらいます" },
        { "latin": "tejado", "kana": "やね" },
        { "latin": "calle", "kana": "みち" },
        { "latin": "correa", "kana": "リード" },
        { "latin": "sin", "kana": "なし" },
        { "latin": "sopa de cerdo", "kana": ["ぶたじる", "とんじる"] },
        { "latin": "estofado", "kana": "ツチュー" }
    ],


    "lesson_15": [
        { "latin": ["poner", "colocar"], "kana": "おきます" },
        { "latin": ["hacer", "producir"], "kana": "つくります" },
        { "latin": "vender", "kana": "うります" },
        { "latin": ["enterarse", "saber", "conocer"], "kana": "しります" },
        { "latin": ["vivir", "residir"], "kana": "すみます" },
        { "latin": "investigar", "kana": "けんきゅうします" },
        { "latin": ["recordar", "acordarse"], "kana": "おもいだします" },
        { "latin": ["materiales", "datos"], "kana": "しりょう" },
        { "latin": "catálogo", "kana": "カタログ" },
        { "latin": "horario", "kana": "じこくひょう" },
        { "latin": "ropa", "kana": "ふく" },
        { "latin": "productos", "kana": "せいひん" },
        { "latin": "software", "kana": "ソフト" },
        { "latin": "diccionario electrónico", "kana": "でんしじしょ" },
        { "latin": "economía", "kana": "けいざい" },
        { "latin": "ayuntamiento", "kana": "しやくしょ" },
        { "latin": ["bachillerato", "escuela secundaria superior"], "kana": "こうこう" },
        { "latin": ["dentista", "clínical dental"], "kana": "はいしゃ" },
        { "latin": "soltero", "kana": "どくしん" },
        { "latin": ["perdón", "lo siento"], "kana": "すみません" },
        { "latin": ["señoras y señores", "ustedes"], "kana": "みなさん" },
        { "latin": "casarse", "kana": "けっこんします" },
        { "latin": "cosas", "kana": "せいひん" },
        { "latin": "usar", "kana": "つかいます" },
        { "latin": "biología", "kana": "せいぶつがく" },
        { "latin": ["pueblo", "campo"], "kana": "いなか" },
        { "latin": "capital", "kana": "しゅと" },
        { "latin": "cambio de divisa", "kana": ["りょうがえ", "かわせ"] },
        { "latin": ["jubilado", "renunciar"], "kana": "たいしょくします" },
        { "latin": "vehículo", "kana": "じどうしゃ" }
    ],


    "lesson_16": [
        { "latin": "subir", "kana": "「でんしゃに」のります" },
        { "latin": "bajar", "kana": "「でんしゃお」おります" },
        { "latin": ["trasbordo", "transbordo"], "kana": "のりかえます" },
        { "latin": "ducharse", "kana": "「シャワーお」あびます" },
        { "latin": ["meter", "introducir", "insertar"], "kana": "いれます" },
        { "latin": ["sacar", "entregar", "presentar", "enviar"], "kana": "だします" },
        { "latin": ["retirar", "sacar"], "kana": "「おかねお」おろします" },
        { "latin": ["entrar", "ingresar"], "kana": "「だいがくに」はいります" },
        { "latin": "graduarse", "kana": "「だいがくお」でます" },
        { "latin": ["presionar", "empujar", "pulsar"], "kana": "おします" },
        { "latin": "beber alcohol", "kana": "のみます" },
        { "latin": ["empezar", "comenzar", "iniciar"], "kana": "はじめます" },
        { "latin": "visitar", "kana": "けんがくします" },
        { "latin": ["llamar por teléfono", "telefonear"], "kana": "でんわします" },
        { "latin": "joven", "kana": "わかい" },
        { "latin": "largo", "kana": "ながい" },
        { "latin": "corto", "kana": "みじかい" },
        { "latin": ["claro", "luminoso"], "kana": "あかるい" },
        { "latin": "oscuro", "kana": "くらい" },
        { "latin": "cuerpo", "kana": "からだ" },
        { "latin": ["cabeza", "cerebro"], "kana": "あたま" },
        { "latin": "cabello", "kana": "かみ" },
        { "latin": "cara", "kana": "かお" },
        { "latin": ["ojo", "ojos"], "kana": "め" },
        { "latin": ["oreja", "orejas"], "kana": "みみ" },
        { "latin": "nariz", "kana": "はな" },
        { "latin": "boca", "kana": "くち" },
        { "latin": ["diente", "dientes"], "kana": "は" },
        { "latin": ["pierna", "piernas", "pie", "pies"], "kana": "あし" },
        { "latin": "estómago", "kana": "おなか" },
        { "latin": ["altura", "estatura"], "kana": "せ" },
        { "latin": "servicio", "kana": "サービス" },
        { "latin": "jogging", "kana": "ジョギング" },
        { "latin": "ducha", "kana": "シャワー" },
        { "latin": ["verde", "zona verde"], "kana": "みどり" },
        { "latin": "templo budista", "kana": "「お」てら" },
        { "latin": "santuario sintoísta", "kana": "じんじゃ" },
        { "latin": "número", "kana": "ーばん" },
        { "latin": ["cómo", "de qué manera"], "kana": ["どうやって", "なんで"] },
        { "latin": "cuál", "kana": "どの～" },
        { "latin": "cuál", "kana": "どれ" },
        { "latin": "increíble", "kana": "すごいですね" },
        { "latin": "todavía", "kana": "まだまだです" },
        { "latin": ["bajo", "pequeño"], "kana": "ちさい" },
        { "latin": "botón", "kana": "ボタン" }
    ],


    "lesson_17": [
        { "latin": "memorizar", "kana": "おぼえます" },
        { "latin": "olvidar", "kana": "わすれます" },
        { "latin": "perder", "kana": "なくします" },
        { "latin": "pagar", "kana": "はらいます" },
        { "latin": "devolver", "kana": "かえします" },
        { "latin": ["salir", "ir", "venir", "volver"], "kana": "「へ」でかけます" },
        { "latin": "quitarse", "kana": "ぬぎます" },
        { "latin": "llevar", "kana": "もっていきます" },
        { "latin": "traer", "kana": "もってきます" },
        { "latin": "preocuparse", "kana": "しんぱいします" },
        { "latin": "trabajar horas extra", "kana": "ざんぎょうします" },
        { "latin": "ir de viaje de trabajo", "kana": "しゅっちょうします" },
        { "latin": ["tomar medicinas", "medicarse"], "kana": "「くすりを」のみます" },
        { "latin": ["tomar un baño", "bañarse"], "kana": "「おふろに」はいります" },
        { "latin": "importante", "kana": "たいせつ「な」" },
        { "latin": "estar bien", "kana": "だいじょうぶ「な」" },
        { "latin": "peligroso", "kana": "あぶない" },
        { "latin": "prohibido fumar", "kana": "きんえん" },
        { "latin": "tarjeta del seguro de salud", "kana": "けんこうほけんしょう" },
        { "latin": "fiebre", "kana": "ねつ" },
        { "latin": "enfermedad grave", "kana": "びょうき" },
        { "latin": ["medicina", "medicamento", "pastillas"], "kana": "くすり" },
        { "latin": ["chaqueta", "abrigo"], "kana": "うわぎ" },
        { "latin": "ropa interior", "kana": "したぎ" },
        { "latin": "unos días", "kana": "２，３にち" },
        { "latin": "unos", "kana": "２，３～" },
        { "latin": "antes de", "kana": "～までに" },
        { "latin": ["por eso", "entonces"], "kana": "ですから" },
        { "latin": "preocupación", "kana": "しんぱい" },
        { "latin": "horas extra", "kana": "ざんぎょう" },
        { "latin": "seguro", "kana": "ほけん" },
        { "latin": "tarjeta", "kana": "しょう" },

        { "latin": "bañera", "kana": "おふろ" },
        { "latin": "platos", "kana": "おさら" },
        { "latin": "país extranjero", "kana": "かいがい" },
        { "latin": "escuela", "kana": "しゅうちょう" },
        { "latin": "documento", "kana": "しりょう" },
        { "latin": "tortilla", "kana": "オムレツ" },
        { "latin": "arroz blanco aguado", "kana": "おかゆ" },
        { "latin": ["comprobar", "confirmar"], "kana": "かくにんします" },
        { "latin": "que te mejores", "kana": "おだいじに" }
    ],



    "lesson_18": [
        { "latin": ["poder", "ser capaz de"], "kana": "できます" },
        { "latin": "lavar", "kana": "あらいます" },
        { "latin": "tocar", "kana": "ひきます" },
        { "latin": "cantar", "kana": "うたいます" },
        { "latin": ["coleccionar", "reunir"], "kana": "あつめます" },
        { "latin": ["tirar", "desechar"], "kana": "すてます" },
        { "latin": ["cambiar", "reemplazar"], "kana": "かえます" },
        { "latin": "conducir", "kana": "うんてんします" },
        { "latin": "reservar", "kana": "よやくします" },
        { "latin": "piano", "kana": "ピアノ" },
        { "latin": "metro", "kana": "メートル" },
        { "latin": "dinero en efectivo", "kana": "げんきん" },
        { "latin": ["afición", "pasatiempo"], "kana": "しゅみ" },
        { "latin": "diario", "kana": "にっき" },
        { "latin": "oración", "kana": "おいのり" },
        { "latin": "jefe de sección", "kana": "かちょう" },
        { "latin": ["gerente de división", "gerente de departamento"], "kana": "ぶちょう" },
        { "latin": ["director ejecutivo", "presidente", "director general de una empresa"], "kana": "しゃちょう" },
        { "latin": "animal", "kana": "どうぶつ" },
        { "latin": "caballo", "kana": "うま" },
        { "latin": "internet", "kana": "インターネット" },

        { "latin": ["por supuesto", "claro"], "kana": "ぜひ" },
        { "latin": "estar feliz", "kana": "うれしい" },
        { "latin": "comida china", "kana": "ちゅうか「りょうり」" },
        { "latin": "otro día", "kana": "べつのひ" },
        { "latin": "uniforme", "kana": "ユニフォーム" },
        { "latin": "Navidad", "kana": "クリスマスイブ" },
        { "latin": "salón", "kana": ["リビング", "いま"] },
        { "latin": "abuelos", "kana": "そふぼ" },
        { "latin": "niebla", "kana": "きり" },
        { "latin": "Nochevieja", "kana": "おおみそか" },
        { "latin": "casa antigua de alquiler", "kana": "こみんか" },
        { "latin": "celebrar los 20 años", "kana": "せいじんのひ" },
        { "latin": ["rezar", "orar"], "kana": "おいのりします" },
        { "latin": "zoo", "kana": "どうぶつえん" },
        { "latin": "poco", "kana": ["あんまり", "あまり"] },
        { "latin": "mi alumno", "kana": "せいと" },
        { "latin": "natación", "kana": "すいえい" },
        { "latin": "no es fácil", "kana": "なかなか" },
        { "latin": "ruidoso", "kana": ["うるさい", "やかましい"] },
        { "latin": "plan", "kana": "よてい" },
        { "latin": "propósito", "kana": "もくひょう" },
        { "latin": "antes de", "kana": "まえに" },
        { "latin": "cepillarse los dientes", "kana": "「ほを」みがきます" },
        { "latin": "personalidad", "kana": "せいかく" },
        { "latin": "planear", "kana": "「よていを」つくります" },
        { "latin": "época", "kana": "じだい" },
        { "latin": "otra vez", "kana": "もういちど" },
        { "latin": "me encantaría", "kana": "ぜひもいちど" },
        { "latin": "peluche", "kana": "ぬいぐるみ" },
        { "latin": "especialmente", "kana": "とくに" },
        { "latin": "historia", "kana": "れきし" },
        { "latin": "saltear", "kana": "やきます" },
        { "latin": "matemáticas", "kana": "すうがく" },
        { "latin": "educación física", "kana": "たいいく" },
        { "latin": "crecer", "kana": "ふえます" },
        { "latin": "estricto", "kana": "きびし" },
        { "latin": "terraza", "kana": "テラス" },
        { "latin": "comida del comedor", "kana": "きゅうしょく" }

    ],



    "lesson_19": [
        { "latin": ["subir", "escalar"], "kana": "「やまに」のぼります" },
        { "latin": ["alojarse", "hospedarse"], "kana": "「ホテルに」とまります" },
        { "latin": "limpiar", "kana": "そうじします" },
        { "latin": ["lavar la ropa", "hacer la colada"], "kana": "せんたくします" },
        { "latin": ["convertirse", "hacerse", "llegar"], "kana": "なります" },
        { "latin": "tener sueño", "kana": "ねむい" },
        { "latin": "fuerte", "kana": "つよい" },
        { "latin": "débil", "kana": "よわい" },
        { "latin": ["práctica", "ensayo"], "kana": "れんしゅう" },
        { "latin": ["practicar", "ensayar"], "kana": "れんしゅう「を」します" },
        { "latin": "golf", "kana": "ゴルフ" },
        { "latin": "sumo", "kana": "すもう" },
        { "latin": "practicar sumo", "kana": "すもうします" },
        { "latin": "ceremonia del té", "kana": "おちゃ" },
        { "latin": "hacer ceremonia del té", "kana": "おちゃをします" },
        { "latin": ["día", "fecha"], "kana": "ひ" },
        { "latin": ["forma", "condición"], "kana": "ちょうし" },
        { "latin": "una vez", "kana": "いちど" },
        { "latin": "nunca", "kana": "いちども" },
        { "latin": "poco a poco", "kana": "だんだん" },
        { "latin": ["dentro de poco", "pronto"], "kana": "もうすぐ" },
        { "latin": ["gracias a usted", "gracias a Dios"], "kana": "おかげさまで" },
        { "latin": ["pero", "sin embargo"], "kana": ["でも", "けど"] },

        { "latin": "lavadora", "kana": "せんたくき" },
        { "latin": "olor", "kana": "におい" },
        { "latin": "marear", "kana": "よいます" },
        { "latin": "teleférico", "kana": "ロープウェー" },
        { "latin": "guía", "kana": "ガイド" },
        { "latin": "elegante", "kana": "エレガント" },
        { "latin": ["dejar de funcionar", "estropearse"], "kana": "こしょうします" }
    ],



    "lesson_20": [
        { "latin": ["necesitar", "requerir"], "kana": "「ビザが」いります" },
        { "latin": ["buscar", "averiguar", "investigar"], "kana": "しらべます" },
        { "latin": "reparar", "kana": "しゅうりします" },
        { "latin": "yo", "kana": "ぼく" },
        { "latin": "tú", "kana": "きみ" },
        { "latin": "señor", "kana": "～くん" },
        { "latin": "sí", "kana": "うん" },
        { "latin": "no", "kana": "ううん" },
        { "latin": ["palabra", "lenguaje", "idioma"], "kana": "ことば" },
        { "latin": "kimono", "kana": "きもの" },
        { "latin": ["visa", "visado"], "kana": "ビザ" },
        { "latin": ["comienzo", "principio"], "kana": "はじめ" },
        { "latin": "fin", "kana": "おわり" },
        { "latin": ["por aquí", "aquí"], "kana": "こっち" },
        { "latin": ["por ahí", "ahí"], "kana": "そっち" },
        { "latin": ["por allí", "allí"], "kana": "あっち" },
        { "latin": ["cuál", "dónde", "por dónde"], "kana": "どっち" },
        { "latin": "todos juntos", "kana": "みんなで" },
        { "latin": "pero", "kana": "～けど" },
        { "latin": ["estoy satisfecho", "estoy lleno"], "kana": "おなかがいっぱいです" },

        { "latin": "lo siento pero me voy primero", "kana": "おさきにしつれいします" },
        { "latin": "ayuntamiento", "kana": "しやくしょ" },
        { "latin": "cómo", "kana": "どう" },
        { "latin": "cómo fue", "kana": "どうだった" },
        { "latin": ["vamos a", "hagámoslo"], "kana": "そうします" },
        { "latin": "ida y vuelta", "kana": "おうふく" },
        { "latin": "?", "kana": "はてな" },
        { "latin": "!", "kana": "ビックリマーク" },
        { "latin": "si no te importa", "kana": "よかったら" },
        { "latin": "más o menos cuando", "kana": "いつごろ" },
        { "latin": "creo que no", "kana": "ないかも" }
    ],



    "lesson_21": [
        { "latin": ["creer", "opinar"], "kana": "おもいます" },
        { "latin": "decir", "kana": "いいます" },
        { "latin": "ganar", "kana": "かちます" },
        { "latin": ["perder", "ser derrotado"], "kana": "まけます" },
        { "latin": ["haber", "tener lugar", "realizarse"], "kana": "あります" },
        { "latin": "ser útil", "kana": "やくにたちます" },
        { "latin": ["funcionar", "moverse"], "kana": "うごきます" },
        { "latin": ["dimitir", "dejar"], "kana": "やめます" },
        { "latin": ["prestar atención", "tener cuidado"], "kana": "きをつけます" },
        { "latin": "estudiar en el extranjero", "kana": "りゅうがくします" },
        { "latin": ["innecesario", "inútil"], "kana": "むだ「な」" },
        { "latin": "inconveniente", "kana": "ふべん「な」" },
        { "latin": ["terrible", "maravilloso", "impresionante"], "kana": "すごい" },
        { "latin": "verdad", "kana": "ほんとう" },
        { "latin": "mentira", "kana": "うそ" },
        { "latin": ["coche", "automóvil"], "kana": "じどうしゃ" },
        { "latin": ["transporte", "tráfico"], "kana": "こうつう" },
        { "latin": ["coste de vida", "costo de vida"], "kana": "ぶっか" },
        { "latin": ["transmisión", "anuncio"], "kana": "ほうそう" },
        { "latin": "noticia", "kana": "ニュース" },
        { "latin": "anime", "kana": "アニメ" },
        { "latin": ["manga", "cómic"], "kana": "マンガ" },
        { "latin": "diseño", "kana": "デザイン" },
        { "latin": "sueño", "kana": "ゆめ" },
        { "latin": "genio", "kana": "てんさい" },
        { "latin": "partido", "kana": "しあい" },
        { "latin": "jugar un partido", "kana": "しあいをします" },
        { "latin": "opinión", "kana": "いけん" },
        { "latin": ["discurso", "cuento"], "kana": "はなし" },
        { "latin": "Tierra", "kana": "ちきゅう" },
        { "latin": "luna", "kana": "つき" },
        { "latin": ["últimamente", "estos días"], "kana": "さいきん" },
        { "latin": ["probablemente", "quizás"], "kana": "たぶん" },
        { "latin": ["sin falta", "seguramente"], "kana": "きっと" },
        { "latin": ["realmente", "de verdad"], "kana": "ほんとうに" },
        { "latin": "no tan", "kana": "そんなに" },
        { "latin": ["sobre", "con respecto a"], "kana": "～について" },

        { "latin": "reformar", "kana": "リフォームします" },
        { "latin": ["freir", "regalar"], "kana": "あげます" },
        { "latin": "última dirección", "kana": "さいしゅうち" },
        { "latin": "tener suficiente", "kana": "たります" },
        { "latin": "por supuesto", "kana": "もちろん" },
        { "latin": "precio inflado", "kana": "ぼったくり" },
        { "latin": "cebolla", "kana": "たまねぎ" },
        { "latin": ["la verdad", "realmente"], "kana": "じつは" },
        { "latin": "último", "kana": "さいご" },
        { "latin": "puntual", "kana": "じかんどうり" },
        { "latin": "ya casi", "kana": "そろそろ" },
        { "latin": "sueldo", "kana": "きゅうりょう" },
        { "latin": "estafa", "kana": "さぎ" },
        { "latin": "lo creo", "kana": "そうだとおもいます" },
        { "latin": "no lo creo", "kana": "ちがうとおもいます" },
        { "latin": "tiempo", "kana": "きかん" }
    ],



    "lesson_22": [
        { "latin": "ponerse camisa", "kana": "「ふくを」きます" },
        { "latin": ["ponerse zapatos", "ponerse pantalones"], "kana": "「くつを」はきます" },
        { "latin": "ponerse sombrero", "kana": "「ぼうしを」かぶります" },
        { "latin": "ponerse gafas", "kana": "「めがねを」かけます" },
        { "latin": "ponerse corbata", "kana": ["「ネクタイを」します", "「ネクタイを」しめます"] },
        { "latin": "nacer", "kana": "うまれます" },
        { "latin": ["abrigo", "sobretodo", "gabardina"], "kana": "コ－ト" },
        { "latin": ["suéter", "pulóver", "jersey"], "kana": "セーター" },
        { "latin": "traje", "kana": "スーツ" },
        { "latin": ["sombrero", "gorra"], "kana": "ぼうし" },
        { "latin": ["gafas", "lentes"], "kana": "めがね" },
        { "latin": "pastel", "kana": "ケーキ" },
        { "latin": "comida preparada en una caja", "kana": "「お」べんとう" },
        { "latin": "robot", "kana": "ロボット" },
        { "latin": "humor", "kana": "ユーモア" },
        { "latin": "conveniencia", "kana": "つごう" },
        { "latin": "frecuentemente", "kana": "よく" },
        { "latin": ["bueno", "veamos"], "kana": "えーと" },
        { "latin": ["felicidades", "felicitaciones"], "kana": "おめでとう「ございます」" },

        { "latin": "ponerse accesorio", "kana": "「とけいを」つけます" },
        { "latin": "taburete", "kana": "スツール" },
        { "latin": ["grabación", "filmación"], "kana": "えいぞう" },
        { "latin": "necesitar", "kana": "いいます" },
        { "latin": "varias cosas", "kana": "いろんなこと" },
        { "latin": "mentir", "kana": "うそをつきます" },
        { "latin": "aprender", "kana": "まなびます" },
        { "latin": "abuelos", "kana": "そふぼ" },
        { "latin": "pesadilla", "kana": "あくむ" },
        { "latin": "ver una pesadilla", "kana": "あくむをみます" },
        { "latin": "calcetines", "kana": "くつした" },
        { "latin": "ceremonia de adultez", "kana": "せいじんしき" },
        { "latin": "ceremonia", "kana": "しき" },
        { "latin": "adulto", "kana": "せいじん" },
        { "latin": "sueldo", "kana": "きゅうりょう" },
        { "latin": "beneficios", "kana": "ふくりこうせい" },
        { "latin": "precio alquiler", "kana": "やちん" },
        { "latin": "entonces", "kana": "では" },
        { "latin": "salón estilo japonés", "kana": "わしつ" },
        { "latin": "armario empotrado", "kana": "おしいれ" },
        { "latin": "buscar", "kana": "さがします" },
        { "latin": "garaje", "kana": "ちゅうしゃじょう" },
        { "latin": "trastero", "kana": "ものおき" },
        { "latin": "polen", "kana": "かふん" }
    ],



    "lesson_23": [
        { "latin": "preguntar", "kana": "ききます" },
        { "latin": "girar", "kana": "まわします" },
        { "latin": ["tirar", "jalar", "enfermar"], "kana": "ひきます" },
        { "latin": "cambiar", "kana": "かえます" },
        { "latin": "tocar", "kana": "さわります" },
        { "latin": "salir", "kana": "でます" },
        { "latin": "caminar", "kana": "あるきます" },
        { "latin": "cruzar", "kana": "わたります" },
        { "latin": ["doblar", "girar"], "kana": "まがります" },
        { "latin": ["solitario", "sentirse solo"], "kana": "さびしい" },
        { "latin": "agua caliente", "kana": "「お」ゆ" },
        { "latin": "sonido", "kana": "おと" },
        { "latin": ["tamaño", "talla"], "kana": "サイズ" },
        { "latin": "avería", "kana": "こしょう" },
        { "latin": "averiarse", "kana": "こしょうします" },
        { "latin": ["calle", "camino"], "kana": "みち" },
        { "latin": "cruce", "kana": "こうさてん" },
        { "latin": "semáforo", "kana": "しんごう" },
        { "latin": "esquina", "kana": "かど" },
        { "latin": "puente", "kana": "はし" },
        { "latin": ["estacionamiento", "aparcamiento"], "kana": "ちゅうしゃじょう" },
        { "latin": "edificio", "kana": "たてもの" },
        { "latin": "muchas veces", "kana": "なんかいも" },
        { "latin": ["el", "la"], "kana": "ーめ" },

        { "latin": "lanzar", "kana": "なげます" },
        { "latin": "casero", "kana": "やぬし" },
        { "latin": ["ir sin permiso de los padres", "fugarse"], "kana": "かけおち「します」" },
        { "latin": "buscar", "kana": "さがします" },
        { "latin": "político", "kana": "せいじか" },
        { "latin": "pintar", "kana": "ぬります" },
        { "latin": "cajones", "kana": "ひきだし" },
        { "latin": "cantidad", "kana": "りょう" },
        { "latin": "mucho", "kana": "おおい" },
        { "latin": "engordar", "kana": "ふとります" },
        { "latin": "feliz", "kana": "しあわせ「な」" },
        { "latin": "electrodoméstico", "kana": "かでん" },
        { "latin": "globo", "kana": "ふうせん" },
        { "latin": "museo", "kana": "はくぶつかん" },
        { "latin": "ambos", "kana": "りょうほう" }
    ],



    "lesson_24": [
        { "latin": "darme", "kana": "くれます" },
        { "latin": ["reparar", "arreglar", "corregir"], "kana": "なおします" },
        { "latin": "llevar", "kana": "つれていきます" },
        { "latin": "traer", "kana": "つれてきます" },
        { "latin": ["acompañar", "llevar"], "kana": "おくります" },
        { "latin": "presentar", "kana": "しょうかいします" },
        { "latin": ["guiar por", "indicar el camino"], "kana": "あんないします" },
        { "latin": "explicar", "kana": "せつめいします" },
        { "latin": ["abuelo", "anciano"], "kana": ["おじいさん", "おじいちゃん"] },
        { "latin": ["abuela", "anciana"], "kana": ["おばあさん", "おばあちゃん"] },
        { "latin": "preparación", "kana": "じゅんび" },
        { "latin": "mudanza", "kana": "ひっこし" },
        { "latin": ["dulce", "golosina"], "kana": "「お」かし" },
        { "latin": "hospedaje en casa de una familia", "kana": "ホームステイ" },
        { "latin": "todo", "kana": ["ぜんぶ", "すべて"] },
        { "latin": ["por uno mismo", "por sí mismo"], "kana": "じぶんで" },

        { "latin": "presentación", "kana": "しょうかい" },
        { "latin": "ramo de flores", "kana": "はなたば" },
        { "latin": "anillo", "kana": "ゆびわ" },
        { "latin": "dedo", "kana": "ゆび" },
        { "latin": "otro", "kana": "ほか" },
        { "latin": "otro lugar", "kana": "ほかのところ" },
        { "latin": "otro día", "kana": "ほかのひ" },
        { "latin": "separado", "kana": "べつべつに" },
        { "latin": "quedarse en habitaciones separadas", "kana": "べつべつにとまります" },
        { "latin": "primer sueldo", "kana": "しょにんきゅう" },
        { "latin": "muebles", "kana": "かぐ" },
        { "latin": "alquiler", "kana": "やちん" },
        { "latin": "croissant", "kana": "クㇿクッサン" }
    ],



    "lesson_25": [
        { "latin": ["pensar", "considerar"], "kana": "かんがえます" },
        { "latin": "llegar", "kana": "つきます" },
        { "latin": "envejecer", "kana": "としをとります" },
        { "latin": "ser suficiente", "kana": "たります" },
        { "latin": ["zona rural", "pueblo natal"], "kana": "いなか" },
        { "latin": "oportunidad", "kana": "チャンス" },
        { "latin": "cien millones", "kana": "おく" },
        { "latin": "si", "kana": "もし" },
        { "latin": ["significado", "sentido"], "kana": "いみ" },

        { "latin": "nuevo", "kana": "しんちゃ" },
        { "latin": ["segunda mano", "seminuevo"], "kana": "ちゅうこしゃ" },
        { "latin": "protector solar", "kana": "ひやけどぬ" },
        { "latin": "almohada", "kana": "まくら" },
        { "latin": "enfadarse", "kana": "むかつきます" },
        { "latin": "pasar tiempo", "kana": "たちます" }
    ]
}