const lessonsj1j2_json = {
    "lesson_1": [
        { "spanish": "yo", "kana": "わたし" },
        { "spanish": "tú, usted", "kana": "あなた" },
        { "spanish": "aquella persona", "kana": ["あのひと", "あのかた"] },
        { "spanish": ["señor", "señora", "señorita"], "kana": "~さん" },
        { "spanish": "chan", "kana": "~ちゃん" },
        { "spanish": "jin", "kana": "~じん" },
        { "spanish": ["maestro", "profesor", "instructor"], "kana": "せんせい" },
        { "spanish": ["maestro", "profesor", "instructor"], "kana": "きょうし" },
        { "spanish": "estudiante", "kana": "がくせい" },
        { "spanish": "empleado de la empresa", "kana": "かいしゃいん" },
        { "spanish": "empleado de la empresa", "kana": "しゃいん" },
        { "spanish": "empleado de un banco", "kana": "ぎんこういん" },
        { "spanish": "médico", "kana": "いしゃ" },
        { "spanish": "investigador", "kana": "けんきゅうしゃ" },
        { "spanish": "universidad", "kana": "さいがく" },
        { "spanish": "hospital", "kana": "びょういん" },
        { "spanish": "quién", "kana": "だれ(どなた)" },
        { "spanish": "años de edad", "kana": "~さい" },
        { "spanish": "cuántos años", "kana": ["なんさい", "おいくつ"] },
        { "spanish": "sí", "kana": "はい" },
        { "spanish": "no", "kana": "いいえ" },

        { "spanish": "1 años", "kana": "いっさい" },
        { "spanish": "2 años", "kana": "にさい" },
        { "spanish": "3 años", "kana": "さんさい" },
        { "spanish": "4 años", "kana": "よんさい" },
        { "spanish": "5 años", "kana": "ごさい" },
        { "spanish": "6 años", "kana": "ろくさい" },
        { "spanish": "7 años", "kana": "ななさい" },
        { "spanish": "8 años", "kana": "はっさい" },
        { "spanish": "9 años", "kana": "きゅうさい" },
        { "spanish": "10 años", "kana": "じゅさい" }
    ],


    "lesson_2": [
        { "spanish": ["este", "esta", "esto"], "kana": "これ" },
        { "spanish": ["ese", "esa", "eso"], "kana": "それ" },
        { "spanish": ["aquel", "aquella", "aquello"], "kana": "あれ" },
        { "spanish": ["este~", "esta~"], "kana": "この~" },
        { "spanish": ["ese~", "esa~"], "kana": "その~" },
        { "spanish": ["aquel~", "aquella~"], "kana": "あの~" },
        { "spanish": ["libro"], "kana": "ほん" },
        { "spanish": "diccionario", "kana": "じしょ" },
        { "spanish": "revista", "kana": "ざっし" },
        { "spanish": "periódico", "kana": "しんぶん" },
        { "spanish": "cuaderno", "kana": "ノート" },
        { "spanish": "agenda", "kana": "てちょお" },
        { "spanish": "tarjeta de visita", "kana": "めいし" },
        { "spanish": "tarjeta", "kana": "カード" },
        { "spanish": "lápiz", "kana": "えんぴつ" },
        { "spanish": "bolígrafo", "kana": "ボールペン" },
        { "spanish": "portaminas", "kana": "シャープペンシル" },
        { "spanish": "llave", "kana": "かぎ" },
        { "spanish": "reloj", "kana": "とけい" },
        { "spanish": "paraguas", "kana": "かさ" },
        { "spanish": "bolso, maleta", "kana": "かばん" },
        { "spanish": "CD", "kana": "CD" },
        { "spanish": ["televisión", "televisor"], "kana": "テレビ" },
        { "spanish": "radio", "kana": "ラジオ" },
        { "spanish": "máquina fotográfica", "kana": "カメラ" },
        { "spanish": "ordenador", "kana": "コンピューター" },
        { "spanish": ["coche", "automóvil"], "kana": "くるま" },
        { "spanish": "escritorio", "kana": "つくえ" },
        { "spanish": "silla", "kana": "いす" },
        { "spanish": "chocolate", "kana": "チョコレート" },
        { "spanish": "café", "kana": "コーヒー" },
        { "spanish": ["souvenir", "recuerdo de un viaje", "regalo que se lleva al visitar a alguien"], "kana": "[お]みやげ" },
        { "spanish": "el idioma inglés", "kana": "えいご" },
        { "spanish": "el idioma japonés", "kana": "にほんご" },
        { "spanish": "idioma~", "kana": "~ご" },
        { "spanish": "qué", "kana": "なん" },
        { "spanish": "sí, eso", "kana": "そう" }
    ],


    "lesson_3": [
        { "spanish": ["aquí", "este lugar"], "kana": "ここ" },
        { "spanish": ["ahí", "ese lugar"], "kana": "そこ" },
        { "spanish": ["allí", "aquel lugar"], "kana": "あそこ" },
        { "spanish": ["dónde", "en qué lugar"], "kana": "そこ" },
        { "spanish": ["por aquí", "aquí"], "kana": "こちら" },
        { "spanish": ["por ahí", "ahí"], "kana": "そちら" },
        { "spanish": ["por allí", "allí"], "kana": "あちら" },
        { "spanish": ["por dónde", "dónde"], "kana": "どちら" },
        { "spanish": "aula", "kana": "きょうしつ" },
        { "spanish": "comedor", "kana": "しょくどう" },
        { "spanish": "oficina", "kana": "きむしょ" },
        { "spanish": "sala de reuniones", "kana": "かいぎしつ" },
        { "spanish": "recepción", "kana": "うけつけ" },
        { "spanish": ["recepción", "vestíbulo"], "kana": "ロビー" },
        { "spanish": ["habitación", "cuarto"], "kana": "へや" },
        { "spanish": ["baño", "servicio"], "kana": "トイレ（おてあらい）" },
        { "spanish": "escalera", "kana": "かいだん" },
        { "spanish": "ascensor", "kana": "エレベーター" },
        { "spanish": "escalera mecánica", "kana": "エスカレーター" },
        { "spanish": "máquina expendedora", "kana": "じどうはんばいき" },
        { "spanish": ["teléfono", "llamada telefónica"], "kana": "でんわ" },
        { "spanish": ["país", "patria"], "kana": "［お］くに" },
        { "spanish": ["empresa", "compañía", "firma"], "kana": "かいしゃ" },
        { "spanish": "casa", "kana": "うち、いえ" },
        { "spanish": "zapatos", "kana": "くつ" },
        { "spanish": "corbata", "kana": "ネクタイ" },
        { "spanish": "vino", "kana": "ワイン" },
        { "spanish": "sección", "kana": "うりば" },
        { "spanish": "sótano", "kana": "ちか" },
        { "spanish": ["piso", "planta"], "kana": "ーかい（ーがい）" },
        { "spanish": "qué piso", "kana": "なんがい" },
        { "spanish": "yen", "kana": "ーえん" },
        { "spanish": "cuánto", "kana": "いくら" },
        { "spanish": "cien", "kana": "ひゃく" },
        { "spanish": "mil", "kana": "せん" },
        { "spanish": "diez mil", "kana": "まん" }
    ],


    "lesson_4": [
        { "spanish": "levantarse", "kana": "おきます" },
        { "spanish": ["acostarse", "ir a la cama"], "kana": "ねます" },
        { "spanish": "trabajar", "kana": "はたらきます" },
        { "spanish": ["descansar", "estar de vacaciones"], "kana": "やすみます" },
        { "spanish": "estudiar", "kana": "べんきょします" },
        { "spanish": "terminar", "kana": "おわります" },
        { "spanish": "grandes almacenes", "kana": "デパート" },
        { "spanish": "banco", "kana": "ぎんこう" },
        { "spanish": "oficina de correos", "kana": "ゆうびんきょく" },
        { "spanish": "biblioteca", "kana": "としょかん" },
        { "spanish": "museo de arte", "kana": "びじゅつかん" },
        { "spanish": "ahora", "kana": "いま" },
        { "spanish": "hora", "kana": "ーじ" },
        { "spanish": "minutos", "kana": "ーふん、ーぷん" },
        { "spanish": "y media", "kana": "はん" },
        { "spanish": "¿qué hora?", "kana": "なんじ" },
        { "spanish": "¿qué minuto?", "kana": "なんぷん" },
        { "spanish": ["la mañana", "AM"], "kana": "ごぜん" },
        { "spanish": ["la tarde", "PM", "por la tarde"], "kana": "ごご" },
        { "spanish": "por la mañana", "kana": "あさ" },
        { "spanish": ["día", "mediodía"], "kana": "ひる" },
        { "spanish": "noche", "kana": "ばん、よる" },
        { "spanish": "anteayer", "kana": "おととい" },
        { "spanish": "ayer", "kana": "きのう" },
        { "spanish": "hoy", "kana": "きょう" },
        { "spanish": "mañana", "kana": "あした" },
        { "spanish": "pasado mañana", "kana": "あさって" },
        { "spanish": "esta mañana", "kana": "けさ" },
        { "spanish": "esta noche", "kana": "こんばん" },
        { "spanish": ["descanso", "día libre"], "kana": "やすみ" },
        { "spanish": "descanso de mediodía", "kana": "ひるやすみ" },
        { "spanish": "número", "kana": "ばんごう" },
        { "spanish": "qué número", "kana": "なんばん" },
        { "spanish": "examen", "kana": "しけん" },
        { "spanish": "reunión", "kana": "かいぎ" },
        { "spanish": "película", "kana": "えいが" },
        { "spanish": "todas las mañanas", "kana": "まいあさ" },
        { "spanish": "todas las noches", "kana": "まいばん" },
        { "spanish": "todos los días", "kana": "まいにち" },
        { "spanish": "lunes", "kana": "げつようび" },
        { "spanish": "martes", "kana": "かようび" },
        { "spanish": "miércoles", "kana": "すいようび" },
        { "spanish": "jueves", "kana": "もくようび" },
        { "spanish": "viernes", "kana": "きんようび" },
        { "spanish": "sábado", "kana": "どようび" },
        { "spanish": "domingo", "kana": "にちようび" },
        { "spanish": "desde ~", "kana": "～から" },
        { "spanish": "hasta ~", "kana": "～まで" },
        { "spanish": "y", "kana": "～と～" }
    ],


    "lesson_5": [
        { "spanish": "ir", "kana": "いきます" },
        { "spanish": "venir", "kana": "きます" },
        { "spanish": "volver, regresar, irse a casa", "kana": "かえります" },
        { "spanish": "escuela", "kana": "がっこう" },
        { "spanish": "supermercado", "kana": "スーパー" },
        { "spanish": "estación", "kana": "えき" },
        { "spanish": "avión", "kana": "ひこうき" },
        { "spanish": "barco", "kana": "ふね" },
        { "spanish": "tren eléctrico", "kana": "でんしゃ" },
        { "spanish": "metro", "kana": "ちかてつ" },
        { "spanish": "shinkansen, tren bala", "kana": "しんかんせん" },
        { "spanish": "autobús", "kana": "バス" },
        { "spanish": "taxi", "kana": "タクシー" },
        { "spanish": "bicicleta", "kana": "じてんしゃ" },
        { "spanish": "a pie, andando", "kana": "あるいて" },
        { "spanish": "persona, gente", "kana": "ひと" },
        { "spanish": "amigo(s)", "kana": "ともだち" },
        { "spanish": "él, novio", "kana": "かれ" },
        { "spanish": "ella, novia", "kana": "かのじょ" },
        { "spanish": "familia", "kana": "かぞく" },
        { "spanish": "solo", "kana": "ひとりで" },
        { "spanish": "la semana pasada", "kana": "せんしゅう" },
        { "spanish": "esta semana", "kana": "こんしゅう" },
        { "spanish": "la semana que viene", "kana": "らいしゅう" },
        { "spanish": "el mes pasado", "kana": "せんげつ" },
        { "spanish": "este mes", "kana": "こんげつ" },
        { "spanish": "el mes que viene", "kana": "らいげつ" },
        { "spanish": "el año pasado", "kana": "きょねん" },
        { "spanish": "este año", "kana": "ことし" },
        { "spanish": "el año que viene", "kana": "らいねん" },
        { "spanish": "año ー", "kana": "ーねん" },
        { "spanish": "qué año", "kana": "なんねん" },
        { "spanish": "mes de", "kana": "ーげつ" },
        { "spanish": "qué mes", "kana": "なんがつ" },
        { "spanish": "el día uno", "kana": "ついたち" },
        { "spanish": "el día dos, 2 días", "kana": "ふつか" },
        { "spanish": "el día cuatro, 4 días", "kana": "みっか" },
        { "spanish": "el día tres, 3 días", "kana": "よっか" },
        { "spanish": "el día seis, 6 días", "kana": "いつか" },
        { "spanish": "el día cinco, 5 días", "kana": "むいか" },
        { "spanish": "el día ocho, 8 días", "kana": "なのか" },
        { "spanish": "el día siete, 7 días", "kana": "ようか" },
        { "spanish": "el día diez, 10 días", "kana": "ここのか" },
        { "spanish": "el día nueve, 9 días", "kana": "とおか" },
        { "spanish": "el día veinte, 20 días", "kana": "じゅうよっか" },
        { "spanish": "el día catorce, 14 días", "kana": "はつか" },
        { "spanish": "díaー, ーdía(s)", "kana": "にじゅうよっか" },
        { "spanish": "el día veinticuatro, 24 días", "kana": "ーにち" },
        { "spanish": "cuándo", "kana": "なんいち" },
        { "spanish": "qué día del mes, cuántos días", "kana": "いつ" },
        { "spanish": "a ningún sitio", "kana": "たんじょうび" },
        { "spanish": "cumpleaños", "kana": "どこ「へ」も（いきませんでした" },
        { "spanish": "hacer solo", "kana": "一で verb + します" }
    ],


    "lesson_6": [
        { "spanish": "comer", "kana": "たべます" },
        { "spanish": ["beber", "tomar"], "kana": "のみます" },
        { "spanish": "fumar", "kana": "すいます" },
        { "spanish": ["ver", "mirar"], "kana": "みます" },
        { "spanish": ["oír", "escuchar"], "kana": "ききます" },
        { "spanish": "leer", "kana": "よみます" },
        { "spanish": ["escribir", "dibujar"], "kana": "かきます" },
        { "spanish": "comprar", "kana": "かいます" },
        { "spanish": "sacar fotos", "kana": "しゃしんをとります" },
        { "spanish": "hacer", "kana": "します" },
        { "spanish": ["ver a", "encontrarse con"], "kana": "あります" },
        { "spanish": ["comida", "arroz cocido"], "kana": "ごはん" },
        { "spanish": "desayuno", "kana": "あさごはん" },
        { "spanish": ["almuerzo", "comida"], "kana": "ひるごはん" },
        { "spanish": "cena", "kana": "ばんごはん" },
        { "spanish": "pan", "kana": "パン" },
        { "spanish": "huevo", "kana": "たまご" },
        { "spanish": "carne", "kana": "にく" },
        { "spanish": ["pescado", "pez"], "kana": "さかな" },
        { "spanish": "verduras", "kana": "やさい" },
        { "spanish": "frutas", "kana": "くだもの" },
        { "spanish": "agua", "kana": "みず" },
        { "spanish": ["té", "té verde"], "kana": "おちゃ" },
        { "spanish": ["té negro", "té inglés"], "kana": "こちゃ" },
        { "spanish": "leche", "kana": ["ぎゅうにゅう", "ミルク"] },
        { "spanish": ["zumo", "refresco"], "kana": "ジューズ" },
        { "spanish": "cerveza", "kana": "ビール" },
        { "spanish": ["bebida alcohólica", "sake"], "kana": "さけ" },
        { "spanish": ["cigarrillo", "tabaco"], "kana": "たばこ" },
        { "spanish": ["carta", "correspondencia"], "kana": "てがみ" },
        { "spanish": ["informe", "reporte"], "kana": "レポート" },
        { "spanish": "fotografía", "kana": "しゃしん" },
        { "spanish": "video", "kana": "ビデオ" },
        { "spanish": ["tienda", "negocio"], "kana": "みせ" },
        { "spanish": "jardín", "kana": "にわ" },
        { "spanish": ["deberes", "tarea"], "kana": "しゅくだい" },
        { "spanish": "tenis", "kana": "テニス" },
        { "spanish": "fútbol", "kana": "サッカー" },
        { "spanish": "ver cerezos en flor", "kana": "はなみ" },
        { "spanish": "qué", "kana": "なに" },
        { "spanish": ["junto", "juntos"], "kana": "いっしょに" },
        { "spanish": "un poco", "kana": "ちょっと" },
        { "spanish": ["siempre", "normalmente"], "kana": "いつも" },
        { "spanish": ["de vez en cuando", "a veces"], "kana": "ときどき" },
        { "spanish": ["y luego", "y después"], "kana": "それから" },
        { "spanish": "sí", "kana": "ええ" },
        { "spanish": "es buena idea", "kana": "いいですね" },
        { "spanish": ["entendido", "muy bien"], "kana": "わかりました" }
    ],


    "lesson_7": [
        { "spanish": "cortar", "kana": "きります" },
        { "spanish": "enviar", "kana": "おくります" },
        { "spanish": "dar", "kana": "あげます" },
        { "spanish": "recibir", "kana": "もらいます" },
        { "spanish": "prestar", "kana": "かします" },
        { "spanish": "tomar prestado", "kana": "かります" },
        { "spanish": "enseñar", "kana": "おしえます" },
        { "spanish": "aprender", "kana": "ならいます" },
        { "spanish": "hacer una llamada", "kana": "でんわをかけます" },
        { "spanish": "mano", "kana": "て" },
        { "spanish": "palillos", "kana": "はし" },
        { "spanish": "cuchara", "kana": "スプーン" },
        { "spanish": "cuchillo", "kana": "ナイフ" },
        { "spanish": "tenedor", "kana": "フォーク" },
        { "spanish": "tijeras", "kana": "はさみ" },
        { "spanish": "ordenador", "kana": "パソコン" },
        { "spanish": "teléfono móvil", "kana": "ケータイ" },
        { "spanish": ["email", "correo electrónico"], "kana": "メール" },
        { "spanish": "tarjeta de año nuevo", "kana": "ねんがじょう" },
        { "spanish": "perforadora", "kana": "パンチ" },
        { "spanish": "grapadora", "kana": "ホッチキス" },
        { "spanish": "cinta adhesiva", "kana": "セロテープ" },
        { "spanish": "goma de borrar", "kana": "けしゴム" },
        { "spanish": "papel", "kana": "かみ" },
        { "spanish": "flor", "kana": "はな" },
        { "spanish": "camisa", "kana": "シャツ" },
        { "spanish": "regalo", "kana": "プレセント" },
        { "spanish": ["equipaje", "paquete"], "kana": "にもつ" },
        { "spanish": "dinero", "kana": "おかね" },
        { "spanish": "billete", "kana": "きっぷ" },
        { "spanish": "Navidad", "kana": "クリスマス" },
        { "spanish": "mi padre", "kana": "ちち" },
        { "spanish": "mi madre", "kana": "はは" },
        { "spanish": "padre", "kana": "おとうさん" },
        { "spanish": "madre", "kana": "おかあさん" },
        { "spanish": "ya", "kana": "もう" },
        { "spanish": "todavía", "kana": "まだ" },
        { "spanish": ["desde ahora", "dentro de poco"], "kana": "これから" }
    ],


    "lesson_8": [
        { "spanish": "guapo", "kana": "ハンサム「な」" },
        { "spanish": ["hermoso", "limpio"], "kana": "きれい「な」" },
        { "spanish": "silencioso", "kana": "しずか「な」" },
        { "spanish": ["concurrido", "animado"], "kana": "にぎやか「な」" },
        { "spanish": ["famoso", "célebre"], "kana": "ゆうめい「な」" },
        { "spanish": ["amable", "generoso"], "kana": "しんせつ「な」" },
        { "spanish": ["sano", "con ánimo"], "kana": "げんき「な」" },
        { "spanish": "estar libre", "kana": "ひま「な」" },
        { "spanish": ["útil", "práctico", "conveniente"], "kana": "べんり「な」" },
        { "spanish": ["bonito", "precioso"], "kana": "すてき「な」" },
        { "spanish": "grande", "kana": "おおきい" },
        { "spanish": "pequeño", "kana": "ちいさい" },
        { "spanish": "nuevo", "kana": "あたらしい" },
        { "spanish": ["antiguo", "viejo"], "kana": "ふるい" },
        { "spanish": "bueno", "kana": ["いい", "よい"] },
        { "spanish": "malo", "kana": "わるい" },
        { "spanish": ["caluroso", "caliente"], "kana": "あつい" },
        { "spanish": "frío", "kana": "さむい" },
        { "spanish": "frío", "kana": "つめたい" },
        { "spanish": "difícil", "kana": "むずかしい" },
        { "spanish": ["fácil", "amable"], "kana": "やさしい" },
        { "spanish": "fácil", "kana": "かんたん「な」" },
        { "spanish": ["caro", "alto"], "kana": "たかい" },
        { "spanish": "barato", "kana": "やすい" },
        { "spanish": "bajo", "kana": "ひくい" },
        { "spanish": ["interesante", "gracioso"], "kana": "おもしろい" },
        { "spanish": ["delicioso", "sabroso", "rico"], "kana": "おいしい" },
        { "spanish": ["atareado", "ocupado"], "kana": "おそがしい" },
        { "spanish": ["divertido", "placentero"], "kana": "たのしい" },
        { "spanish": "blanco", "kana": "しろい" },
        { "spanish": "negro", "kana": "くろい" },
        { "spanish": "rojo", "kana": "あかい" },
        { "spanish": "azul", "kana": "あおい" },
        { "spanish": ["árbol de cerezo", "flor de cerezo"], "kana": "さくら" },
        { "spanish": "montaña", "kana": "やま" },
        { "spanish": ["población", "ciudad"], "kana": "まち" },
        { "spanish": ["comida", "alimentos"], "kana": "たべもの" },
        { "spanish": "lugar", "kana": "ところ" },
        { "spanish": ["residencia", "dormitorios"], "kana": "りょう" },
        { "spanish": "restaurante", "kana": "レストラン" },
        { "spanish": "vida diaria", "kana": "せいかつ" },
        { "spanish": ["trabajo", "profesión"], "kana": "「お」しごと" },
        { "spanish": "cómo", "kana": "どう" },
        { "spanish": "qué clase de", "kana": "どんな" },
        { "spanish": ["muy", "mucho"], "kana": "とても" },
        { "spanish": ["no muy", "no mucho"], "kana": "あまり" },
        { "spanish": "y", "kana": "そして" },
        { "spanish": "pero", "kana": "～が、～" }
    ],


    "lesson_9": [
        { "spanish": ["entender", "comprender"], "kana": "わかります" },
        { "spanish": ["haber", "estar", "existir"], "kana": "あります" },
        { "spanish": "gustar", "kana": "すき" },
        { "spanish": ["odiar", "detestar"], "kana": "きらい" },
        { "spanish": ["ser bueno", "ser hábil"], "kana": "じょうず" },
        { "spanish": ["ser malo", "ser inhábil"], "kana": "へた" },
        { "spanish": "bebida", "kana": "のみもの" },
        { "spanish": ["cocina", "plato"], "kana": "りょうり" },
        { "spanish": "deporte", "kana": "スポーツ" },
        { "spanish": "béisbol", "kana": "やきゅう" },
        { "spanish": "baile", "kana": "ダンス" },
        { "spanish": "viaje", "kana": "りょこう" },
        { "spanish": "música", "kana": "おんがく" },
        { "spanish": "canción", "kana": "うた" },
        { "spanish": "música clásica", "kana": "クラシック" },
        { "spanish": "jazz", "kana": "ジャズ" },
        { "spanish": "concierto", "kana": "コンサート" },
        { "spanish": "día laboral", "kana": "へいじつ" },
        { "spanish": "día festivo", "kana": "きゅくじつ" },
        { "spanish": "día", "kana": "じつ" },
        { "spanish": "karaoke", "kana": "カラオケ" },
        { "spanish": "kabuki", "kana": "かぶき" },
        { "spanish": ["pintura", "dibujo", "cuadro"], "kana": "え" },
        { "spanish": "letra", "kana": "じ" },
        { "spanish": "caracteres chinos", "kana": "かんじ" },
        { "spanish": "hiragana", "kana": "ひらがな" },
        { "spanish": "katakana", "kana": "カタカナ" },
        { "spanish": "alfabeto latino", "kana": "ローマじ" },
        { "spanish": ["dinero suelto", "en monedas"], "kana": "こまかいおかね" },
        { "spanish": "detallista", "kana": "こまかい" },
        { "spanish": "entrada", "kana": "チケット" },
        { "spanish": "tiempo", "kana": "じかん" },
        { "spanish": "algo que hacer", "kana": "ようじ" },
        { "spanish": ["cita", "compromiso", "promesa"], "kana": "やくそく" },
        { "spanish": ["trabajo temporal", "trabajo eventual"], "kana": "アルバイト" },
        { "spanish": "todo", "kana": "ぜんぶ" },
        { "spanish": "crear", "kana": "つくります" },
        { "spanish": ["su marido", "tu marido"], "kana": "ごしゅじん" },
        { "spanish": ["mi marido", "mi esposo"], "kana": ["おっと", "しゅじん"] },
        { "spanish": ["su esposa", "tu esposa"], "kana": "おくさん" },
        { "spanish": "mi esposa", "kana": ["つま", "かない"] },
        { "spanish": ["niño", "mi hijo"], "kana": "こども" },
        { "spanish": ["bien", "mucho"], "kana": "よく" },
        { "spanish": ["más o menos", "aproximadamente"], "kana": "だいたい" },
        { "spanish": "mucho", "kana": "たくさん" },
        { "spanish": ["poco", "un poco"], "kana": "すこし" },
        { "spanish": "nada", "kana": "ぜんぜん" },
        { "spanish": ["temprano", "rápido"], "kana": "はやく" },
        { "spanish": "porque", "kana": "～から" },
        { "spanish": "por qué", "kana": "どうして" },
        { "spanish": "sano", "kana": "けんこう" },
        { "spanish": "flexible", "kana": "フレキシブル" },
        { "spanish": "dolor", "kana": "いたい" },
        { "spanish": "cabeza", "kana": "あたま" },
        { "spanish": "querer", "kana": "したい" },
        { "spanish": ["guapo", "guay"], "kana": "かっこいい" }
    ],


    "lesson_10": [
        { "spanish": ["estar", "haber", "existir"], "kana": "あります" },
        { "spanish": ["estar", "haber", "existir"], "kana": "います" },
        { "spanish": "diversos", "kana": "いろいろ「な」" },
        { "spanish": "hombre", "kana": "おとこのひと" },
        { "spanish": "mujer", "kana": "おんなのひと" },
        { "spanish": "niño", "kana": "おとこのこ" },
        { "spanish": "niña", "kana": "おんなのこ" },
        { "spanish": "perro", "kana": "いぬ" },
        { "spanish": "perrito", "kana": "こいぬ" },
        { "spanish": "gato", "kana": "ねこ" },
        { "spanish": "gatito", "kana": "こねこ" },
        { "spanish": "panda", "kana": "パンダ" },
        { "spanish": "elefante", "kana": "ぞう" },
        { "spanish": "caballo", "kana": "うま" },
        { "spanish": ["árbol", "madera"], "kana": "き" },
        { "spanish": ["cosa", "objeto"], "kana": "もの" },
        { "spanish": ["pila", "batería"], "kana": "でんち" },
        { "spanish": "caja", "kana": "はこ" },
        { "spanish": "cajón", "kana": "ひきだし" },
        { "spanish": "interruptor", "kana": "スイッチ" },
        { "spanish": ["refrigerador", "nevera"], "kana": "れいぞうこ" },
        { "spanish": "congelador", "kana": "れいとうこ" },
        { "spanish": "taza", "kana": "マグカップ" },
        { "spanish": "vaso", "kana": "コップ" },
        { "spanish": "mesa", "kana": "テーブル" },
        { "spanish": "cama", "kana": "ベッド" },
        { "spanish": "estante", "kana": "たな" },
        { "spanish": "puerta", "kana": "ドア" },
        { "spanish": "ventana", "kana": "まど" },
        { "spanish": "buzón", "kana": "ポスト" },
        { "spanish": "construir", "kana": "たてます" },
        { "spanish": "edificio de oficinas", "kana": "ビル" },
        { "spanish": "edificio", "kana": "たてもの" },
        { "spanish": ["ATM", "cajero automático"], "kana": "ATM" },
        { "spanish": ["tienda de conveniencia", "tienda de 24 horas"], "kana": "コンビニ" },
        { "spanish": "parque", "kana": "こうえん" },
        { "spanish": "cafetería", "kana": "きっさてん" },
        { "spanish": "tienda de", "kana": "～や" },
        { "spanish": "parada", "kana": "のりば" },
        { "spanish": "provincia", "kana": "けん" },
        { "spanish": ["encima", "arriba"], "kana": "うえ" },
        { "spanish": ["debajo", "abajo"], "kana": "した" },
        { "spanish": ["delante", "adelante", "en frente"], "kana": "まえ" },
        { "spanish": ["montar", "subir"], "kana": "のります" },
        { "spanish": "aire acondicionado", "kana": "エアコン" },
        { "spanish": ["detrás", "atrás"], "kana": "うしろ" },
        { "spanish": "derecha", "kana": "みぎ" },
        { "spanish": "izquierda", "kana": "ひだり" },
        { "spanish": "dentro", "kana": "なか" },
        { "spanish": "fuera", "kana": "そと" },
        { "spanish": "al lado", "kana": ["となり", "よこ"] },
        { "spanish": "cerca", "kana": "ちかく" },
        { "spanish": "lejos", "kana": "とおく" },
        { "spanish": "entre", "kana": "あいだ" },
        { "spanish": "y entre otros", "kana": "～や ～「など」" },
        { "spanish": "banco", "kana": "ベンチ" },
        { "spanish": "camión", "kana": "トラック" },
        { "spanish": "animal", "kana": "どうぶつ" },
        { "spanish": "zoo", "kana": "どうぶつえん" },
        { "spanish": "zona al aire libre", "kana": "えん" },
        { "spanish": "chanclas", "kana": "ビーチサンダル" },
        { "spanish": "sandalias", "kana": "サンダル" },
        { "spanish": ["barrio", "distrito"], "kana": "ちいき" },
        { "spanish": "pasear", "kana": "さんぽ「を」します" },
        { "spanish": "línea de transporte público", "kana": "せん" },
        { "spanish": "plaza", "kana": "ひろば" },
        { "spanish": ["sección", "esquina"], "kana": "コーナー" },
        { "spanish": "centro", "kana": "まんなか" },
        { "spanish": "al fondo", "kana": "おく" },
        { "spanish": "despertar", "kana": "めぎまし" },
        { "spanish": "reloj despertador", "kana": "めぎましどけい" },
        { "spanish": "brazo", "kana": "うで" },
        { "spanish": "reloj de muñeca", "kana": "うでどけい" },
        { "spanish": "estadio", "kana": "スタジアム" },
        { "spanish": "estadio", "kana": "ドーム" },
        { "spanish": "padres", "kana": "りょうしん" },
        { "spanish": "juego de mesa", "kana": "ポードゲーム" }
    ],


    "lesson_11": [
        { "spanish": "tener hijos", "kana": "「こどもが」います" },
        { "spanish": ["estar", "permanecer"], "kana": "います" },
        { "spanish": ["tardar", "costar"], "kana": "かかります" },
        { "spanish": ["ausentarse", "faltar"], "kana": "やすみます" },
        { "spanish": ["cuántos", "cuántas"], "kana": "いくら" },
        { "spanish": "una persona", "kana": "ひとり" },
        { "spanish": "dos personas", "kana": "ふたり" },

        { "spanish": "objetos", "kana": "ーつ" },
        { "spanish": "personas", "kana": "ーにん" },
        { "spanish": "orden", "kana": "ーばん" },
        { "spanish": ["objetos finos y planos", "objetos planos y finos"], "kana": "ーまい" },
        { "spanish": ["máquinas", "vehículos"], "kana": "ーだい" },
        { "spanish": "edad", "kana": "ーさい" },
        { "spanish": ["libros", "cuadernos"], "kana": "ーさつ" },
        { "spanish": "ropas", "kana": "ーちゃく" },
        { "spanish": "frecuencia", "kana": "ーかい" },
        { "spanish": "objetos pequeños", "kana": "ーこ" },
        { "spanish": ["calzados", "calcetines"], "kana": ["ーそく", "ーぞく"] },
        { "spanish": "viviendas", "kana": ["ーけん", "ーげん"] },
        { "spanish": ["pisos", "plantas"], "kana": ["ーかい", "ーがい"] },
        { "spanish": ["objetos delgados y largos", "objetos largos y delgados"], "kana": ["ーほん", "ーぼん", "ーぽん"] },
        { "spanish": ["bebidas", "vasos", "copas", "tazas"], "kana": ["ーはい", "ーばい", "ーぱい"] },
        { "spanish": ["animales pequeños", "peces", "insectos"], "kana": ["ーひき", "ーびき", "ーぴき"] },

        { "spanish": "manzana", "kana": "りんご" },
        { "spanish": "mandarina", "kana": "みかん" },
        { "spanish": "sándwich", "kana": "サンドイッチ" },
        { "spanish": "curry con arroz", "kana": "カレーライス" },
        { "spanish": "helado", "kana": "アイスクリーム" },
        { "spanish": "sello postal", "kana": "きって" },
        { "spanish": "tarjeta postal", "kana": "はがき" },
        { "spanish": "sobre", "kana": "ふうとう" },
        { "spanish": "padres", "kana": "りょうしん" },
        { "spanish": "hermanas", "kana": "しまい" },
        { "spanish": "hermanos", "kana": "きょうだい" },
        { "spanish": "mi hermano mayor", "kana": "あに" },
        { "spanish": "hermano mayor", "kana": "おにいさん" },
        { "spanish": "mi hermana mayor", "kana": "あね" },
        { "spanish": "hermana mayor", "kana": "おねえさん" },
        { "spanish": "hermano pequeño", "kana": "あとうと" },
        { "spanish": "hermana pequeña", "kana": "いもうと" },
        { "spanish": "país extranjero", "kana": "がいこく" },
        { "spanish": "extranjero", "kana": "がいこくじん" },
        { "spanish": "estudiante extranjero", "kana": "りゅうがくせい" },
        { "spanish": "clase", "kana": "クラス" },
        { "spanish": "horas", "kana": "ーじかん" },
        { "spanish": "semanas", "kana": "ーしゅうかん" },
        { "spanish": "meses", "kana": "ーかげつ" },
        { "spanish": "años", "kana": "ーねん" },
        { "spanish": "alrededor de", "kana": "～ぐらい" },
        { "spanish": ["cuánto tiempo", "cuánta cantidad"], "kana": "どのくらい" },
        { "spanish": "en total", "kana": "ぜんぶで" },
        { "spanish": "todos", "kana": "みんな" },
        { "spanish": "solo", "kana": "～だけ" },
        { "spanish": "descansar", "kana": "きゅうけいします" },
        { "spanish": "descanso", "kana": "きゅうけい" },
        { "spanish": "patinar", "kana": "スケートボード" }
    ],


    "lesson_12": [
        { "spanish": ["fácil", "sencillo"], "kana": "かんたん「な」" },
        { "spanish": "cercano", "kana": "ちかい" },
        { "spanish": ["distante", "lejano"], "kana": "とおい" },
        { "spanish": ["rápido", "temprano"], "kana": "はやい" },
        { "spanish": ["tarde", "lento", "despacio"], "kana": "おそい" },
        { "spanish": ["mucha", "muchos", "mucho"], "kana": "「ひとが」おおい" },
        { "spanish": ["poca", "un poco", "escaso"], "kana": "「ひとが」すくない" },
        { "spanish": ["cálido", "templado"], "kana": "あたたかい" },
        { "spanish": "fresco", "kana": "すずしい" },
        { "spanish": "dulce", "kana": "あまい" },
        { "spanish": "picante", "kana": "からい" },
        { "spanish": "pesado", "kana": "おもい" },
        { "spanish": "ligero", "kana": "かるい" },
        { "spanish": "preferir", "kana": "「コーヒーが」いい" },
        { "spanish": ["estación", "temporada"], "kana": "きせつ" },
        { "spanish": "primavera", "kana": "はる" },
        { "spanish": "verano", "kana": "なつ" },
        { "spanish": "otoño", "kana": "あき" },
        { "spanish": "invierno", "kana": "ふゆ" },
        { "spanish": ["tiempo", "clima"], "kana": "てんき" },
        { "spanish": "lluvia", "kana": "あめ" },
        { "spanish": "nieve", "kana": "ゆき" },
        { "spanish": "nublado", "kana": "くもり" },
        { "spanish": "soleado", "kana": "はれ" },
        { "spanish": "hotel", "kana": "ホテル" },
        { "spanish": "aeropuerto", "kana": "くうごう" },
        { "spanish": ["mar", "océano"], "kana": "うみ" },
        { "spanish": "mundo", "kana": "せかい" },
        { "spanish": "fiesta", "kana": "パーティー" },
        { "spanish": ["festival", "feria"], "kana": "「お」まつり" },
        { "spanish": "estofado de ternera y verduras", "kana": "すきやき" },
        { "spanish": "sashimi", "kana": "さしみ" },
        { "spanish": "sushi", "kana": "「お」すし" },
        { "spanish": "tempura", "kana": "てんぷら" },
        { "spanish": "carne de cerdo", "kana": "ぶたにく" },
        { "spanish": "carne de pollo", "kana": "とりにく" },
        { "spanish": "carne de vaca", "kana": "ぎゅうにく" },
        { "spanish": "limón", "kana": "レモン" },
        { "spanish": "arreglo floral", "kana": "いけばな" },
        { "spanish": ["arce", "hojas coloradas de otoño"], "kana": "もみじ" },
        { "spanish": "cúal", "kana": "どちら" },
        { "spanish": "ambos", "kana": "どちらも" },
        { "spanish": ["el más", "el primero"], "kana": "いちばん" },
        { "spanish": ["mucho más", "continuamente", "sin parar"], "kana": "ずっと" },
        { "spanish": "por primera vez", "kana": "はじめて" },

        { "spanish": "aburrido", "kana": "つまらない" },
        { "spanish": "normal", "kana": "ふつう「な」" },
        { "spanish": "espinacas", "kana": "ほうれんそう" },
        { "spanish": "huevo frito", "kana": "めだまやき" },
        { "spanish": "cuando tenía", "kana": "～のとき" },
        { "spanish": ["buen tiempo", "buen clima"], "kana": "いいてんき" },
        { "spanish": "más", "kana": "より" },
        { "spanish": "más", "kana": "ほう" },
        { "spanish": "igual", "kana": "おなじ" },
        { "spanish": "meterse", "kana": "いれます" },
        { "spanish": "vivir solo", "kana": "ひとりぐらし" },
        { "spanish": "patinete eléctrico", "kana": "スクーター" },
        { "spanish": "salmón crudo", "kana": "サーモン" },
        { "spanish": "salmón cocinado", "kana": "さけ" },
        { "spanish": "atún", "kana": "まぐる" },
        { "spanish": "atún enlatado", "kana": "ツナ" },
        { "spanish": "cansado", "kana": "つかれ" },
        { "spanish": "encuesta", "kana": "アンケート" },
        { "spanish": "hacer encuesta", "kana": "アンケートします" },
        { "spanish": "primos", "kana": "いとこ" },
        { "spanish": "votar", "kana": "とうびょうします" },
        { "spanish": "elecciones", "kana": "せんきょ" },
        { "spanish": "recomendar", "kana": "おすすめ「な」" },
        { "spanish": ["mejórate", "espero que te mejores"], "kana": "おだいじに" },
        { "spanish": "vacaciones", "kana": "きゅうじつ" }
    ],


    "lesson_13": [
        { "spanish": ["jugar", "divertirse"], "kana": "あそびます" },
        { "spanish": "nadar", "kana": "およぎます" },
        { "spanish": ["recoger", "recibir"], "kana": "むかえます" },
        { "spanish": "cansarse", "kana": "つかれます" },
        { "spanish": "estar cansado", "kana": "つかれました" },
        { "spanish": "casarse", "kana": "けっこんします" },
        { "spanish": "hacer compras", "kana": "かいものします" },
        { "spanish": "comer", "kana": "しょくじします" },
        { "spanish": "pasear", "kana": "「こうえんを」さんぽします" },
        { "spanish": ["duro", "terrible"], "kana": "たいへん「な」" },
        { "spanish": "querer", "kana": "ほしい" },
        { "spanish": ["amplio", "espacioso"], "kana": "ひるい" },
        { "spanish": ["pequeño", "angosto", "estrecho"], "kana": "せまい" },
        { "spanish": "piscina", "kana": "プール" },
        { "spanish": "río", "kana": "かわ" },
        { "spanish": "bellas artes", "kana": "びじゅつ" },
        { "spanish": "pesca", "kana": "つり" },
        { "spanish": "pescar", "kana": "つりをします" },
        { "spanish": "esquí", "kana": "スキー" },
        { "spanish": "esquiar", "kana": "スキーをします" },
        { "spanish": "fin de semana", "kana": "しゅうまつ" },
        { "spanish": "año nuevo", "kana": "「お」しょうがつ" },
        { "spanish": "hacia", "kana": "～ごろ" },
        { "spanish": "algo", "kana": "なにか" },
        { "spanish": "algún lugar", "kana": "どこか" },
        { "spanish": "tener sed", "kana": "のどがかわきました" },
        { "spanish": "tener hambre", "kana": "おなかがすきました" },
        { "spanish": "garganta", "kana": "のど" },
        { "spanish": "secar", "kana": "かわきます" },
        { "spanish": "estómago", "kana": "おなか" },
        { "spanish": "estar vacío", "kana": "すきます" },
        { "spanish": "alguien", "kana": "だれか" },
        { "spanish": "algún momento", "kana": "いつか" },
        { "spanish": "matrimonio", "kana": "けっこん" },
        { "spanish": "boda", "kana": "けっこんしき" },
        { "spanish": "siguiente", "kana": "つぎ" },
        { "spanish": "estar lleno", "kana": "いっぱいです" },
        { "spanish": "mucho", "kana": "いっぱい「たくさん」" },
        { "spanish": "recoger", "kana": "うけとります" },
        { "spanish": "pagar", "kana": "はらいます" },
        { "spanish": "esperar", "kana": "まちます" },
        { "spanish": "economía", "kana": "けいざい" },
        { "spanish": "entrar", "kana": "はいります「に」" },
        { "spanish": "salir", "kana": "でます「を」" },
    ],


    "lesson_14": [
        { "spanish": "encender", "kana": "つけます" },
        { "spanish": "apagar", "kana": "けします" },
        { "spanish": "abrir", "kana": "あけます" },
        { "spanish": "cerrar", "kana": "しめます" },
        { "spanish": ["apresurarse", "darse prisa"], "kana": "いそぎます" },
        { "spanish": "esperar", "kana": "まちます" },
        { "spanish": ["tener algo en la mano", "tomar"], "kana": "もちます" },
        { "spanish": ["pasar", "dar"], "kana": "とります" },
        { "spanish": "ayudar", "kana": "てつだいます" },
        { "spanish": "llamar", "kana": "よびます" },
        { "spanish": "hablar", "kana": "はなします" },
        { "spanish": "usar", "kana": "つかいます" },
        { "spanish": ["parar", "estacionar"], "kana": "とめます" },
        { "spanish": ["mostrar", "enseñar"], "kana": "みせます" },
        { "spanish": ["enseñar, dar"], "kana": "［じゅうしょを］おしえます" },
        { "spanish": "sentarse", "kana": "すわります" },
        { "spanish": "ponerse de pie", "kana": "たちます" },
        { "spanish": "entrar", "kana": "［きっさてんに］はいります" },
        { "spanish": "salir", "kana": "［きっさてんを］でます" },
        { "spanish": "llover", "kana": "［あめが］ふります" },
        { "spanish": "sacar fotocopias", "kana": "コピーします" },
        { "spanish": ["electricidad", "luz"], "kana": "でんき" },
        { "spanish": "aire acondicionado", "kana": "エアコン" },
        { "spanish": "pasaporte", "kana": "パスポート" },
        { "spanish": "nombre", "kana": "なまえ" },
        { "spanish": ["dirección, domicilio"], "kana": "じゅうしょ" },
        { "spanish": ["mapa", "plano"], "kana": "ちず" },
        { "spanish": "sal", "kana": "しお" },
        { "spanish": "azúcar", "kana": "さとう" },
        { "spanish": ["pregunta", "problema"], "kana": "もんだい" },
        { "spanish": "respuesta", "kana": "こたえ" },
        { "spanish": ["cómo leer", "modo de lectura"], "kana": "よみかた" },
        { "spanish": ["cómo", "modo de", "manera de"], "kana": "～かた" },
        { "spanish": ["derecho", "recto"], "kana": "まっすぐ" },
        { "spanish": "despacio", "kana": "ゆっくり" },
        { "spanish": "inmediatamente", "kana": "すぐ" },
        { "spanish": "de nuevo", "kana": "また" },
        { "spanish": ["después", "más tarde"], "kana": "あとで" },
        { "spanish": "un poco más", "kana": "もうすこし" },
        { "spanish": ["más", "otro"], "kana": "もう" },
        { "spanish": "vamos", "kana": "さあ" },
        { "spanish": ["¿Cómo?", "¿Eh?"], "kana": "あれ？" },
        { "spanish": "mudanza", "kana": "ひっこし" },
        { "spanish": "explicar", "kana": "せつめいします" },
        { "spanish": "sacar", "kana": "だします" },
        { "spanish": "solo", "kana": "だけ" },
        { "spanish": "girar", "kana": "まわります" },
        { "spanish": "recoger a alguien", "kana": "むかえます" },
        { "spanish": "montar", "kana": "のります" },
        { "spanish": "reservar", "kana": "よやくします" },
        { "spanish": "jefe de departamento", "kana": "ぶちょう" },
        { "spanish": "jefe", "kana": "かちょう" },
        { "spanish": "materiales", "kana": "しりょう" },
        { "spanish": "conductor", "kana": "うんてんしゅ" },
        { "spanish": "semáforo", "kana": "しんごう" },
        { "spanish": "lavar", "kana": "あらいます" },
        { "spanish": "tejado", "kana": "やね" },
        { "spanish": "calle", "kana": "みち" },
        { "spanish": "correa", "kana": "リード" },
        { "spanish": "sin", "kana": "なし" },
        { "spanish": "sopa de cerdo", "kana": ["ぶたじる", "とんじる"] },
        { "spanish": "estofado", "kana": "ツチュー" }
    ],


    "lesson_15": [
        { "spanish": ["poner", "colocar"], "kana": "おきます" },
        { "spanish": ["hacer", "producir"], "kana": "つくります" },
        { "spanish": "vender", "kana": "うります" },
        { "spanish": ["enterarse", "saber", "conocer"], "kana": "しります" },
        { "spanish": ["vivir", "residir"], "kana": "すみます" },
        { "spanish": "investigar", "kana": "けんきゅうします" },
        { "spanish": ["recordar", "acordarse"], "kana": "おもいだします" },
        { "spanish": ["materiales", "datos"], "kana": "しりょう" },
        { "spanish": "catálogo", "kana": "カタログ" },
        { "spanish": "horario", "kana": "じこくひょう" },
        { "spanish": "ropa", "kana": "ふく" },
        { "spanish": "productos", "kana": "せいひん" },
        { "spanish": "software", "kana": "ソフト" },
        { "spanish": "diccionario electrónico", "kana": "でんしじしょ" },
        { "spanish": "economía", "kana": "けいざい" },
        { "spanish": "ayuntamiento", "kana": "しやくしょ" },
        { "spanish": ["bachillerato", "escuela secundaria superior"], "kana": "こうこう" },
        { "spanish": ["dentista", "clínical dental"], "kana": "はいしゃ" },
        { "spanish": "soltero", "kana": "どくしん" },
        { "spanish": ["perdón", "lo siento"], "kana": "すみません" },
        { "spanish": ["señoras y señores", "ustedes"], "kana": "みなさん" },
        { "spanish": "casarse", "kana": "けっこんします" },
        { "spanish": "cosas", "kana": "せいひん" },
        { "spanish": "usar", "kana": "つかいます" },
        { "spanish": "biología", "kana": "せいぶつがく" },
        { "spanish": ["pueblo", "campo"], "kana": "いなか" },
        { "spanish": "capital", "kana": "しゅと" },
        { "spanish": "cambio de divisa", "kana": ["りょうがえ", "かわせ"] },
        { "spanish": ["jubilado", "renunciar"], "kana": "たいしょくします" },
        { "spanish": "vehículo", "kana": "じどうしゃ" }
    ],


    "lesson_16": [
        { "spanish": "subir", "kana": "「でんしゃに」のります" },
        { "spanish": "bajar", "kana": "「でんしゃお」おります" },
        { "spanish": ["trasbordo", "transbordo"], "kana": "のりかえます" },
        { "spanish": "ducharse", "kana": "「シャワーお」あびます" },
        { "spanish": ["meter", "introducir", "insertar"], "kana": "いれます" },
        { "spanish": ["sacar", "entregar", "presentar", "enviar"], "kana": "だします" },
        { "spanish": ["retirar", "sacar"], "kana": "「おかねお」おろします" },
        { "spanish": ["entrar", "ingresar"], "kana": "「だいがくに」はいります" },
        { "spanish": "graduarse", "kana": "「だいがくお」でます" },
        { "spanish": ["presionar", "empujar", "pulsar"], "kana": "おします" },
        { "spanish": "beber alcohol", "kana": "のみます" },
        { "spanish": ["empezar", "comenzar", "iniciar"], "kana": "はじめます" },
        { "spanish": "visitar", "kana": "けんがくします" },
        { "spanish": ["llamar por teléfono", "telefonear"], "kana": "でんわします" },
        { "spanish": "joven", "kana": "わかい" },
        { "spanish": "largo", "kana": "ながい" },
        { "spanish": "corto", "kana": "みじかい" },
        { "spanish": ["claro", "luminoso"], "kana": "あかるい" },
        { "spanish": "oscuro", "kana": "くらい" },
        { "spanish": "cuerpo", "kana": "からだ" },
        { "spanish": ["cabeza", "cerebro"], "kana": "あたま" },
        { "spanish": "cabello", "kana": "かみ" },
        { "spanish": "cara", "kana": "かお" },
        { "spanish": ["ojo", "ojos"], "kana": "め" },
        { "spanish": ["oreja", "orejas"], "kana": "みみ" },
        { "spanish": "nariz", "kana": "はな" },
        { "spanish": "boca", "kana": "くち" },
        { "spanish": ["diente", "dientes"], "kana": "は" },
        { "spanish": ["pierna", "piernas", "pie", "pies"], "kana": "あし" },
        { "spanish": "estómago", "kana": "おなか" },
        { "spanish": ["altura", "estatura"], "kana": "せ" },
        { "spanish": "servicio", "kana": "サービス" },
        { "spanish": "jogging", "kana": "ジョギング" },
        { "spanish": "ducha", "kana": "シャワー" },
        { "spanish": ["verde", "zona verde"], "kana": "みどり" },
        { "spanish": "templo budista", "kana": "「お」てら" },
        { "spanish": "santuario sintoísta", "kana": "じんじゃ" },
        { "spanish": "número", "kana": "ーばん" },
        { "spanish": ["cómo", "de qué manera"], "kana": ["どうやって", "なんで"] },
        { "spanish": "cuál", "kana": "どの～" },
        { "spanish": "cuál", "kana": "どれ" },
        { "spanish": "increíble", "kana": "すごいですね" },
        { "spanish": "todavía", "kana": "まだまだです" },
        { "spanish": ["bajo", "pequeño"], "kana": "ちさい" },
        { "spanish": "botón", "kana": "ボタン" }
    ],


    "lesson_17": [
        { "spanish": "memorizar", "kana": "おぼえます" },
        { "spanish": "olvidar", "kana": "わすれます" },
        { "spanish": "perder", "kana": "なくします" },
        { "spanish": "pagar", "kana": "はらいます" },
        { "spanish": "devolver", "kana": "かえします" },
        { "spanish": ["salir", "ir", "venir", "volver"], "kana": "「へ」でかけます" },
        { "spanish": "quitarse", "kana": "ぬぎます" },
        { "spanish": "llevar", "kana": "もっていきます" },
        { "spanish": "traer", "kana": "もってきます" },
        { "spanish": "preocuparse", "kana": "しんぱいします" },
        { "spanish": "trabajar horas extra", "kana": "ざんぎょうします" },
        { "spanish": "ir de viaje de trabajo", "kana": "しゅっちょうします" },
        { "spanish": ["tomar medicinas", "medicarse"], "kana": "「くすりを」のみます" },
        { "spanish": ["tomar un baño", "bañarse"], "kana": "「おふろに」はいります" },
        { "spanish": "importante", "kana": "たいせつ「な」" },
        { "spanish": "estar bien", "kana": "だいじょうぶ「な」" },
        { "spanish": "peligroso", "kana": "あぶない" },
        { "spanish": "prohibido fumar", "kana": "きんえん" },
        { "spanish": "tarjeta del seguro de salud", "kana": "けんこうほけんしょう" },
        { "spanish": "fiebre", "kana": "ねつ" },
        { "spanish": "enfermedad grave", "kana": "びょうき" },
        { "spanish": ["medicina", "medicamento", "pastillas"], "kana": "くすり" },
        { "spanish": ["chaqueta", "abrigo"], "kana": "うわぎ" },
        { "spanish": "ropa interior", "kana": "したぎ" },
        { "spanish": "unos días", "kana": "２，３にち" },
        { "spanish": "unos", "kana": "２，３～" },
        { "spanish": "antes de", "kana": "～までに" },
        { "spanish": ["por eso", "entonces"], "kana": "ですから" },
        { "spanish": "preocupación", "kana": "しんぱい" },
        { "spanish": "horas extra", "kana": "ざんぎょう" },
        { "spanish": "seguro", "kana": "ほけん" },
        { "spanish": "tarjeta", "kana": "しょう" },

        { "spanish": "bañera", "kana": "おふろ" },
        { "spanish": "platos", "kana": "おさら" },
        { "spanish": "país extranjero", "kana": "かいがい" },
        { "spanish": "escuela", "kana": "しゅうちょう" },
        { "spanish": "documento", "kana": "しりょう" },
        { "spanish": "tortilla", "kana": "オムレツ" },
        { "spanish": "arroz blanco aguado", "kana": "おかゆ" },
        { "spanish": ["comprobar", "confirmar"], "kana": "かくにんします" },
        { "spanish": "que te mejores", "kana": "おだいじに" }
    ],



    "lesson_18": [
        { "spanish": ["poder", "ser capaz de"], "kana": "できます" },
        { "spanish": "lavar", "kana": "あらいます" },
        { "spanish": "tocar", "kana": "ひきます" },
        { "spanish": "cantar", "kana": "うたいます" },
        { "spanish": ["coleccionar", "reunir"], "kana": "あつめます" },
        { "spanish": ["tirar", "desechar"], "kana": "すてます" },
        { "spanish": ["cambiar", "reemplazar"], "kana": "かえます" },
        { "spanish": "conducir", "kana": "うんてんします" },
        { "spanish": "reservar", "kana": "よやくします" },
        { "spanish": "piano", "kana": "ピアノ" },
        { "spanish": "metro", "kana": "メートル" },
        { "spanish": "dinero en efectivo", "kana": "げんきん" },
        { "spanish": ["afición", "pasatiempo"], "kana": "しゅみ" },
        { "spanish": "diario", "kana": "にっき" },
        { "spanish": "oración", "kana": "おいのり" },
        { "spanish": "jefe de sección", "kana": "かちょう" },
        { "spanish": ["gerente de división", "gerente de departamento"], "kana": "ぶちょう" },
        { "spanish": ["director ejecutivo", "presidente", "director general de una empresa"], "kana": "しゃちょう" },
        { "spanish": "animal", "kana": "どうぶつ" },
        { "spanish": "caballo", "kana": "うま" },
        { "spanish": "internet", "kana": "インターネット" },

        { "spanish": ["por supuesto", "claro"], "kana": "ぜひ" },
        { "spanish": "estar feliz", "kana": "うれしい" },
        { "spanish": "comida china", "kana": "ちゅうか「りょうり」" },
        { "spanish": "otro día", "kana": "べつのひ" },
        { "spanish": "uniforme", "kana": "ユニフォーム" },
        { "spanish": "Navidad", "kana": "クリスマスイブ" },
        { "spanish": "salón", "kana": ["リビング", "いま"] },
        { "spanish": "abuelos", "kana": "そふぼ" },
        { "spanish": "niebla", "kana": "きり" },
        { "spanish": "Nochevieja", "kana": "おおみそか" },
        { "spanish": "casa antigua de alquiler", "kana": "こみんか" },
        { "spanish": "celebrar los 20 años", "kana": "せいじんのひ" },
        { "spanish": ["rezar", "orar"], "kana": "おいのりします" },
        { "spanish": "zoo", "kana": "どうぶつえん" },
        { "spanish": "poco", "kana": ["あんまり", "あまり"] },
        { "spanish": "mi alumno", "kana": "せいと" },
        { "spanish": "natación", "kana": "すいえい" },
        { "spanish": "no es fácil", "kana": "なかなか" },
        { "spanish": "ruidoso", "kana": ["うるさい", "やかましい"] },
        { "spanish": "plan", "kana": "よてい" },
        { "spanish": "propósito", "kana": "もくひょう" },
        { "spanish": "antes de", "kana": "まえに" },
        { "spanish": "cepillarse los dientes", "kana": "「ほを」みがきます" },
        { "spanish": "personalidad", "kana": "せいかく" },
        { "spanish": "planear", "kana": "「よていを」つくります" },
        { "spanish": "época", "kana": "じだい" },
        { "spanish": "otra vez", "kana": "もういちど" },
        { "spanish": "me encantaría", "kana": "ぜひもいちど" },
        { "spanish": "peluche", "kana": "ぬいぐるみ" },
        { "spanish": "especialmente", "kana": "とくに" },
        { "spanish": "historia", "kana": "れきし" },
        { "spanish": "saltear", "kana": "やきます" },
        { "spanish": "matemáticas", "kana": "すうがく" },
        { "spanish": "educación física", "kana": "たいいく" },
        { "spanish": "crecer", "kana": "ふえます" },
        { "spanish": "estricto", "kana": "きびし" },
        { "spanish": "terraza", "kana": "テラス" },
        { "spanish": "comida del comedor", "kana": "きゅうしょく" }

    ],



    "lesson_19": [
        { "spanish": ["subir", "escalar"], "kana": "「やまに」のぼります" },
        { "spanish": ["alojarse", "hospedarse"], "kana": "「ホテルに」とまります" },
        { "spanish": "limpiar", "kana": "そうじします" },
        { "spanish": ["lavar la ropa", "hacer la colada"], "kana": "せんたくします" },
        { "spanish": ["convertirse", "hacerse", "llegar"], "kana": "なります" },
        { "spanish": "tener sueño", "kana": "ねむい" },
        { "spanish": "fuerte", "kana": "つよい" },
        { "spanish": "débil", "kana": "よわい" },
        { "spanish": ["práctica", "ensayo"], "kana": "れんしゅう" },
        { "spanish": ["practicar", "ensayar"], "kana": "れんしゅう「を」します" },
        { "spanish": "golf", "kana": "ゴルフ" },
        { "spanish": "sumo", "kana": "すもう" },
        { "spanish": "practicar sumo", "kana": "すもうします" },
        { "spanish": "ceremonia del té", "kana": "おちゃ" },
        { "spanish": "hacer ceremonia del té", "kana": "おちゃをします" },
        { "spanish": ["día", "fecha"], "kana": "ひ" },
        { "spanish": ["forma", "condición"], "kana": "ちょうし" },
        { "spanish": "una vez", "kana": "いちど" },
        { "spanish": "nunca", "kana": "いちども" },
        { "spanish": "poco a poco", "kana": "だんだん" },
        { "spanish": ["dentro de poco", "pronto"], "kana": "もうすぐ" },
        { "spanish": ["gracias a usted", "gracias a Dios"], "kana": "おかげさまで" },
        { "spanish": ["pero", "sin embargo"], "kana": ["でも", "けど"] },

        { "spanish": "lavadora", "kana": "せんたくき" },
        { "spanish": "olor", "kana": "におい" },
        { "spanish": "marear", "kana": "よいます" },
        { "spanish": "teleférico", "kana": "ロープウェー" },
        { "spanish": "guía", "kana": "ガイド" },
        { "spanish": "elegante", "kana": "エレガント" },
        { "spanish": ["dejar de funcionar", "estropearse"], "kana": "こしょうします" }
    ],



    "lesson_20": [
        { "spanish": ["necesitar", "requerir"], "kana": "「ビザが」いります" },
        { "spanish": ["buscar", "averiguar", "investigar"], "kana": "しらべます" },
        { "spanish": "reparar", "kana": "しゅうりします" },
        { "spanish": "yo", "kana": "ぼく" },
        { "spanish": "tú", "kana": "きみ" },
        { "spanish": "señor", "kana": "～くん" },
        { "spanish": "sí", "kana": "うん" },
        { "spanish": "no", "kana": "ううん" },
        { "spanish": ["palabra", "lenguaje", "idioma"], "kana": "ことば" },
        { "spanish": "kimono", "kana": "きもの" },
        { "spanish": ["visa", "visado"], "kana": "ビザ" },
        { "spanish": ["comienzo", "principio"], "kana": "はじめ" },
        { "spanish": "fin", "kana": "おわり" },
        { "spanish": ["por aquí", "aquí"], "kana": "こっち" },
        { "spanish": ["por ahí", "ahí"], "kana": "そっち" },
        { "spanish": ["por allí", "allí"], "kana": "あっち" },
        { "spanish": ["cuál", "dónde", "por dónde"], "kana": "どっち" },
        { "spanish": "todos juntos", "kana": "みんなで" },
        { "spanish": "pero", "kana": "～けど" },
        { "spanish": ["estoy satisfecho", "estoy lleno"], "kana": "おなかがいっぱいです" },

        { "spanish": "lo siento pero me voy primero", "kana": "おさきにしつれいします" },
        { "spanish": "ayuntamiento", "kana": "しやくしょ" },
        { "spanish": "cómo", "kana": "どう" },
        { "spanish": "cómo fue", "kana": "どうだった" },
        { "spanish": ["vamos a", "hagámoslo"], "kana": "そうします" },
        { "spanish": "ida y vuelta", "kana": "おうふく" },
        { "spanish": "?", "kana": "はてな" },
        { "spanish": "!", "kana": "ビックリマーク" },
        { "spanish": "si no te importa", "kana": "よかったら" },
        { "spanish": "más o menos cuando", "kana": "いつごろ" },
        { "spanish": "creo que no", "kana": "ないかも" }
    ],



    "lesson_21": [
        { "spanish": ["creer", "opinar"], "kana": "おもいます" },
        { "spanish": "decir", "kana": "いいます" },
        { "spanish": "ganar", "kana": "かちます" },
        { "spanish": ["perder", "ser derrotado"], "kana": "まけます" },
        { "spanish": ["haber", "tener lugar", "realizarse"], "kana": "あります" },
        { "spanish": "ser útil", "kana": "やくにたちます" },
        { "spanish": ["funcionar", "moverse"], "kana": "うごきます" },
        { "spanish": ["dimitir", "dejar"], "kana": "やめます" },
        { "spanish": ["prestar atención", "tener cuidado"], "kana": "きをつけます" },
        { "spanish": "estudiar en el extranjero", "kana": "りゅうがくします" },
        { "spanish": ["innecesario", "inútil"], "kana": "むだ「な」" },
        { "spanish": "inconveniente", "kana": "ふべん「な」" },
        { "spanish": ["terrible", "maravilloso", "impresionante"], "kana": "すごい" },
        { "spanish": "verdad", "kana": "ほんとう" },
        { "spanish": "mentira", "kana": "うそ" },
        { "spanish": ["coche", "automóvil"], "kana": "じどうしゃ" },
        { "spanish": ["transporte", "tráfico"], "kana": "こうつう" },
        { "spanish": ["coste de vida", "costo de vida"], "kana": "ぶっか" },
        { "spanish": ["transmisión", "anuncio"], "kana": "ほうそう" },
        { "spanish": "noticia", "kana": "ニュース" },
        { "spanish": "anime", "kana": "アニメ" },
        { "spanish": ["manga", "cómic"], "kana": "マンガ" },
        { "spanish": "diseño", "kana": "デザイン" },
        { "spanish": "sueño", "kana": "ゆめ" },
        { "spanish": "genio", "kana": "てんさい" },
        { "spanish": "partido", "kana": "しあい" },
        { "spanish": "jugar un partido", "kana": "しあいをします" },
        { "spanish": "opinión", "kana": "いけん" },
        { "spanish": ["discurso", "cuento"], "kana": "はなし" },
        { "spanish": "Tierra", "kana": "ちきゅう" },
        { "spanish": "luna", "kana": "つき" },
        { "spanish": ["últimamente", "estos días"], "kana": "さいきん" },
        { "spanish": ["probablemente", "quizás"], "kana": "たぶん" },
        { "spanish": ["sin falta", "seguramente"], "kana": "きっと" },
        { "spanish": ["realmente", "de verdad"], "kana": "ほんとうに" },
        { "spanish": "no tan", "kana": "そんなに" },
        { "spanish": ["sobre", "con respecto a"], "kana": "～について" },

        { "spanish": "reformar", "kana": "リフォームします" },
        { "spanish": ["freir", "regalar"], "kana": "あげます" },
        { "spanish": "última dirección", "kana": "さいしゅうち" },
        { "spanish": "tener suficiente", "kana": "たります" },
        { "spanish": "por supuesto", "kana": "もちろん" },
        { "spanish": "precio inflado", "kana": "ぼったくり" },
        { "spanish": "cebolla", "kana": "たまねぎ" },
        { "spanish": ["la verdad", "realmente"], "kana": "じつは" },
        { "spanish": "último", "kana": "さいご" },
        { "spanish": "puntual", "kana": "じかんどうり" },
        { "spanish": "ya casi", "kana": "そろそろ" },
        { "spanish": "sueldo", "kana": "きゅうりょう" },
        { "spanish": "estafa", "kana": "さぎ" },
        { "spanish": "lo creo", "kana": "そうだとおもいます" },
        { "spanish": "no lo creo", "kana": "ちがうとおもいます" },
        { "spanish": "tiempo", "kana": "きかん" }
    ],



    "lesson_22": [
        { "spanish": "ponerse camisa", "kana": "「ふくを」きます" },
        { "spanish": ["ponerse zapatos", "ponerse pantalones"], "kana": "「くつを」はきます" },
        { "spanish": "ponerse sombrero", "kana": "「ぼうしを」かぶります" },
        { "spanish": "ponerse gafas", "kana": "「めがねを」かけます" },
        { "spanish": "ponerse corbata", "kana": ["「ネクタイを」します", "「ネクタイを」しめます"] },
        { "spanish": "nacer", "kana": "うまれます" },
        { "spanish": ["abrigo", "sobretodo", "gabardina"], "kana": "コ－ト" },
        { "spanish": ["suéter", "pulóver", "jersey"], "kana": "セーター" },
        { "spanish": "traje", "kana": "スーツ" },
        { "spanish": ["sombrero", "gorra"], "kana": "ぼうし" },
        { "spanish": ["gafas", "lentes"], "kana": "めがね" },
        { "spanish": "pastel", "kana": "ケーキ" },
        { "spanish": "comida preparada en una caja", "kana": "「お」べんとう" },
        { "spanish": "robot", "kana": "ロボット" },
        { "spanish": "humor", "kana": "ユーモア" },
        { "spanish": "conveniencia", "kana": "つごう" },
        { "spanish": "frecuentemente", "kana": "よく" },
        { "spanish": ["bueno", "veamos"], "kana": "えーと" },
        { "spanish": ["felicidades", "felicitaciones"], "kana": "おめでとう「ございます」" },

        { "spanish": "ponerse accesorio", "kana": "「とけいを」つけます" },
        { "spanish": "taburete", "kana": "スツール" },
        { "spanish": ["grabación", "filmación"], "kana": "えいぞう" },
        { "spanish": "necesitar", "kana": "いいます" },
        { "spanish": "varias cosas", "kana": "いろんなこと" },
        { "spanish": "mentir", "kana": "うそをつきます" },
        { "spanish": "aprender", "kana": "まなびます" },
        { "spanish": "abuelos", "kana": "そふぼ" },
        { "spanish": "pesadilla", "kana": "あくむ" },
        { "spanish": "ver una pesadilla", "kana": "あくむをみます" },
        { "spanish": "calcetines", "kana": "くつした" },
        { "spanish": "ceremonia de adultez", "kana": "せいじんしき" },
        { "spanish": "ceremonia", "kana": "しき" },
        { "spanish": "adulto", "kana": "せいじん" },
        { "spanish": "sueldo", "kana": "きゅうりょう" },
        { "spanish": "beneficios", "kana": "ふくりこうせい" },
        { "spanish": "precio alquiler", "kana": "やちん" },
        { "spanish": "entonces", "kana": "では" },
        { "spanish": "salón estilo japonés", "kana": "わしつ" },
        { "spanish": "armario empotrado", "kana": "おしいれ" },
        { "spanish": "buscar", "kana": "さがします" },
        { "spanish": "garaje", "kana": "ちゅうしゃじょう" },
        { "spanish": "trastero", "kana": "ものおき" },
        { "spanish": "polen", "kana": "かふん" }
    ],



    "lesson_23": [
        { "spanish": "preguntar", "kana": "ききます" },
        { "spanish": "girar", "kana": "まわします" },
        { "spanish": ["tirar", "jalar", "enfermar"], "kana": "ひきます" },
        { "spanish": "cambiar", "kana": "かえます" },
        { "spanish": "tocar", "kana": "さわります" },
        { "spanish": "salir", "kana": "でます" },
        { "spanish": "caminar", "kana": "あるきます" },
        { "spanish": "cruzar", "kana": "わたります" },
        { "spanish": ["doblar", "girar"], "kana": "まがります" },
        { "spanish": ["solitario", "sentirse solo"], "kana": "さびしい" },
        { "spanish": "agua caliente", "kana": "「お」ゆ" },
        { "spanish": "sonido", "kana": "おと" },
        { "spanish": ["tamaño", "talla"], "kana": "サイズ" },
        { "spanish": "avería", "kana": "こしょう" },
        { "spanish": "averiarse", "kana": "こしょうします" },
        { "spanish": ["calle", "camino"], "kana": "みち" },
        { "spanish": "cruce", "kana": "こうさてん" },
        { "spanish": "semáforo", "kana": "しんごう" },
        { "spanish": "esquina", "kana": "かど" },
        { "spanish": "puente", "kana": "はし" },
        { "spanish": ["estacionamiento", "aparcamiento"], "kana": "ちゅうしゃじょう" },
        { "spanish": "edificio", "kana": "たてもの" },
        { "spanish": "muchas veces", "kana": "なんかいも" },
        { "spanish": ["el", "la"], "kana": "ーめ" },

        { "spanish": "lanzar", "kana": "なげます" },
        { "spanish": "casero", "kana": "やぬし" },
        { "spanish": ["ir sin permiso de los padres", "fugarse"], "kana": "かけおち「します」" },
        { "spanish": "buscar", "kana": "さがします" },
        { "spanish": "político", "kana": "せいじか" },
        { "spanish": "pintar", "kana": "ぬります" },
        { "spanish": "cajones", "kana": "ひきだし" },
        { "spanish": "cantidad", "kana": "りょう" },
        { "spanish": "mucho", "kana": "おおい" },
        { "spanish": "engordar", "kana": "ふとります" },
        { "spanish": "feliz", "kana": "しあわせ「な」" },
        { "spanish": "electrodoméstico", "kana": "かでん" },
        { "spanish": "globo", "kana": "ふうせん" },
        { "spanish": "museo", "kana": "はくぶつかん" },
        { "spanish": "ambos", "kana": "りょうほう" }
    ],



    "lesson_24": [
        { "spanish": "darme", "kana": "くれます" },
        { "spanish": ["reparar", "arreglar", "corregir"], "kana": "なおします" },
        { "spanish": "llevar", "kana": "つれていきます" },
        { "spanish": "traer", "kana": "つれてきます" },
        { "spanish": ["acompañar", "llevar"], "kana": "おくります" },
        { "spanish": "presentar", "kana": "しょうかいします" },
        { "spanish": ["guiar por", "indicar el camino"], "kana": "あんないします" },
        { "spanish": "explicar", "kana": "せつめいします" },
        { "spanish": ["abuelo", "anciano"], "kana": ["おじいさん", "おじいちゃん"] },
        { "spanish": ["abuela", "anciana"], "kana": ["おばあさん", "おばあちゃん"] },
        { "spanish": "preparación", "kana": "じゅんび" },
        { "spanish": "mudanza", "kana": "ひっこし" },
        { "spanish": ["dulce", "golosina"], "kana": "「お」かし" },
        { "spanish": "hospedaje en casa de una familia", "kana": "ホームステイ" },
        { "spanish": "todo", "kana": ["ぜんぶ", "すべて"] },
        { "spanish": ["por uno mismo", "por sí mismo"], "kana": "じぶんで" },

        { "spanish": "presentación", "kana": "しょうかい" },
        { "spanish": "ramo de flores", "kana": "はなたば" },
        { "spanish": "anillo", "kana": "ゆびわ" },
        { "spanish": "dedo", "kana": "ゆび" },
        { "spanish": "otro", "kana": "ほか" },
        { "spanish": "otro lugar", "kana": "ほかのところ" },
        { "spanish": "otro día", "kana": "ほかのひ" },
        { "spanish": "separado", "kana": "べつべつに" },
        { "spanish": "quedarse en habitaciones separadas", "kana": "べつべつにとまります" },
        { "spanish": "primer sueldo", "kana": "しょにんきゅう" },
        { "spanish": "muebles", "kana": "かぐ" },
        { "spanish": "alquiler", "kana": "やちん" },
        { "spanish": "croissant", "kana": "クㇿクッサン" }
    ],



    "lesson_25": [
        { "spanish": ["pensar", "considerar"], "kana": "かんがえます" },
        { "spanish": "llegar", "kana": "つきます" },
        { "spanish": "envejecer", "kana": "としをとります" },
        { "spanish": "ser suficiente", "kana": "たります" },
        { "spanish": ["zona rural", "pueblo natal"], "kana": "いなか" },
        { "spanish": "oportunidad", "kana": "チャンス" },
        { "spanish": "cien millones", "kana": "おく" },
        { "spanish": "si", "kana": "もし" },
        { "spanish": ["significado", "sentido"], "kana": "いみ" },

        { "spanish": "nuevo", "kana": "しんちゃ" },
        { "spanish": ["segunda mano", "seminuevo"], "kana": "ちゅうこしゃ" },
        { "spanish": "protector solar", "kana": "ひやけどぬ" },
        { "spanish": "almohada", "kana": "まくら" },
        { "spanish": "enfadarse", "kana": "むかつきます" },
        { "spanish": "pasar tiempo", "kana": "たちます" }
    ],



    "verbos": [
        { "spanish": "levantarse", "kana": "おきます" },
        { "spanish": ["acostarse", "ir a la cama"], "kana": "ねます" },
        { "spanish": "trabajar", "kana": "はたらきます" },
        { "spanish": ["descansar", "estar de vacaciones", "ausentarse", "faltar"], "kana": "やすみます" },
        { "spanish": "estudiar", "kana": "べんきょします" },
        { "spanish": "terminar", "kana": "おわります" },
        { "spanish": "ir", "kana": "いきます" },
        { "spanish": "venir", "kana": "きます" },
        { "spanish": "volver, regresar, irse a casa", "kana": "かえります" },
        { "spanish": "comer", "kana": "たべます" },
        { "spanish": ["beber", "tomar"], "kana": "のみます" },
        { "spanish": "fumar", "kana": "すいます" },
        { "spanish": ["ver", "mirar"], "kana": "みます" },
        { "spanish": ["oír", "escuchar", "preguntar"], "kana": "ききます" },
        { "spanish": "leer", "kana": "よみます" },
        { "spanish": ["escribir", "dibujar"], "kana": "かきます" },
        { "spanish": "comprar", "kana": "かいます" },
        { "spanish": "sacar fotos", "kana": "しゃしんをとります" },
        { "spanish": "hacer", "kana": "します" },
        { "spanish": ["ver a", "encontrarse con"], "kana": "あいます" },
        { "spanish": "cortar", "kana": "きります" },
        { "spanish": "recibir", "kana": "もらいます" },
        { "spanish": "prestar", "kana": "かします" },
        { "spanish": "tomar prestado", "kana": "かります" },
        { "spanish": "enseñar", "kana": "おしえます" },
        { "spanish": "aprender", "kana": "ならいます" },
        { "spanish": ["hacer una llamada", "llamar"], "kana": "でんわをかけます" },
        { "spanish": ["entender", "comprender"], "kana": "わかります" },
        { "spanish": ["estar", "haber", "existir"], "kana": "あります" },
        { "spanish": ["estar", "haber", "existir", "permanecer"], "kana": "います" },
        { "spanish": "construir", "kana": "たてます" },
        { "spanish": ["montar", "subir"], "kana": "のります" },
        { "spanish": "pasear", "kana": "さんぽをします" },
        { "spanish": "tener hijos", "kana": "こどもがいます" },
        { "spanish": ["tardar", "costar"], "kana": "かかります" },
        { "spanish": "descansar", "kana": "きゅうけいします" },
        { "spanish": "hacer encuesta", "kana": "アンケートします" },
        { "spanish": "votar", "kana": "とうびょうします" },
        { "spanish": ["jugar", "divertirse"], "kana": "あそびます" },
        { "spanish": "nadar", "kana": "およぎます" },
        { "spanish": ["recoger", "recibir"], "kana": "むかえます" },
        { "spanish": ["cansarse", "estar cansado"], "kana": "つかれます" },
        { "spanish": "casarse", "kana": "けっこんします" },
        { "spanish": "hacer compras", "kana": "かいものします" },
        { "spanish": "comer", "kana": "しょくじします" },
        { "spanish": "pescar", "kana": "つりをします" },
        { "spanish": "esquiar", "kana": "スキーをします" },
        { "spanish": "secar", "kana": "かわきます" },
        { "spanish": "estar vacío", "kana": "すきます" },
        { "spanish": "recoger", "kana": "うけとります" },
        { "spanish": "pagar", "kana": "はらいます" },
        { "spanish": "esperar", "kana": "まちます" },
        { "spanish": "encender", "kana": "つけます" },
        { "spanish": "apagar", "kana": "けします" },
        { "spanish": "abrir", "kana": "あけます" },
        { "spanish": "cerrar", "kana": "しめます" },
        { "spanish": ["apresurarse", "darse prisa"], "kana": "いそぎます" },
        { "spanish": ["tener algo en la mano", "tomar"], "kana": "もちます" },
        { "spanish": ["pasar", "dar"], "kana": "とります" },
        { "spanish": "ayudar", "kana": "てつだいます" },
        { "spanish": "llamar", "kana": "よびます" },
        { "spanish": "hablar", "kana": "はなします" },
        { "spanish": "usar", "kana": "つかいます" },
        { "spanish": ["parar", "estacionar"], "kana": "とめます" },
        { "spanish": ["mostrar", "enseñar"], "kana": "みせます" },
        { "spanish": "sentarse", "kana": "すわります" },
        { "spanish": "ponerse de pie", "kana": "たちます" },
        { "spanish": "salir", "kana": "でます" },
        { "spanish": "llover", "kana": "あめがふります" },
        { "spanish": "sacar fotocopias", "kana": "コピーします" },
        { "spanish": "explicar", "kana": "せつめいします" },
        { "spanish": "girar", "kana": "まわります" },
        { "spanish": "reservar", "kana": "よやくします" },
        { "spanish": "lavar", "kana": "あらいます" },
        { "spanish": ["poner", "colocar"], "kana": "おきます" },
        { "spanish": ["crear", "hacer", "producir"], "kana": "つくります" },
        { "spanish": "vender", "kana": "うります" },
        { "spanish": ["enterarse", "saber", "conocer"], "kana": "しります" },
        { "spanish": ["vivir", "residir"], "kana": "すみます" },
        { "spanish": "investigar", "kana": "けんきゅうします" },
        { "spanish": ["recordar", "acordarse"], "kana": "おもいだします" },
        { "spanish": ["jubilado", "renunciar"], "kana": "たいしょくします" },
        { "spanish": "subir", "kana": "でんしゃにのります" },
        { "spanish": "bajar", "kana": "でんしゃおおります" },
        { "spanish": ["trasbordo", "transbordo"], "kana": "のりかえます" },
        { "spanish": "ducharse", "kana": "シャワーおあびます" },
        { "spanish": ["meter", "introducir", "insertar"], "kana": "いれます" },
        { "spanish": ["sacar", "entregar", "presentar", "enviar"], "kana": "だします" },
        { "spanish": ["retirar", "sacar"], "kana": "おろします" },
        { "spanish": ["entrar", "ingresar"], "kana": "はいります" },
        { "spanish": "graduarse", "kana": "だいがくおでます" },
        { "spanish": ["presionar", "empujar", "pulsar"], "kana": "おします" },
        { "spanish": ["empezar", "comenzar", "iniciar"], "kana": "はじめます" },
        { "spanish": "visitar", "kana": "けんがくします" },
        { "spanish": ["llamar por teléfono", "telefonear"], "kana": "でんわします" },
        { "spanish": "memorizar", "kana": "おぼえます" },
        { "spanish": "olvidar", "kana": "わすれます" },
        { "spanish": "perder", "kana": "なくします" },
        { "spanish": "devolver", "kana": "かえします" },
        { "spanish": ["salir", "ir", "venir", "volver"], "kana": "でかけます" },
        { "spanish": "quitarse", "kana": "ぬぎます" },
        { "spanish": "llevar", "kana": "もっていきます" },
        { "spanish": "traer", "kana": "もってきます" },
        { "spanish": "preocuparse", "kana": "しんぱいします" },
        { "spanish": "trabajar horas extra", "kana": "ざんぎょうします" },
        { "spanish": "ir de viaje de trabajo", "kana": "しゅっちょうします" },
        { "spanish": ["tomar medicinas", "medicarse"], "kana": "くすりをのみます" },
        { "spanish": ["tomar un baño", "bañarse"], "kana": "おふろにはいります" },
        { "spanish": ["comprobar", "confirmar"], "kana": "かくにんします" },
        { "spanish": ["poder", "ser capaz de"], "kana": "できます" },
        { "spanish": "tocar", "kana": "ひきます" },
        { "spanish": "cantar", "kana": "うたいます" },
        { "spanish": ["coleccionar", "reunir"], "kana": "あつめます" },
        { "spanish": ["tirar", "desechar"], "kana": "すてます" },
        { "spanish": ["cambiar", "reemplazar"], "kana": "かえます" },
        { "spanish": "conducir", "kana": "うんてんします" },
        { "spanish": ["rezar", "orar"], "kana": "おいのりします" },
        { "spanish": "cepillarse los dientes", "kana": "はをみがきます" },
        { "spanish": "planear", "kana": "よていをつくります" },
        { "spanish": "saltear", "kana": "やきます" },
        { "spanish": "crecer", "kana": "ふえます" },
        { "spanish": ["subir", "escalar"], "kana": "やまにのぼります" },
        { "spanish": ["alojarse", "hospedarse"], "kana": "ホテルにとまります" },
        { "spanish": "limpiar", "kana": "そうじします" },
        { "spanish": ["lavar la ropa", "hacer la colada"], "kana": "せんたくします" },
        { "spanish": ["convertirse", "hacerse", "llegar"], "kana": "なります" },
        { "spanish": ["practicar", "ensayar"], "kana": "れんしゅうします" },
        { "spanish": "practicar sumo", "kana": "すもうします" },
        { "spanish": "hacer ceremonia del té", "kana": "おちゃをします" },
        { "spanish": "marear", "kana": "よいます" },
        { "spanish": ["dejar de funcionar", "estropearse", "averiarse"], "kana": "こしょうします" },
        { "spanish": ["necesitar", "requerir"], "kana": "いります" },
        { "spanish": ["buscar", "averiguar", "investigar"], "kana": "しらべます" },
        { "spanish": "reparar", "kana": "しゅうりします" },
        { "spanish": ["vamos a", "hagámoslo"], "kana": "そうします" },
        { "spanish": ["creer", "opinar"], "kana": "おもいます" },
        { "spanish": "decir", "kana": "いいます" },
        { "spanish": "ganar", "kana": "かちます" },
        { "spanish": ["perder", "ser derrotado"], "kana": "まけます" },
        { "spanish": "ser útil", "kana": "やくにたちます" },
        { "spanish": ["funcionar", "moverse"], "kana": "うごきます" },
        { "spanish": ["dimitir", "dejar"], "kana": "やめます" },
        { "spanish": ["prestar atención", "tener cuidado"], "kana": "きをつけます" },
        { "spanish": "estudiar en el extranjero", "kana": "りゅうがくします" },
        { "spanish": "jugar un partido", "kana": "しあいをします" },
        { "spanish": "reformar", "kana": "リフォームします" },
        { "spanish": ["dar", "freir", "regalar"], "kana": "あげます" },
        { "spanish": ["tener suficiente", "ser suficiente"], "kana": "たります" },
        { "spanish": "lo creo", "kana": "そうだとおもいます" },
        { "spanish": "no lo creo", "kana": "ちがうとおもいます" },
        { "spanish": "ponerse camisa", "kana": "ふくをきます" },
        { "spanish": ["ponerse zapatos", "ponerse pantalones"], "kana": "くつをはきます" },
        { "spanish": "ponerse sombrero", "kana": "ぼうしをかぶります" },
        { "spanish": "ponerse gafas", "kana": "めがねをかけます" },
        { "spanish": "ponerse corbata", "kana": ["ネクタイをします", "ネクタイをしめます"] },
        { "spanish": "nacer", "kana": "うまれます" },
        { "spanish": ["felicidades", "felicitaciones"], "kana": "おめでとうございます" },
        { "spanish": "ponerse accesorio", "kana": "とけいをつけます" },
        { "spanish": "mentir", "kana": "うそをつきます" },
        { "spanish": "aprender", "kana": "まなびます" },
        { "spanish": "ver una pesadilla", "kana": "あくむをみます" },
        { "spanish": "girar", "kana": "まわします" },
        { "spanish": ["tirar", "jalar", "enfermar"], "kana": "ひきます" },
        { "spanish": "tocar", "kana": "さわります" },
        { "spanish": "caminar", "kana": "あるきます" },
        { "spanish": "cruzar", "kana": "わたります" },
        { "spanish": ["doblar", "girar"], "kana": "まがります" },
        { "spanish": "lanzar", "kana": "なげます" },
        { "spanish": ["ir sin permiso de los padres", "fugarse"], "kana": "かけおちします" },
        { "spanish": "buscar", "kana": "さがします" },
        { "spanish": "pintar", "kana": "ぬります" },
        { "spanish": "engordar", "kana": "ふとります" },
        { "spanish": "darme", "kana": "くれます" },
        { "spanish": ["reparar", "arreglar", "corregir"], "kana": "なおします" },
        { "spanish": "llevar", "kana": "つれていきます" },
        { "spanish": "traer", "kana": "つれてきます" },
        { "spanish": ["acompañar", "llevar", "enviar"], "kana": "おくります" },
        { "spanish": "presentar", "kana": "しょうかいします" },
        { "spanish": ["guiar por", "indicar el camino"], "kana": "あんないします" },
        { "spanish": "quedarse en habitaciones separadas", "kana": "べつべつにとまります" },
        { "spanish": ["pensar", "considerar"], "kana": "かんがえます" },
        { "spanish": "llegar", "kana": "つきます" },
        { "spanish": "envejecer", "kana": "としをとります" },
        { "spanish": "enfadarse", "kana": "むかつきます" },
        { "spanish": "pasar tiempo", "kana": "たちます" }
    ]
}